### ISSUE TITLE
Clarification in readme how to use create_template script

### ISSUE THREAD

**Issue by Xnygra** [custom-components/nordpool#10]
I am having trouble understand how to use the create_template script in HA. Where and how should you execute the script? Just a bit more explanation in the readme.md file would be much appreciated. 
Thank you for your good work

**Comment by Hellowlol** [comment]
It doesnt matter where you execute the script. You the only requirement is that python needs to be install on the system. The idea is to copy paste the output to your own sensors.yaml

**Comment by Hellowlol** [comment]
I updated the readme. :)
