### ISSUE TITLE
Where is config stored

### ISSUE THREAD

**Issue by dsl10007** [custom-components/nordpool#101]
After installing this i was prompted for settings in the GUI and entered them, but afterwards i have been wanting to change some of the settings, but i can not find where these settings are stored, i have looked in the "Nordpool" folder and in configuration.yaml, but i can not find them.

**Comment by Hellowlol** [comment]
You can’t edit the sensor. It isn’t supported. Just delete the sensor and set it up again.

**Comment by dsl10007** [comment]
Okay, i will do that.

I have made a "feature request" to ask for the settings to be made editable after the sensor has been created, i hope that is ok :)

**Comment by Hellowlol** [comment]
That's fine no problem :)
