### ISSUE TITLE
Get Price From a specific date

### ISSUE THREAD

**Issue by ethante** [custom-components/nordpool#108]
Hey guys.

Can it be done so you can state a special date, so you can get the calculated price pr. hour for the stated date,    

many of "us" get our power consumption from the company called (https://eloverblik.dk/) where we can only se what our consumption was from 2 days ago.

so it would be nice if you could state a date and get hourly price from that date, that would be amazing.

**Comment by Hellowlol** [comment]
I don't understand, is the usage delayed with up to two days from eloverblik? You don't get real time usage?

**Comment by ethante** [comment]
Yes that is correct, the usage is delayed by 2 days, that's why it could be nice to set a date you want the nu er from as a ekstra feature 😊

**Comment by Hellowlol** [comment]
That’s out of scope of this project. Have you looked at https://www.home-assistant.io/integrations/history_stats this with some template should get you going.
