### ISSUE TITLE
SYS is system price

### ISSUE THREAD

**Issue by bardahlm** [custom-components/nordpool#111]
Re https://github.com/custom-components/nordpool/blob/7d3a8ca253c560d1aeb6f779fa58efb82d55b921/custom_components/nordpool/aio_price.py#L33

SYS, system price is _an unconstrained market clearing reference price for the Nordic region. It is calculated without any congestion restrictions by setting capacities to infinity._ 

In other words, a price where Ohms law does not apply in the grid.

https://www.nordpoolgroup.com/trading/Day-ahead-trading/Price-calculation/

**Comment by Hellowlol** [comment]
Thanks!
