### ISSUE TITLE
Store only one sensor state per day

### ISSUE THREAD

**Issue by angainor** [custom-components/nordpool#113]
Currently, the nordpool sensor is updated every hour. Since the hourly prices do not change once published, there is IMO not much use of storing the sensor 24 times per day, just to update the state to the current hourly price. This uses much more space than necessary in the db.

Would it be a good idea to add an option that would allow for once per day saving of the sensor state?

**Comment by Hellowlol** [comment]
I don’t understand what the issue is. The state changes for every hour. I don’t see the problem. Are the state saved more then 24 times a day?

**Comment by angainor** [comment]
@Hellowlol well, it's not really a problem, that's why I thought I submitted an enhancement request. 

The thing is that - at least from my experience - it would be easier to look at the history prices if there was only one sensor reading per day. Also, the database would be smaller. One entry in the current sensor take 4096 bytes just for the attributes. That makes 35Mb over one year. Sure, it doesn't sound like much, unless you are using RP with a small sd card.

I guess maybe one reading is not enough - you probably need two. One at midnight and one when new prices arrive. As I said, this is not a problem really, just thought it would be a cleaner solution. Feel free to ignore this if you disagree.

**Comment by angainor** [comment]
@Hellowlol On the other hand, I guess this is probably due to my lack of understanding of how HA storage works. I guess I need some alternative storage solution for long-term. You are right, this is probably completely irrelevant.

**Comment by Hellowlol** [comment]
I think the default settings for the recorder prunes the db every 10 days so unless you have changed the recorder settings, the db size should be rather small. If you are want stats over time I would suggest you looking into influxdb and grafana. I think these tools does a better job then the history page.

If you are worried about space you can omit integrations for the recorder.

Have you looked at https://community.home-assistant.io/t/how-to-keep-your-recorder-database-size-under-control/295795 ?

**Comment by angainor** [comment]
@Hellowlol Brilliant, thank you!
