### ISSUE TITLE
Attributes are written with underscore except for "low price"

### ISSUE THREAD

**Issue by nord-** [custom-components/nordpool#114]
https://github.com/custom-components/nordpool/blob/5f1a4ef3470ad8203911f3c0ea0e8e3bf4793676/custom_components/nordpool/sensor.py#L387

All attributes/properties are written with underscore as separator except for "low price" which uses a space. 

`off_peak_1` and `off_peak_2` were changed in last release to reflect this, but not "low price".

**Comment by janneojala** [comment]
Fixed in this PR [71ad373270d853440a7ca22b64304c9904756ba8](https://github.com/custom-components/nordpool/pull/121/commits/71ad373270d853440a7ca22b64304c9904756ba8#diff-859aedf8e471e5e27a31f0c61d4899e8476c6343cb5c1099b8d19563518e68bcR402)
