### ISSUE TITLE
Add daily average

### ISSUE THREAD

**Issue by twk99** [custom-components/nordpool#116]
Hi!

I live in SE3-area and I guess I pay by the daily average, not the hourly price. Is it possible to add Daily average as an option for the sensor?

Does this make sense? I'm new to this :)

**Comment by nsimb** [comment]
If you fint havet a hour based contract, and not fixed.price.you Will havet a volymen avrage Price from youre retailer. In Swedish thia is refered to as "månadsmedel". Om topp of that you get a surecharge. Its not just THE avrage Price from Nordpool, it takes in THE avrage consuption parterna for youre area

**Comment by twk99** [comment]
Okay, thank you! Perhaps daily average from Nordpool would still be the closest value, even if It's not exactly what I pay.

**Comment by AndersHub** [comment]
I don't understand if I shall choose Card-mod or template then I want to change font-size and decimals in an Entity card. And I have tried both methods but no success so far. Just in this example, I try to get the "average" attribute from Nordpool. I can i.e change color but not size and round to 3 decimals. 
I will appreciate an answer with recommendations and code.

**Comment by Hellowlol** [comment]
@AndersHub your can round using the integration as for the other questions I don’t know but I would start googling lovelace.
