### ISSUE TITLE
VAT Calculation

### ISSUE THREAD

**Issue by raudraido** [custom-components/nordpool#117]
When I add VAT+nordpool price + my template price together - app gets wrong result.
It's working any other combination, but with not those 3 together.

Example: 
Nordpool price 0,13008 + my template price 0,0281 = 0,1582 Correct
Nordpool price 0,13008 + VAT20% (Estonia) 0,03164 = 0,1561 Correct
Nordpool price 0,13008 + VAT20% (Estonia) 0,03164 + my template price 0,0281 = 0.1842 Wrong. Should be 0,1898.

What is happening?

**Comment by raudraido** [comment]
Ol, now I understand whats happening. I assumed thah vat well be added to nordpool price+template price sum, but actually vat is added to nordpool price and template price added after that

**Comment by Hellowlol** [comment]
I disagree, that makes it harder if the additional costs has another vat percentage

**Comment by raudraido** [comment]
You are right. But would be nice if explained how VAT is calculated.
