### ISSUE TITLE
Unavailable sensor

### ISSUE THREAD

**Issue by olealm** [custom-components/nordpool#118]
## Version of the custom_component

"version": "0.0.4"

## Homeassistant version
2022.2.6

## Configuration
nordpool:

sensor:
  - platform: nordpool
    VAT: True
    currency: "NOK"
    low_price_cutoff: 0.88
    region: "Bergen"
    precision: 3
    price_type: kwh
    friendly_name: "Nordpool spotpris inkludert mva"
    additional_costs: "{{0.33|float}}"
```yaml

Add your logs here.
Logger: homeassistant.components.sensor
Source: custom_components/nordpool/sensor.py:278
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 01:45:42 (2 occurrences)
Last logged: 01:45:42

Error adding entities for domain sensor with platform nordpool
Error while setting up nordpool platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 781, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/nordpool/sensor.py", line 488, in async_added_to_hass
    await self.check_stuff()
  File "/config/custom_components/nordpool/sensor.py", line 449, in check_stuff
    self._update(today)
  File "/config/custom_components/nordpool/sensor.py", line 308, in _update
    formatted_prices = [
  File "/config/custom_components/nordpool/sensor.py", line 309, in <listcomp>
    self._calc_price(
  File "/config/custom_components/nordpool/sensor.py", line 278, in _calc_price
    price = template_value + value / _PRICE_IN[self._price_type] * (
TypeError: can only concatenate str (not "float") to str
```

## Describe the bug
I have struggled with the Nordpool sensor for ages. Put it away last year but tried again now. Still the same - The sensor is unavailable and there are faults in the log as shown above.
The sensor has been set up via yaml as shown above, because trying to add the sensor via the GUI throws an error for the template-value, no matter what I write in that field. Have tried "0", "{{0.0|float}}", "{{0.33|float}}" anda few others..

For the yaml I have tried everything from basic setup (region only) to the setup shown above. Also tried VAT True and False.

## Debug log

```text

Add your logs here.

```

**Comment by olealm** [comment]
![image](https://user-images.githubusercontent.com/42977984/153762260-1153d64e-5648-499a-beb1-5460cad27f53.png)

empty, {{0.0}}, {{0.33}}, {{0.0|float}}, 0.33|float(default=0 (with and without quotes) all throws an error in the GUI and also not working if added via .yaml.
Oh, and {{ 0.33|float(default=0) is string }} returns False in the template editor, is number returns True.

**Comment by olealm** [comment]
![image](https://user-images.githubusercontent.com/42977984/153770906-fe05d038-9d9c-44cc-9ab1-7e02854b2ba8.png)

**Comment by Hellowlol** [comment]
Just the template. Remove the is …
no identity check as you do now.

**Comment by olealm** [comment]
Like this?
![image](https://user-images.githubusercontent.com/42977984/153772479-cf98a17a-76a8-42fb-bc3b-6a44814f2375.png)

**Comment by Hellowlol** [comment]
Yes. But you have to snip the image with the template type. It’s listed above the output value

**Comment by olealm** [comment]
This one? If so, it looks static. It states result type: string even if i empty the editor completely.
![image](https://user-images.githubusercontent.com/42977984/153779601-2f7f55fb-72d5-4ad6-a73e-6d6cc9cfd9cf.png)

**Comment by Hellowlol** [comment]
Well a empty template is s string so clearing that would do that. 

Your can check that isnt static by using {{[1,1]}} that would return a list as long as the template engine works as intended.

**Comment by olealm** [comment]
Yeah, it's static.
![image](https://user-images.githubusercontent.com/42977984/154105411-ae20b7a1-b1a7-455f-b958-eab9f1678ddf.png)
