### ISSUE TITLE
Avg. price for tomorrow

### ISSUE THREAD

**Issue by jeppii** [custom-components/nordpool#123]
Is there any way to get the average price for tomorrow from this integration? I have now locked my electricity price, and wants to set up a notification when the price for tomorrow is below, so I can change it back.

**Comment by Hellowlol** [comment]
Use a template sensor 😀

**Comment by jeppii** [comment]
Okey, I need to add them all together and divide on the amount? Or do you now an other way with a template sensor?

**Comment by Hellowlol** [comment]
Check the template docs. There is a average filter you can use.

**Comment by jeppii** [comment]
Okey thanks. I will check it out
