### ISSUE TITLE
Nordpool and Apex Graph not working anymore

### ISSUE THREAD

**Issue by TheEnergy** [custom-components/nordpool#126]
I use this script.

type: custom:apexcharts-card
graph_span: 24h
experimental:
  color_threshold: true
header:
  title: Elpris i dag (kr/kWh)
  show: true
apex_config:
  yaxis:
    min: 0
hours_12: false
span:
  start: hour
  offset: '-2h'
now:
  show: true
  label: Pris nu
series:
  - entity: sensor.pris
    type: column
    data_generator: |
      return (entity.attributes.raw_today.map((start, index) => {
        return [new Date(start["start"]).getTime(), entity.attributes.raw_today[index]["value"]];
      })).concat(entity.attributes.raw_tomorrow.map((start, index) => {
        return [new Date(start["start"]).getTime(), entity.attributes.raw_tomorrow[index]["value"]];
      }));
    color_threshold:
      - value: 0
        color: green
      - value: 1
        color: orange
      - value: 2
        color: red
      - value: 3
        color: darkred
      - value: 4
        color: black

https://github.com/custom-components/nordpool/issues/19

It have been working fine, but after update something i broken.
I can restart my home assistant and i pool data and works for the 24 hours. But it will not refresh itself afterwards.
Home Assistant 2022.3.5

only thing i can find in the logs is this.
2022-03-20 07:15:05 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration nordpool which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

But nothing else.
Here is the graph, i know about the 24 hour rule and you cant see much forward, but later i can post the graph when nothing is refreshed.
![image](https://user-images.githubusercontent.com/54671083/159159147-a8b9a9ef-7592-4665-a8a0-400131598065.png)

**Comment by ricmik** [comment]
I suspect this is due to the reported issue #124 ?

**Comment by TheEnergy** [comment]
> I suspect this is due to the reported issue #124 ?

Yea seems like it.
