### ISSUE TITLE
Best approach detecting high peaks

### ISSUE THREAD

**Issue by janneojala** [custom-components/nordpool#128]
Thank you for this nice piece of code. My question is not directly related to Nordpool component, but I'd like to hear what kind of approaches other users have taken to identify upcoming high peaks. My problem is following: in order to minimized usage of expensive energy on heating and I'd like to benefit the low cost period to preheat my house few degrees above normal target temperature, so that during the high peak target temperature of heating could be set to few degrees below normal target temperature. Basically I'd need to know before hand length of upcoming high peak period is and we it starts.

**Comment by ricmik** [comment]
Hi @janneojala,

I know that some people use Node-RED with https://github.com/ottopaulsen/node-red-contrib-power-saver 

There is a node called heat capacitor that does exactly what you are looking for.

**Comment by janneojala** [comment]
Great, thanks @ricmik ! I will definitely take a look of this project!
