### ISSUE TITLE
Transfer Fee request

### ISSUE THREAD

**Issue by mnuxx** [custom-components/nordpool#130]
In Estonia, we have transfer fee. Its one fee 07.00-23.00 week days and another  23-07 and weekends. To make better decision when to charge battery. For example  Friday 18.00 100€ mwh is more expensive then 23.00 120€ mwh 
My fees are daytime 34€ mwh and night time + weekends 19.4€ mwh.
Tariff are good to show current hour actual price, but to make decision whole day +  next day to find best hours is difficult.

**Comment by janneojala** [comment]
Not sure if I understood you correctly, but additional_costs: property is nice way include other costs related to energy price:

`
additional_costs: '{% set s = {
        "hourly_fixed_cost": 0.0024,
        "day": 0.0259,
        "night": 0.0135
}
%}
    {% if now().hour >=6 and now().hour <23 %}
        {{s.day+s.hourly_fixed_cost|float}}
    {% else %}
        {{s.night+s.hourly_fixed_cost|float}}
    {% endif %}'
` 
In Finland we also have separate costs for transfer during day and night. This helps make better decisions when adjusting current load ia. heating or such.

**Comment by mnuxx** [comment]
Im sorry for being stupid :)
For being new in HA and templating documentation was a little bit hard to understand. Your sample could be there, would make much more sense.
Thank you for explaining.
