### ISSUE TITLE
Adding integration fails with jinja error

### ISSUE THREAD

**Issue by fvant** [custom-components/nordpool#134]
Error importing platform config_flow from integration nordpool to set up nordpool configuration entry: cannot import name 'contextfunction' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)

Home Assistant 2022.4.0b6
HACS  1.24.3
Home Assistant OS 7.6

**Comment by Hellowlol** [comment]
I'll make a new release later today. :)

**Comment by Hellowlol** [comment]
Workaround until release, https://github.com/custom-components/nordpool/pull/132
