### ISSUE TITLE
Multiple sensors with seperate but similar config ?

### ISSUE THREAD

**Issue by ujhede** [custom-components/nordpool#136]
## Configuration

- platform: nordpool
  VAT: False
  currency: "DKK"
  low_price_cutoff: 0.95
  region: "DK2"
  precision: 4
  price_type: kWh
  additional_costs: '{% set s = {
    "lavlast": 0.3003,
    "spidslast": 0.7651,
    "elafgift": 0.9030
}
%}
{% if now().month >= 10 and now().month <=4 %}
    {% if now().hour >= 17 and now().hour <= 20 %}
        {{s.spidslast+s.elafgift|float}}
    {% endif %}
{% else %}
  {{s.lavlast+s.elafgift|float}}   
{% endif %}'

- platform: nordpool
  VAT: False
  currency: "DKK"
  low_price_cutoff: 0.95
  region: "DK2"
  precision: 4
#  price_type: kWh
#  additional_costs: {{0.0|float}}"
Add your logs here.

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:593
Integration: Sensor (documentation, issues)
First occurred: 21:55:13 (1 occurrences)
Last logged: 21:55:13

Platform nordpool does not generate unique IDs. ID nordpool_kwh_dk2_dkk_4_095_0 already exists - ignoring sensor.nordpool_kwh_dk2_dkk_allin

## Describe the bug

It does not seem to be possible to create mukltiple sensores with the same parameters that are used in the sensor id.  I see a similar issue has been reported in #66 But I don't know HA well enought to know if it is actually the same issue.

## Debug log

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:593
Integration: Sensor (documentation, issues)
First occurred: 21:55:13 (1 occurrences)
Last logged: 21:55:13

Platform nordpool does not generate unique IDs. ID nordpool_kwh_dk2_dkk_4_095_0 already exists - ignoring sensor.nordpool_kwh_dk2_dkk_allin
Add your logs here.

```

**Comment by Hellowlol** [comment]
Closing this duplicate. You can’t have two identical sensors. You change the precision settings as a workaround
