### ISSUE TITLE
Completely broken after reboot

### ISSUE THREAD

**Issue by dogmatic69** [custom-components/nordpool#137]
## Homeassistant version

2022.4.1

## Configuration

Config flow 

## Describe the bug

Integration not loaded. Error log says "Failed to set up: Import error"

Started today running the previous version but persists after upgrade through HACS and numerous reboots. 

## Debug log

```text

Logger: homeassistant.config_entries
Source: config_entries.py:316 
First occurred: 13:58:09 (2 occurrences) 
Last logged: 17:23:27

Error importing platform config_flow from integration nordpool to set up nordpool configuration entry: cannot import name 'contextfunction' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)

```

**Comment by Hellowlol** [comment]
Then you need to fix your install.
