### ISSUE TITLE
Not able to set VAT to False

### ISSUE THREAD

**Issue by AlexxHansson** [custom-components/nordpool#14]
I can´t seem to get rid off the VAT.

```
  - platform: nordpool
    region: "SE4"
    VAT: False
```

The VAT is still added.

**Comment by Hellowlol** [comment]
Hm, that seems strange. Is this setup using yaml or config flow?

**Comment by AlexxHansson** [comment]
yaml

**Comment by Hellowlol** [comment]
tried lower case false?

**Comment by AlexxHansson** [comment]
Yes i have. I had a quick look in the code but it seems prettu straight forward so i don’t know... 😕

**Comment by Hellowlol** [comment]
I dont see any reason why this should fail, Can you post the entity id?

**Comment by AlexxHansson** [comment]
`sensor.nordpool_kwh_se4_sek_3_10_025`

**Comment by Hellowlol** [comment]
The entityid tells me that tax should be included. Can you try to setup the sensor using the webui?

**Comment by AlexxHansson** [comment]
I am running Hass in docker so i don´t know if it is possible?

**Comment by Hellowlol** [comment]
Inside the home assistant web ui: click menu -> Configuration -> Integration -> search for nordpool, click ok -> enter the settings

**Comment by AlexxHansson** [comment]
Ah! Integrations, sorry :D

I can confirm that this works fine!
