### ISSUE TITLE
Home assistant  /config/.storage/core.config_entries not updated if configuration.yaml changed

### ISSUE THREAD

**Issue by MEKadan** [custom-components/nordpool#141]
I'm not quite sure how to report / ask this, but You will probably guide me forward, if this is not a right place/ way.

I already wrote a description about the situation I'm facing to under Home Assistant Community / Configuration. Link:

https://community.home-assistant.io/t/any-good-ideas-are-welcome-nordpool-energy-price-per-hour/34646/141?u=mekanics

Later it occurred to mind that this would probably be a better starting point, so I'm sorry about double posting, if this is considered to be such. 

Anyway:
2 separate systems under same local network. Raspberry Pi 4 4GBs with HAOS + all the latest updates. Both have Norpool component installed from HACS and corresponding definitions in configuration.yaml. Both systems under same LAN and sharing of course the same external IP, when communicationg to Nordpool.

Problem is mainly in additional costs; I have specified them in configuration.yaml, but they do not get updated in  /config/.storage/core.config_entries, which, I suppose, is causing most of the problems described in the link provided. 

Secondly, it looks like the 2 systems interfere. Is it possible that Nordpool does not take well situatiuon when it gets communication from 2 devices, but from same IP?

Any advice?

**Comment by Hellowlol** [comment]
Sorry man. I don’t know. The api is flaky from time to time, so maybe http call on rpi 1 is successful but rpi2 fails
