### ISSUE TITLE
sensor cheapest hours

### ISSUE THREAD

**Issue by sunkan85** [custom-components/nordpool#142]
sensor that gets on or off the 5 cheapest hours a night sensor and a day sensor.  is it possible to do it to charge the electric car at the best price?

the price of electricity has started to go up and down so much.  so% or average price works poorly

**Comment by Skeletorjus** [comment]
I did something similar as a template sensor. Not elegant at all, but it works. I use it to control the water heater. 

https://community.home-assistant.io/t/any-good-ideas-are-welcome-nordpool-energy-price-per-hour/34646/71?u=skeletorjus

**Comment by sunkan85** [comment]
i will try it thx

Den ons 27 apr. 2022 kl 20:30 skrev Skeletorjus ***@***.***>:

**Comment by sunkan85** [comment]
The linked soulution did work good
