### ISSUE TITLE
Min and Max are not looking at tomorrow

### ISSUE THREAD

**Issue by AJediIAm** [custom-components/nordpool#152]
I recently began using this component and it looks great! I looked at several components which do a similar thing and this is by far the most complete. There are a small number of small suggestions which I would like to mention:

1) I wanted to use the min and max values to automate my EV charger, but I noticed it only looks at today, even when tomorrow is available. It would be really useful to know the min and max value of all future prices (from now until the latest available time). 

2) Could you describe the attributes such as average, off_peak, peak and low price? It's not entirely clear how they are calculated. 

3) some attributes such as average and off_peak are not rounded as specified in the configuration

4) Is it possible to change the configuration when the UI is used? I cannot adjust the taxes or rounding digits, so I have to recreate the entity every time I want to change something. (I guess I could use configuration.yaml instead).

**Comment by Hellowlol** [comment]
1. This isn’t supported. What would you use the average price for? 
2. Average is just that. Offpeak etc is the hours that nordpool uses.
3. This will happen is you use a custom template
4.  This isn’t supported atm, using yaml would be a bad solution imo. It’s on my todo list

**Comment by AJediIAm** [comment]
1) I don't want them use the average price. I want to use the minimum and maximum price to determine when to charge or discharge my battery.

2) Can I update the documentation to include this information for completeness? I haven't contributed before, but I'm willing to help.

3) Can't the template be wrapped by the right rounding math?

4) Can I buy you a coffee to support you?

**Comment by tarmor1** [comment]
> 2. Could you describe the attributes such as average, off_peak, peak and low price? It's not entirely clear how they are calculated.

These are the official definitions: https://www.energiforetagen.se/globalassets/energiforetagen/det-erbjuder-vi/kurser-och-konferenser/krisutbildningar/nord-pool-spot-glossary.pdf

_Peak refers to the average price of the period from 8am to 8pm.
Off peak 1 refers to the average price of the time period from midnight to 8am and off peak 2 refers to the average price of the time period from 8pm to midnight._

**Comment by Hellowlol** [comment]
> 1. I don't want them use the average price. I want to use the minimum and maximum price to determine when to charge or discharge my battery.
That can be added, just create a feature request.
> 2. Can I update the documentation to include this information for completeness? I haven't contributed before, but I'm willing to help.
Yes please! Click the edit button and add the information that you want. Use the editor and preview to make sure it look ok.
> 3. Can't the template be wrapped by the right rounding math?
Create a feature request
> 4. Can I buy you a coffee to support you?
That would be nice! Thanks. I added buymecoffe and Paypal donation button to the first page.
