### ISSUE TITLE
Peak period value incorrect

### ISSUE THREAD

**Issue by tarmor1** [custom-components/nordpool#154]
Looks like the PEAK period value averaging has wrong index and returns incorrect value.

https://github.com/custom-components/nordpool/blob/7d792d89e8d30e713d7ac47dbff42047c1cf8a75/custom_components/nordpool/misc.py#L106
Should be 8am to 8pm by definition.
See as well definitions in https://github.com/custom-components/nordpool/issues/152#issuecomment-1139563930

**Comment by Hellowlol** [comment]
Hi!

The code is correct. What we are referring to there are the indices in the list. Python is 0 indexed
It's easier to visualize it. See the example in the link.

https://replit.com/@Hellowlol/WickedThisGenre#main.py

**Comment by tarmor1** [comment]
Hey!

Thanks for coming back! I'm still puzzled and for me it's evident from the code (and the example you posted) that some hours are just discarded, whether to consider the values as Time (UTC, Local or whatever) or index.

I did a small comparison of values the component calculates and how it represents to actual values included.
The values date for Estonian /EE prices on 28th of May 2022.

As I'm having prices in HA in cents/kWh and incl VAT, I did another columns of comparison and this is what I came up with.
![image](https://user-images.githubusercontent.com/106139715/170829817-02d9706a-9205-4bb5-9a7c-169094e0be36.png)

In left are the prices from Nordpool web in EE (wo VAT, €/MWh), in left copy-paste from Attributes list in HA, and calculated back to Nordpool (that is, without VAT and €/MWh.

What I see is that from the resulting calculation CET times 7, 16,17,18 are not included to the respective averages.

**Comment by Hellowlol** [comment]
Your price example are off and will never be correct because your not using the correct hours. If peak  is 12 hours we are clearly discardinc hours. I think the peak stopped at hour 1800 before. That what i have coded 😂 ill check all the peaks and update the code.

**Comment by tarmor1** [comment]
Hey!

I agree this is a matter of definition of peak. Indeed in Nordpool it's 12 hrs, right between off_peak_1 and off_peak_2.

_Peak refers to the average price of the period from 8am to 8pm.
Off peak 1 refers to the average price of the time period from midnight to 8am and off peak 2 refers to the average price of the time period from 8pm to midnight._ @ https://github.com/custom-components/nordpool/issues/152#issuecomment-1139563930

**Comment by Hellowlol** [comment]
https://github.com/custom-components/nordpool/pull/155
