### ISSUE TITLE
Sensor data not usable in additional cost

### ISSUE THREAD

**Issue by cpoulsen** [custom-components/nordpool#156]
I cant use sensor value in additional cost

```
  additional_costs: >
    {% if states('sensor.yearly_energy_usage') | float > 4000 | float %}
      {{0.55|float}}
    {% else %}
       {{1.45|float}}
    {% endif %}
```

`Template warning: 'float' got invalid input 'unknown' when rendering template '{% if states('sensor.yearly_energy_usage') | float > 4000 | float %} {{0.55|float}} {% else %} {{1.45|float}} {% endif %}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.6`

Works perfectly fine in a template

**Comment by Hellowlol** [comment]
This nothing to do with nordpool. The error message clearly states the issue. You can read some details here https://community.home-assistant.io/t/updating-templates-with-the-new-default-values-in-2021-10-x/346198
