### ISSUE TITLE
sensor device-class as monetary

### ISSUE THREAD

**Issue by RafSchandevyl** [custom-components/nordpool#160]
could you create the sensor with device class monetary, at that moment they the price will be kept in the historical data.  Is good for trend information and historical statistics.

**Comment by Hellowlol** [comment]
For now the workaround is to use a template sensor for this.

**Comment by Strixx76** [comment]
To "fix" this and #188 you have to import 
```
from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
)
```
And add the following attributes to the sensor:
```
_attr_device_class = SensorDeviceClass.MONETARY
_attr_state_class = SensorStateClass.MEASUREMENT
```

**Comment by nordicgit70** [comment]
@Strixx76 I tried to implement your code change (in a pull request) but it does not activate statistics. 
The entity properties are not updated in the registry. Is any other action needed to trigger an update?

**Comment by nordicgit70** [comment]
Statistics started working with minor adjustment to import the SensorEntity.
I will create a pull request after some more testing.

```
from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntity,
    SensorStateClass,
)
```
