### ISSUE TITLE
Additional cost as an attribute

### ISSUE THREAD

**Issue by SVH-Powel** [custom-components/nordpool#162]
Make additional cost an attribute so that we can see that it has the correct value thru the day. As it is now, there is no feedback that the configuration is correct.

**Comment by xotoy** [comment]
It is obviously a great deed setting up the Nordpool sensor and it is much appreciated! I agree with your suggestion, for instance, plotting the price including the additional costs make more sense! 

In addition, it would be great with some additional instructions on how to actually implement the additional tariff in the Nordpool sensor. Being something of a n00b, I have not been able to figure out how make it work. I have plots and I automated my heavy consumers to the cheaper hours, but without the tariff impact taken into account.

**Comment by Hellowlol** [comment]
I agree! This is an excellent and straightforward PR for a first-time contributor.

**Comment by Hellowlol** [comment]
Added in 0.0.9
