### ISSUE TITLE
VAT in NL region will temporarily be 9% instead of 21%

### ISSUE THREAD

**Issue by sicco92** [custom-components/nordpool#163]
First of all, thank you so much for this integration. I've been using it for a while and it works really well! I've been using it to get prices from the Netherlands region.

The reason for this issue is that the VAT in the Netherlands will temporarily change from 21% to 9%, starting 1 July 2022. For now it looks to be reverted to 21% after 31 December 2022. 

I searched through the code, but I couldn't find anything that makes me think this temporary change is accounted for. Could you confirm that? If so, is there a way to easily account for this temporary change?

I want to help, but I'm not very experienced with Python projects. My solution would be to just change this value to 0.09 and add a comment saying it needs to be reverted to 0.21 after 31 December:
https://github.com/custom-components/nordpool/blob/2a33bd779c71054cb74d8afcc2470061524d4d2a/custom_components/nordpool/sensor.py#L44

If you want that as a solution, I could make a PR with those changes. Just let me know if that's something you'd want.

**Comment by Hellowlol** [comment]
Hi! Thanks for using the component.

Currently there isn’t any way to change the tax without modifying the code as you have done. But a better solution would be to add the current price as a variable to the template. That way you can turn off vat in the settings and do your own calculations. 

Example:
{{current_price * 0.09 | float }}

**Comment by sicco92** [comment]
I added a pull request for this issue. I couldn't get your idea of using 'current_price' in the template to work, so this was my solution.

**Comment by AJediIAm** [comment]
I also created a pull request for this: https://github.com/custom-components/nordpool/pull/171
It's currently blocked because another dependency thingy needs to be fixed first.

**Comment by Pihlflykt** [comment]
I would like to remove the VAT entirely as we do not get the VAT in Sweden when we sell electricity. I tried to change the value 0.25 in sensor.py but the sensor keeps failing for any other value than 0.25. 
What am I missing here? Do I need to change the value somewhere else instead?

**Comment by Hellowlol** [comment]
Setup the sensor without vat? This a own setting.

**Comment by Pihlflykt** [comment]
> v

I cannot find any other setting, except for the setting that says "True" for VAT. (in the configuration.yaml) Tried to change this to "false" but that also fails the sensor.

**Comment by Pihlflykt** [comment]
Update - I just discovered that when VAT is set to false - an entirely new sensor pops up and the "old" sensor stops working. This was confusing for me but now my problem is solved. I simply use the new sensor that shows the price without VAT :)

**Comment by Hellowlol** [comment]
0.0.8 is out, with that you can calculate your own VAT. See the readme for more info
