### ISSUE TITLE
One single attribute with prices

### ISSUE THREAD

**Issue by SVH-Powel** [custom-components/nordpool#168]
As it is now, we have todays prices in an attribute named raw_today and tomorrows prices in raw_tomorrow. At midnight these two attributes are updated and this behavior makes automation more difficult than it need to be. There has to be code for handling an empty raw_tomorrow and automation finding the cheapest prices will loose history at midnight because data is cleared.

Would it be possible to create a new attribute (raw_prices) which is only updated once each day at 13:10 when the prices from Nordpool is ready and stay constand until the next day at 13:10?

**Comment by Hellowlol** [comment]
Yes, it would be possible to that but im not add it. I dont think its wise to have that many heavy attributes in a sensor. You can use automation and a template sensors to do this.
