### ISSUE TITLE
Sensor not showing up in HA

### ISSUE THREAD

**Issue by jtfidje** [custom-components/nordpool#17]
Copied all files into `[ha_config_folder]/custom_components/nordpool/`

Using the following config in `configuration.yaml`:
```
sensor:
  - platform: nordpool
    currency: "NOK"
    region: "Kr.sand"
    name: "Nordpool Spotpris"
```
Sensor does not show up in Home Assistant.

**Comment by Hellowlol** [comment]
Logs? Try setting it up using the UI

**Comment by jtfidje** [comment]
Sure. Apparently also something wrong with the resolution of met-api.

Not sure what you mean by "Try setting it up using the UI" :-/
Here's the logs though:

```
2020-03-01 18:47:52 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for nordpool which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-03-01 18:47:53 WARNING (SyncWorker_5) [zeroconf] Exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zeroconf.py", line 2245, in send
    bytes_sent = s.sendto(packet, 0, (addr, port))
OSError: [Errno 126] Required key not available
2020-03-01 18:47:53 ERROR (MainThread) [metno] https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/1.9/ returned Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Temporary failure in name resolution]
2020-03-01 18:47:53 ERROR (MainThread) [homeassistant.components.met.weather] Retrying in 16 minutes
```

**Comment by Hellowlol** [comment]
The logs didn’t really tell me anything except that the has loaded the component. Anyway. With ui I meant the web ui: Configuration > Integration > search for nordpool. You should also try to install it using hacs instead of manual install.

**Comment by jtfidje** [comment]
Have setup the logger now, but it brought nothing new to the table. It's just showing a bunch of INFO messages telling me the different components that's been loaded. ( neither `hacs` nor `nordpool` is one of them ). 

Here's a link to the logs: https://pastebin.com/NYxhs77v

I've followed the instructiosn for installing `hacs`, but it's not showing up in the list of integrations.
Maybe this is the problem - my instance og HA is not loading custom components as it should?

**Comment by Hellowlol** [comment]
I think you're onto something. I would delete the entire custom_components and start for scratch using this guide: https://hacs.xyz/docs/installation/manual

After hacs is up and running, install any (nordpool) package by clicking the Community on the left side menu in the webui.  After that you click INTEGRATIONS and search for nordpool and click it, Press install. Go back to the main interface by clicking overview and then click Configuration > Integration > search for nordpool, then enter your settings.

**Comment by jtfidje** [comment]
Following that guide HACS still won't show up in the Integrations list. 
However - I'll close this issue as it seems the problem is with my instance of HA :-)

Thx for all the help so far and super quick responses!

**Comment by Hellowlol** [comment]
Thanks! Let me know if you have any issues with the integration.

**Comment by winny-git** [comment]
I have the same issue.

Searching for nordpool under Add integration gives zero results.

Downloading the master branch version form github and extracting the zip file to `/opt/homeassistant/config/custom_components/nordpool` and adding the following to `/opt/homeassistant/config/configuration.yaml`:

```
#Nordpool
nordpool:

sensor:
  - platform: nordpool
    region: "SE3"
    VAT: True
    currency: "SEK"
    low_price_cutoff: 1
```

gives the following error message:

Configuration invalid!

Integration error: nordpool - Integration 'nordpool' not found.
Platform error sensor.nordpool - Integration 'nordpool' not found.
