### ISSUE TITLE
All sensors is not updated after a restart of HA

### ISSUE THREAD

**Issue by and117** [custom-components/nordpool#173]
## Version of the custom_component
0.0.7

## Homeassistant version
Home Assistant 2022.7.5
Supervisor 2022.07.0
Operating System 8.2
Frontend-version: 20220707.1 - lates

## Configuration

Use HA integration for creating the sensors

## Describe the bug
Only one of my three sensors is updated after a restart of HA.

## Debug log

[nordpool_debug_220718.txt](https://github.com/custom-components/nordpool/files/9129895/nordpool_debug_220718.txt)

**Comment by Hellowlol** [comment]
Should be fixed in 0.0.8. If not please create a new issue
