### ISSUE TITLE
Previous hours price attribute/sensor.

### ISSUE THREAD

**Issue by ujhede** [custom-components/nordpool#176]
**Is your feature request related to a problem? Please describe.**

The hourly energy consumption provided by my car charger is "delayed" by about some minutes meaning that the energy used in an hour interval is not available until a few minutes after the end of the consumption period.

This makes calculating the price of the charging session a little difficult because the current price sensor updates at the hour so in order to calculate the price I need to use the price from the previous hour.

I could naturally calculate the previous hour interval and get the value of the specific hourly attribute but it would be nice if the value would just be available as another attribute of the sensor.  Then I would not have to deal with the complexities of handling date rolling :-) 

**Describe the solution you'd like**

Add an attribute that has the price of the previous hour interval.

**Describe alternatives you've considered**

Create a (for my templating skills) rather complex template sensor to do the calculation.  

I have considered if the change function from the statistics integration could be used but that seems to the first observation in the time series as a reference point.

**Additional context**
None that i can think of.

**Comment by Hellowlol** [comment]
Thanks for an detailed issue description. I will not add a attribute for last hour value, it’s easy to create a template sensor for this.
It will be something like .today[now().hour -1]

**Comment by ujhede** [comment]
Thanks for the feedback.

I tried playing with the template sensor before submitting this issue.  It works just fine 23 out of the 24 hours in a day. But it does not handle rolling over at midnight because when midnight is passed "todays" value for the 23-24 hour  is replaced by "tomorrows" and are no longer available.

I could maybe hack a workaround together saving the value in an input helper or something (a little beyond my HA skils)  like that but I just thought that having the sensor available might help other people with the same "problem".
