### ISSUE TITLE
Price mismatch

### ISSUE THREAD

**Issue by Lars6503** [custom-components/nordpool#179]
## Version of the custom_component
latest
-->

## Homeassistant version
2022-08-1

## Configuration
platform: nordpool
region: SE4
precision: 5

## Describe the bug
When accessing the entity I can see the values in data as well as raw data, but the number isn't the same as the number I can see at Nordpool site for SE4.
Is there a currency mismatch since the site uses euro and convert it to SEK with another conversion?

2022-08-09 21.00-22.00
Program report 5.42282
Site reports 4.33826

**Comment by winny-git** [comment]
That’s exactly 25 % difference, the VAT in Sweden. Check your include_VAT setting.

**Comment by Lars6503** [comment]
Thanks! 

winny-git ***@***.***> skrev: (2 september 2022 11:00:57 CEST)
>That’s exactly 25 % difference, the VAT in Sweden. Check your
>include_VAT setting. >
>>
>-- >
>Reply to this email directly or view it on GitHub:>
>https://github.com/custom-components/nordpool/issues/179#issuecomment-1235252011>
>You are receiving this because you authored the thread.>
>>
>Message ID:
***@***.***>

-This is not the (an)droid you're looking for.
