### ISSUE TITLE
Low price

### ISSUE THREAD

**Issue by ruant** [custom-components/nordpool#183]
Regarding the `low_price` boolean.
It states: `low_price = hour_price < average * low_price_cutoff`

Does that include tomorrow prices in the average if tomorrow prices are available?
Or just todays average?

**Comment by Rantaki** [comment]
I was already confused with the description as it says _low_price_ and the variable name is _low_price_cutoff_. Does that mean the same?

Now that I have tried different values by removing the integration and adding it again back via UI, I noticed that it would be useful to have possibility to configure the integration directly without having it removed. Could that be possible? 

Anyway thanks for the integration. Will be very useful during the next winter. I will try to have my garage heating optimized with this.

**Comment by Hellowlol** [comment]
@ruant Its only today's average. 
@Rantaki Thats correct :)
