### ISSUE TITLE
Long-Term Statistic 

### ISSUE THREAD

**Issue by PatricDahl** [custom-components/nordpool#188]
Hi,

Please implement Long-Term Statistic as described.
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by Strixx76** [comment]
This would be really great. My need for it is that I pay (like many others I guess) an "average" of the month (I know it is more to it than that). With long term statistics we could use the SQL integration to calculate the current average of the month.
I also have solar panels. And by comparing the current monthly average and the hourly price I can diced if it is better to sell or to use the generated power. (BTW The information in the above link seems to be incorrect, I have filed a issue [device_class of Long-term Statistics sensors](https://github.com/home-assistant/developers.home-assistant/issues/1474))

But until then you can always create a template sensor:
```
- name: "Total compensation"
  unit_of_measurement: "SEK/kWh"
  state_class: measurement
  device_class: monetary
  state: "{{ states('sensor.nordpool_kwh_se4_sek_3_10_0')|float(0) + (0.60 + 0.052) }}"
```
And you will have access to long term statistics.

**Comment by Hellowlol** [comment]
Closing this some as I don't know who to add this and add it to the energy dashboard. I think a simple template sensor is a good workaround.

**Comment by 0ki** [comment]
It seems that this was closed because of lack of developers, is that correct?
Should I open a new bugreport for this or can we reopen the old one to work on this?

**Comment by Hellowlol** [comment]
It was closed as someone create a pr that merged in. If if does not work please create a new pr
