### ISSUE TITLE
Memory Leak HA 2022.8.7

### ISSUE THREAD

**Issue by romlisrl** [custom-components/nordpool#190]
After installing component I've faced to the memory leaks of HA.
"python3 -m homeassistant --config /config" growing until probably HA restarts or HUP of python3 process.
When I disable the component - memory usage became stable.
My configuration is raspberry PI and HA under supervisor installation.
Memory leak was noticed on HA 2022.7 version and continued after update to the latest 2022.8.7
![image](https://user-images.githubusercontent.com/49437281/188712022-d97b39c6-6fd5-4031-8743-0eb0ac1fa4a1.png)
Total history of memory usage, beginning of the August is a time when was installed component.

[This topic I've create on HA community site with discussion.](https://community.home-assistant.io/t/memory-leak-from-2022-7/457565)

I'm very appreciate your job and very like to use it in future, but small worm of untrust starts eating me from inside. Please save me from this worm.

**Comment by Hellowlol** [comment]
I have no issues with mine. Hardt any changes has been done for a really long time. But it might be a memory leak for all i know 🤦‍♂️

How is this setup?

Can you share your config?

**Comment by romlisrl** [comment]
Sure, what exactly of config you are interested in?
I have raspberry pi 4 with 4GB RAM. Supervisor 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
[aboutHA.txt](https://github.com/custom-components/nordpool/files/9500226/aboutHA.txt)

**Comment by Hellowlol** [comment]
What version if nordpool is installed and what settings(in the sensor) are you using?

Unfortunately the info you provided just confirm that ha uses more memory, and not what the error is.

**Comment by romlisrl** [comment]
I was deactivated integration currently to collect statistic data.
Based on manifest  "version": "0.0.7".
![image](https://user-images.githubusercontent.com/49437281/188731138-03b5179b-171c-4350-b5eb-ea74425014c0.png)

**Comment by Hellowlol** [comment]
Please enable https://www.home-assistant.io/integrations/profiler/ and do what listed there to start monitor the memory usage. Depending on how fast the memory usage increases you can create a automation  that call the memory profiler every xx

**Comment by romlisrl** [comment]
I should apologize, looks like I was too hasty with my conclusions. 
After deactivation of all custom components, memory leak continued with the same pace. So from my point of view leak may be in HA instance it self. 
I will try to collect data by profiler and post it here if it interesting for you.
![image](https://user-images.githubusercontent.com/49437281/188797650-d80ca743-84eb-40fe-adc4-33f0d1283ff5.png)

**Comment by romlisrl** [comment]
I got profiler data, in case you are interested.
[callgrind.out.zip](https://github.com/custom-components/nordpool/files/9503734/callgrind.out.zip)

**Comment by mfalkvidd** [comment]
@romlisrl could you share the solution?

**Comment by romlisrl** [comment]
@mfalkvidd Sorry dear, I havn't solution yet, still continue investigation of memory leak reason.
Probably it's not connected with the component, cause after it deactivation memory usage grows in same pace.

**Comment by mfalkvidd** [comment]
Ok, thanks for explaining :-)

**Comment by romlisrl** [comment]
Downgraded to the 2022.6.7, so far it looks more stable in regards of memory usage.
