### ISSUE TITLE
precision does not work as expected

### ISSUE THREAD

**Issue by mct370770** [custom-components/nordpool#192]
I thought that I could set the precision to "2" to get a more easy readable cost.
But setting the precision value to 2 just gets me an "unvailable" for the data.

Do I misunderstand the meaning behind "precision"?

**Comment by vahem2lu** [comment]
Same problem here.

And sometimes the cost is rounded to 1 value after comma, sometimes is displayed with 2 or 3.

<img width="600" alt="Screenshot 2022-09-10 at 11 26 32" src="https://user-images.githubusercontent.com/15649157/189477457-90b6a845-ad08-4f81-adb8-e423c79fe3f2.png">

**Comment by Hellowlol** [comment]
This uses Python round function. Does any logs show errors? What can you take a screenshot of the State and attributes?

**Comment by mct370770** [comment]
If I change the number after “precision:” to anything other than 3 it becomes unavailable like shown in the attached screen shots. 

![4E5B077D-9D34-450F-8C20-C2B97A738944](https://user-images.githubusercontent.com/50733331/189518203-7729aabb-56a8-4c9a-8af8-900b06567c5f.jpeg)
![B03BB21B-D1EA-44A2-B6BF-95EFF9AF46B1](https://user-images.githubusercontent.com/50733331/189518205-1157db16-d65c-4dfb-8235-2dbe21c616aa.jpeg)
![1DBF4B05-D9BD-4116-AEFD-50DFD70345D0](https://user-images.githubusercontent.com/50733331/189518206-c0e38855-6772-47b4-8097-60e9795649bf.jpeg)
![C6100244-9FEE-4914-8795-0B985BCADA6B](https://user-images.githubusercontent.com/50733331/189518207-df898cc8-00af-4b27-b312-17c3666e5614.jpeg)
![D2295C81-760B-48E0-8F62-034C247A2188](https://user-images.githubusercontent.com/50733331/189518208-f651a787-d5e2-425b-8e56-51db0e1d3baf.jpeg)
![F684A3DE-1622-4FEF-A85D-BF0FD6AF2A80](https://user-images.githubusercontent.com/50733331/189518210-bd9edee3-494a-40f5-92a2-b516fb43a8e5.jpeg)

**Comment by vahem2lu** [comment]
I've found error.

When you edit configuration (including precision) your sensor will get a new name. So you will have to edit your dashboard etc accordingly.

Please check http://homeassistant.local:8123/config/entities URL to see your new sensor name.

**Comment by mfalkvidd** [comment]
Nice work @vahem2lu , thanks for sharing the solution.

**Comment by vahem2lu** [comment]
I will make new issue due to rounding errors.
https://github.com/custom-components/nordpool/issues/193
