### ISSUE TITLE
Precision does not round correctly

### ISSUE THREAD

**Issue by vahem2lu** [custom-components/nordpool#193]
A new issue from https://github.com/custom-components/nordpool/issues/192

Sometimes the cost is rounded to 1 value after comma, sometimes is displayed with 2 or 3.

<img width="600" alt="Screenshot 2022-09-10 at 11 26 32" src="https://user-images.githubusercontent.com/15649157/189477457-90b6a845-ad08-4f81-adb8-e423c79fe3f2.png">

Logs does not show any errors.

Raw data screenshots

<img width="564" alt="Screenshot 2022-09-12 at 09 59 23" src="https://user-images.githubusercontent.com/15649157/189592125-3a2f52b1-145c-40ee-bb57-c1b4b1d11426.png">

<img width="531" alt="Screenshot 2022-09-12 at 10 00 58" src="https://user-images.githubusercontent.com/15649157/189592202-7f4ba768-1816-4167-b0e2-01d5c0a31828.png">

Seems like data "current"/"off peak" etc is displayed in attributes already with precision 2, not 3 like stated in configuration.

**Comment by yksxjan** [comment]
I have the same issue. Worst even for me... Using EUR/kwh and in EE the prices this night were 0.0003 and 0.0001 from (1 to 5 local time). I have set precision to 4 and with "not so low prices" sensor works correctly. With such prices it becomes 0.0 and does not update afterwards from1 AM.
