### ISSUE TITLE
Nordpool integration stopped working

### ISSUE THREAD

**Issue by booyaga** [custom-components/nordpool#198]
![Screenshot_20221002-003835~2](https://user-images.githubusercontent.com/81765479/193431218-81bcdcb6-5d2b-4651-bc3e-c415a005f5a6.png)

**Comment by Enthalphy** [comment]
Same issue here

**Comment by Hellowlol** [comment]
Closing this issue as your failed to use the issue template. The sensor works here and you provided 0 helpfull information.
