### ISSUE TITLE
Tomorrow's daily price

### ISSUE THREAD

**Issue by dront242** [custom-components/nordpool#200]
Most customers in (at least) Sweden doesn't pay the hourly Nordpool price but instead the daily price that's set one day in advance. I haven't found a way to get this price into HA. I'm not an expert but I can't see it would be very difficult to implement that option?
Just an idea from me... :)

**Comment by Hellowlol** [comment]
What price is it? Who sets the price?

**Comment by dront242** [comment]
Nordpool sets the price and maybe it's just the average of all hourly prices during one day? On their webpage you can look at "Day ahead-prices" and chose "Daily" as time resolution. For example today the price in Swedish zone SE2 is €141.26 and tomorrow it will be €29.74.

https://www.nordpoolgroup.com/en/Market-data1/Dayahead/Area-Prices/ALL1/Hourly1/?view=table

**Comment by dront242** [comment]
I've had a closer look at it and yes, it's just the average value. So I'm closing this.
