### ISSUE TITLE
"Tomorrow valid = true" when no values are present (before 13:00)

### ISSUE THREAD

**Issue by bjornta** [custom-components/nordpool#209]
## Version of the custom_component
0.0.7

## Homeassistant version
2022.10.4

## Configuration

    - platform: nordpool
      VAT: True
      currency: "NOK"
      low_price_cutoff: 0.95
      region: "Oslo"
      precision: 3 
      price_type: kWh
      friendly_name: "Power price"

## Describe the bug
Attribute "Tomorrow valid" is set to true, but there are no values present. The time is 11am.

HA running in docker with the following parameter:
-v /etc/localtime:/etc/localtime:ro
also tried with the following parameter instead:
-e TZ=Europe/Oslo

Timezone on both host and container is set to Europe/Oslo.

Current price 2.01
Average 1.77
Off peak 1 1.43
Off peak 2 1.75
Peak 2.01
Min 0.94
Max 2.34
Unit kWh
Currency NOK
Country Norway
Region Oslo
Low price false
Tomorrow valid true
Today 1.605, 1.453, 1.005, 0.988, 0.935, 1.417, 1.896, 2.169, 2.344, 2.178, 2.175, 2.013, 1.725, 1.687, 1.69, 1.745, 1.877, 2.132, 2.237, 2.295, 1.997, 1.781, 1.671, 1.562
Tomorrow , , , , , , , , , , , , , , , , , , , , , , ,

**Comment by urpokarhu** [comment]
I notice this too

**Comment by DohmenICT** [comment]
Same here for region NL

**Comment by gitskotjuko** [comment]
Same for region FI

**Comment by Hellowlol** [comment]
@gitskotjuko @DohmenICT @urpokarhu is due to a restart before 1400? It not please create a new issue

**Comment by gitskotjuko** [comment]
> @gitskotjuko @DohmenICT @urpokarhu is due to a restart before 1400? It not please create a new issue

By me seems due to restart before 1400. Restarted today about 10:00 (+2) and having:
region: FI
tomorrow_valid: **true**
today: 3.295, 3.231, 2.848, 2.902, 2.603, 2.978, 3.261, 3.711, ...
tomorrow: 2.461, , , , , , , , , , , , , , , , , , , , , , , 
raw_tomorrow: 
- start: '2022-11-07T00:00:00+02:00'
  end: '2022-11-07T01:00:00+02:00'
  value: 2.461
- start: '2022-11-07T01:00:00+02:00'
  end: '2022-11-07T02:00:00+02:00'
  **value: null**

  end: '2022-11-07T03:00:00+02:00'
  **value: null**

**Comment by depen84** [comment]
Im experiencing it too.

current_price: 0.657
average: 0.529
off_peak_1: 0.278
off_peak_2: 0.463
peak: 0.73
min: 0.125
max: 0.837
unit: kWh
currency: SEK
country: Sweden
region: SE3
low price: false
tomorrow_valid: true
today: 0.208, 0.174, 0.125, 0.147, 0.174, 0.278, 0.495, 0.624, 0.679, 0.735, 0.767, 0.719, 0.678, 0.657, 0.706, 0.763, 0.816, 0.837, 0.679, 0.592, 0.522, 0.492, 0.435, 0.403
tomorrow: , , , , , , , , , , , , , , , , , , , , , , , 
raw_today: 
- start: '2022-11-07T00:00:00+01:00'
  end: '2022-11-07T01:00:00+01:00'
  value: 0.208
- start: '2022-11-07T01:00:00+01:00'
  end: '2022-11-07T02:00:00+01:00'
  value: 0.174
- start: '2022-11-07T02:00:00+01:00'
  end: '2022-11-07T03:00:00+01:00'
  value: 0.125
- start: '2022-11-07T03:00:00+01:00'
  end: '2022-11-07T04:00:00+01:00'
  value: 0.147
- start: '2022-11-07T04:00:00+01:00'
  end: '2022-11-07T05:00:00+01:00'
  value: 0.174
- start: '2022-11-07T05:00:00+01:00'
  end: '2022-11-07T06:00:00+01:00'
  value: 0.278
- start: '2022-11-07T06:00:00+01:00'
  end: '2022-11-07T07:00:00+01:00'
  value: 0.495
- start: '2022-11-07T07:00:00+01:00'
  end: '2022-11-07T08:00:00+01:00'
  value: 0.624
- start: '2022-11-07T08:00:00+01:00'
  end: '2022-11-07T09:00:00+01:00'
  value: 0.679
- start: '2022-11-07T09:00:00+01:00'
  end: '2022-11-07T10:00:00+01:00'
  value: 0.735
- start: '2022-11-07T10:00:00+01:00'
  end: '2022-11-07T11:00:00+01:00'
  value: 0.767
- start: '2022-11-07T11:00:00+01:00'
  end: '2022-11-07T12:00:00+01:00'
  value: 0.719
- start: '2022-11-07T12:00:00+01:00'
  end: '2022-11-07T13:00:00+01:00'
  value: 0.678
- start: '2022-11-07T13:00:00+01:00'
  end: '2022-11-07T14:00:00+01:00'
  value: 0.657
- start: '2022-11-07T14:00:00+01:00'
  end: '2022-11-07T15:00:00+01:00'
  value: 0.706
- start: '2022-11-07T15:00:00+01:00'
  end: '2022-11-07T16:00:00+01:00'
  value: 0.763
- start: '2022-11-07T16:00:00+01:00'
  end: '2022-11-07T17:00:00+01:00'
  value: 0.816
- start: '2022-11-07T17:00:00+01:00'
  end: '2022-11-07T18:00:00+01:00'
  value: 0.837
- start: '2022-11-07T18:00:00+01:00'
  end: '2022-11-07T19:00:00+01:00'
  value: 0.679
- start: '2022-11-07T19:00:00+01:00'
  end: '2022-11-07T20:00:00+01:00'
  value: 0.592
- start: '2022-11-07T20:00:00+01:00'
  end: '2022-11-07T21:00:00+01:00'
  value: 0.522
- start: '2022-11-07T21:00:00+01:00'
  end: '2022-11-07T22:00:00+01:00'
  value: 0.492
- start: '2022-11-07T22:00:00+01:00'
  end: '2022-11-07T23:00:00+01:00'
  value: 0.435
- start: '2022-11-07T23:00:00+01:00'
  end: '2022-11-08T00:00:00+01:00'
  value: 0.403

raw_tomorrow: 
- start: '2022-11-08T00:00:00+01:00'
  end: '2022-11-08T01:00:00+01:00'
  value: null
- start: '2022-11-08T01:00:00+01:00'
  end: '2022-11-08T02:00:00+01:00'
  value: null
- start: '2022-11-08T02:00:00+01:00'
  end: '2022-11-08T03:00:00+01:00'
  value: null
- start: '2022-11-08T03:00:00+01:00'
  end: '2022-11-08T04:00:00+01:00'
  value: null
- start: '2022-11-08T04:00:00+01:00'
  end: '2022-11-08T05:00:00+01:00'
  value: null
- start: '2022-11-08T05:00:00+01:00'
  end: '2022-11-08T06:00:00+01:00'
  value: null
- start: '2022-11-08T06:00:00+01:00'
  end: '2022-11-08T07:00:00+01:00'
  value: null
- start: '2022-11-08T07:00:00+01:00'
  end: '2022-11-08T08:00:00+01:00'
  value: null
- start: '2022-11-08T08:00:00+01:00'
  end: '2022-11-08T09:00:00+01:00'
  value: null
- start: '2022-11-08T09:00:00+01:00'
  end: '2022-11-08T10:00:00+01:00'
  value: null
- start: '2022-11-08T10:00:00+01:00'
  end: '2022-11-08T11:00:00+01:00'
  value: null
- start: '2022-11-08T11:00:00+01:00'
  end: '2022-11-08T12:00:00+01:00'
  value: null
- start: '2022-11-08T12:00:00+01:00'
  end: '2022-11-08T13:00:00+01:00'
  value: null
- start: '2022-11-08T13:00:00+01:00'
  end: '2022-11-08T14:00:00+01:00'
  value: null
- start: '2022-11-08T14:00:00+01:00'
  end: '2022-11-08T15:00:00+01:00'
  value: null
- start: '2022-11-08T15:00:00+01:00'
  end: '2022-11-08T16:00:00+01:00'
  value: null
- start: '2022-11-08T16:00:00+01:00'
  end: '2022-11-08T17:00:00+01:00'
  value: null
- start: '2022-11-08T17:00:00+01:00'
  end: '2022-11-08T18:00:00+01:00'
  value: null
- start: '2022-11-08T18:00:00+01:00'
  end: '2022-11-08T19:00:00+01:00'
  value: null
- start: '2022-11-08T19:00:00+01:00'
  end: '2022-11-08T20:00:00+01:00'
  value: null
- start: '2022-11-08T20:00:00+01:00'
  end: '2022-11-08T21:00:00+01:00'
  value: null
- start: '2022-11-08T21:00:00+01:00'
  end: '2022-11-08T22:00:00+01:00'
  value: null
- start: '2022-11-08T22:00:00+01:00'
  end: '2022-11-08T23:00:00+01:00'
  value: null
- start: '2022-11-08T23:00:00+01:00'
  end: '2022-11-09T00:00:00+01:00'
  value: null

unit_of_measurement: SEK/kWh
icon: mdi:flash
friendly_name: nordpool_kwh_se3_sek_3_10_025

**Comment by Hellowlol** [comment]
Thanks for the bug report, this should be fixed is the latest release.
