### ISSUE TITLE
Configurable VAT percent

### ISSUE THREAD

**Issue by jonnenauha** [custom-components/nordpool#210]
**Is your feature request related to a problem? Please describe.**

In the current state of Europe energy markets, many countries are temporarily decreasing VAT. This component does a nice job during normal times to include VAT out of the box. This is what you typical users really wants to see, what they will be paying in their bill.

I saw that some were requesting changes to the hardcoded VAT list. This is fine if the country permanently changes energy VAT but I don't think its a good solution for these temporary changes. You cant possible follow all of them and make releases to keep up with them accross Europe.

I'm from Finland that will drop VAT to 10% for 3 months I believe. I have made other prometheus/grafana tracking that look into future prices where I can change the VAT, they won then match this components exposed prometheus metrics in terms of VAT.

**Describe the solution you'd like**

Allow config value to define manual VAT, easy and simple for "non programmer" users. We should not force users to disable VAT and do their VAT computation elsewhere in the templates, this can be hard for novice users. And to be honest even for users that can do this, it can be a pain to maintain.

```yaml
    # Should the prices include vat? Default True
    VAT: True
    # Custom country VAT percent, overrides built in country VAT
    VAT_percent: 10
```

Change this in code (pseudo) in `sensor.py`

```python
        if vat is True and vat_percent > 0:
            self._vat = vat_percent / 100
        elif vat is True:
            self._vat = _REGIONS[area][2]
        else:
            self._vat = 0
```

You'd obviously want to check `vat_percent` is a number, not `None/undefined/null`.

---

I'm not that well versed in Python (its been years since I touched it) but if you want I can make a PR if you agree on the plan.

**Comment by Hellowlol** [comment]
Hi, 

I agree that having a hardcoded list is vat isn’t ideally these days. In the master branch you can use the current_price to calculate the vat yourself.
Eg:
current_price * 0.1

If your test and confirm that it’s working I’ll push a new version to hacs.

**Comment by jonnenauha** [comment]
Isn't the solution you are suggesting then setting VAT to zero and doing the computation outside of this HA component? 

As I tried to convey this is not great for novice users. And if you want to change the VAT you might end up modifying many places where that computation is done, instead of once at the source (this HA component). When you change it back you can forget to update of of the number of places where current_price is used.

Or did I understand something wrong? Do you have some global place where I have the change to modify the price before its exposed to HA as (in my case) `states.sensor.nordpool_kwh_fi_eur_4_095_024`?

**Comment by Hellowlol** [comment]
You have to use:
{{current_price * 0.1|float}}
in the additional costs field in the gui or yaml

**Comment by jonnenauha** [comment]
Yeah, I do get I can do it like this but its not intuitive to users to turn off VAT first then modify `additional_costs` which is meant for the margin per kWh. If you want this to be the only way to accomplish this then thats fine. Would be nice if this was documented in the readme "how to set custrom VAT and sale margin with additional_costs".

**Comment by Hellowlol** [comment]
It’s the best and only way to allow maxium flexabilty and reduce the burden for the developers. (We do this in our spare time..)

It isn’t documented as it isn’t in a release that hacs can use. Feel free to document and send a PR if you like. Or simply wait for a new update :)

**Comment by jeveli** [comment]
Easiest at the moment is to edit the sensor.py from 0.24 to 0.10
and you get a new entity ( sensor.nordpool_kwh_fi_eur_3_10_01 ) that we can use, not ideal but it's working

![image](https://user-images.githubusercontent.com/7755806/202525371-7a48763b-51cb-4143-ba11-a2376b51fafa.png)
![image](https://user-images.githubusercontent.com/7755806/202526290-19db68a2-69da-4257-aacc-ff6c735d8e58.png)
