### ISSUE TITLE
Nordpool keeps changing name of sensor

### ISSUE THREAD

**Issue by cmd85** [custom-components/nordpool#211]
Hi, I am having the issue that Nordpool sensor changes names very often at reboots and it breaks automations.

As this morning I had [sensor.nordpool_kwh_se3_sek_3_06_025].
Now the active one is [sensor.nordpool_kwh_se3_sek_3_09_025]

I havent been able to understand why or how to fix this, any ideas here?

**Comment by clas72** [comment]
I encountered the same problem today.

Sensors were renamed from: nordpool_kwh_se3_sek_2_095_025
to:
nordpool_kwh_se3_sek_3_095_025
Why is this ? 
Really annoying !

**Comment by Hellowlol** [comment]
Hi!

The entity is generated based on settings of the sensor. If you change settings, the unique id will change and break your automation. 

See how this is generated:
https://github.com/custom-components/nordpool/blob/master/custom_components/nordpool/sensor.py#L217-L227

In hindsight, i should have generated this in another way, but it is what it is.  Moral of the story is, if you change your settings you need to update your automation.

**Comment by clas72** [comment]
Aha, I changed the precision from 3 to 2, that explains it then :) 
Thanks for the update.

**Comment by cmd85** [comment]
Yep that explains it, thx :)
