### ISSUE TITLE
Default precision 

### ISSUE THREAD

**Issue by motionthings** [custom-components/nordpool#212]
I would like the default precision to be 2 decimals since that is what the energy dashboard uses.

![image](https://user-images.githubusercontent.com/264911/199917704-01b5e19f-b222-46ea-b34e-aaf60d3ecf13.png)

If you want 3 decimal precision, then you can edit the yaml.
I just want to set it up in the GUI without editing the yaml.

**Comment by Hellowlol** [comment]
You can set it up both in the gui and the yaml with the precision you want.  I'm not gonna change the default value.
