### ISSUE TITLE
Additional costs template not working as expected configuring from GUI

### ISSUE THREAD

**Issue by renslinden** [custom-components/nordpool#213]
## Version of the custom_component
0.0.7

## Homeassistant version
2022.11.1

## Configuration

N/A, configuring through the GUI.

## Describe the bug

I'm trying to add the VAT manually since it is temporarily decreased to 9% in the Netherlands.

But I'm not able to create the sensor with the current_price attribute.

This don't work:
```yaml
{{current_price * 0.09}}
```

Resulting in this error
```text
The template is invalid, check https://github.com/custom-components/nordpool
```

While this is working (adding 10 cents)

```yaml
{{0.10}}
```

So it seems related with the **current_price** attribute.

## Debug log

N/A

**Comment by Andholmvej** [comment]
Hi. 
Nice you got that running.
I would like to know how to add different teansfer price at different times, something like 0.6 kr ekstra between 17 and 20 in the wintermonth.
Hope someone can help.

**Comment by Hellowlol** [comment]
Current price is not in a release yet

**Comment by renslinden** [comment]
> Current price is not in a release yet

Can you elaborate please? I'm totally confused now. [Here](https://github.com/custom-components/nordpool/issues/210#issuecomment-1296243461) you referring to this...

**Comment by Hellowlol** [comment]
I also wrote that this functionality isn’t released yet… AKA it’s not in 0.0.7 or any other release. You will need run it from the master branch by manually download and install it.

**Comment by Andholmvej** [comment]
I would like to have something like this working, we have a flexible power price and different tranfer price in Danmark so it could be nice to se a littel in adwance with these power price

![Screenshot_20221106_134428_Chrome](https://user-images.githubusercontent.com/110162473/200171635-121bf303-79da-41ce-9da3-7d8a15ae8a43.jpg)

**Comment by renslinden** [comment]
> I also wrote that this functionality isn’t released yet… AKA it’s not in 0.0.7 or any other release. You will need run it from the master branch by manually download and install it.

That make sense, thanks for explanation! Are there any plans for a new release?

**Comment by Heronimonimo** [comment]
> I also wrote that this functionality isn’t released yet… AKA it’s not in 0.0.7 or any other release. You will need run it from the master branch by manually download and install it.

Thanks for letting us know. Would love to see a release including this!

**Comment by Hellowlol** [comment]
@Andholmvej template is have been supported for a long time. It’s only the special_variable current_price that isn’t.

**Comment by Hellowlol** [comment]
New release is out. Closing :)
