### ISSUE TITLE
Showing wrong values

### ISSUE THREAD

**Issue by Mpgod80** [custom-components/nordpool#215]
I am using Nordpool for showing prices in sweden electrical area 2.

But from 07:00am today it is showing to high value of 1,167 SEK instead of 0,93 SEK as it shows on the website https://elen.nu/dagens-spotpris/se2-sundsvall/

Runing the latest version.
And the latest of HA core and everything else.

## Version of the custom_component
0.0.7

## Homeassistant version
2022.11.2
Supervisor 2022.10.2
Operating System 9.3

## Configuration

```yaml

Add your configuration here.

```

## Debug log

```text

Add your logs here.

```

**Comment by Hellowlol** [comment]
Closing, there is nothing for me to do here. No log, no bug description.  I just released 0.0.8. Try that one and create a new issue using all the field in the issue template. It's there for a reason.
