### ISSUE TITLE
Tomorrow_valid True when it should be False

### ISSUE THREAD

**Issue by uphillbattle** [custom-components/nordpool#218]
## Version of the custom_component
0.0.8

## Homeassistant version
2022.11.2

## Configuration
By the UI

## Describe the bug
`tomorrow_valid` is True when there are no values in `tomorrow` (at 8:30 in the morning)
![image](https://user-images.githubusercontent.com/15340540/201290133-edbc6069-2d44-43ab-b05c-5f357d597fcf.png)

**Comment by yksxjan** [comment]
<img width="250" alt="image" src="https://user-images.githubusercontent.com/10712418/201317198-9e9f97f5-e76b-4c5a-99c3-2ad4448c4278.png">

**Comment by Hellowlol** [comment]
Thanks!

**Comment by Hellowlol** [comment]
Should be fixed in 0.0.9. Reopen this issue if its still a issue
