### ISSUE TITLE
Monthly average price attribute

### ISSUE THREAD

**Issue by grotteru** [custom-components/nordpool#221]
It would be nice to have the monthly average price as an attribute to the sensor.

During the current high price situation every individual consumer in Norway gets a reduction in the tariff based on the monthly average power price for their respective area. It would thus be nice to have this price calculated from the source.

I have made an AppDaemon app that utilizes the nordpool package to get the average power price for the current month. If I find time maybe I will try to integrate it in this component myself. 

Nevertheless, I think it would be a nice improvement.

**Comment by yozik04** [comment]
You can do it yourself: https://www.home-assistant.io/integrations/statistics/

**Comment by Hellowlol** [comment]
This feature will not be added. It’s simple to add directly in home assistant. All features like this just adds dents that need to be maintained.
