### ISSUE TITLE
Nord Pool prices

### ISSUE THREAD

**Issue by IngoAlta** [custom-components/nordpool#222]
I have installed the Nordpool integration. But I think I have set it up incorrectly. My electric company charges me on an hourly basis and uses the Nord Pool day ahead prices for Sweden SE3. These prices are published on their home page under Day-ahead prices both in SEK and EUR. I use SEK but it looks like the Nordpool integration givs me different prices. Being new to this I wonder what I have done wrong. Would by really thankful if someone could help me. This is my set up in configuration.yaml:

nordpool:

sensor:
  - platform: nordpool
    VAT: True
    currency: "SEK"
    price_in_cents: True
    low_price_cutoff: 0.00
    region: "SE3"
    precision: 3
    price_type: kWh
    additional_costs: "{{0.0|float}}"

Have I missed something or done something wrong? I get prices but not the one I was looking for. This is what the sensor returns:
Current price
39,67
Average
36,06
Off peak 1
26,66
Off peak 2
31,51
Peak
43,85
Min
23,07
Max
67,37
Unit
kWh
Currency
SEK
Country
Sweden
Region
SE3
Low price
false
Price percent to average
1,1
Today
25.533, 24.102, 23.212, 23.065, 23.321, 24.872, 30.524, 38.644, 46.17, 38.994, 42.164, 44.132, 39.736, 38.064, 39.884, 39.669, 42.339, 67.373, 53.992, 33.666, 34.328, 32.763, 31.805, 27.125
Tomorrow
49.407, 32.495, 23.053, 19.915, 19.996, 23.964, 57.409, 83.422, 116.637, 98.19, 82.269, 80.706, 77.868, 78.261, 78.709, 84.035, 87.036, 101.586, 82.269, 67.706, 60.071, 51.119, 54.203, 43.525
Tomorrow valid
true
Raw today
- start: '2022-11-16T00:00:00+01:00'
end: '2022-11-16T01:00:00+01:00'
value: 25.533
- start: '2022-11-16T01:00:00+01:00'
end: '2022-11-16T02:00:00+01:00'
value: 24.102
- start: '2022-11-16T02:00:00+01:00'
end: '2022-11-16T03:00:00+01:00'
value: 23.212
and like that until

Raw tomorrow
- start: '2022-11-17T00:00:00+01:00'
end: '2022-11-17T01:00:00+01:00'
value: 49.407
- start: '2022-11-17T01:00:00+01:00'
end: '2022-11-17T02:00:00+01:00'
value: 32.495
and like that until

Additional costs current hour
0
The Noth Pool home page givs the following information for November 15th in SEK/MWh to be compared with the integrations price in öre/kWh

00 - 01 | 299,28
01 - 02 | 271,97
02 - 03 | 232,31
03 - 04 | 203,82
04 - 05 | 217,26
05 - 06 | 255,42
06 - 07 | 293,37
07 - 08 | 769,70
08 - 09 | 955,89
09 - 10 | 1 023,08
10 - 11 | 1 074,03
11 - 12 | 1 022,32
12 - 13 | 961,48
13 - 14 | 902,68
14 - 15 | 890,31
15 - 16 | 750,89
16 - 17 | 603,72
17 - 18 | 859,78
18 - 19 | 466,98
19 - 20 | 299,28
20 - 21 | 251,76
21 - 22 | 202,42
22 - 23 | 191,78
23 - 00 | 167,81

Thankful if some could hint on the problem.

**Comment by Hellowlol** [comment]
I dont see the problem. The prices seems correct. The only difference is they one in mw and the other are in øre/kWh (Also includes vat)

**Comment by Hellowlol** [comment]
Closing this issue. If you still think it’s a issue please provide logs and reopen the issue 👍

**Comment by IngoAlta** [comment]
Thanks a lot! Feels like an idiot. You are right and all works fine! Missed the vat part.

**Comment by Hellowlol** [comment]
No worries, it happens all the time.
