### ISSUE TITLE
10% VAT instead of 24% in Finland after 1 December until 30 April

### ISSUE THREAD

**Issue by jeveli** [custom-components/nordpool#224]
Can this be manually changed? It would be great if this could easily be changed, I guess other countries will go this route as well.

**Comment by jeveli** [comment]
Easiest at the moment is to edit the sensor.py from 0.24 to 0.10
and you get a new entity ( sensor.nordpool_kwh_fi_eur_3_10_01 ) that we can use, not ideal but it's working

![image](https://user-images.githubusercontent.com/7755806/202529422-a518ca7f-2c76-4f5e-b8a4-804a43d0c37a.png)
![image](https://user-images.githubusercontent.com/7755806/202529450-c07ab301-1771-4171-9697-2cd13a3fc221.png)

**Comment by Hellowlol** [comment]
Disable vat and use the additional cost template. See the example in the readme
