### ISSUE TITLE
Price in EUR/MWh becomes in kWh

### ISSUE THREAD

**Issue by i5rast** [custom-components/nordpool#225]
Hi,

Great integration, using it continously in terribly pricy SE4!

I noticed that in versions 0.08 and 0.09, the price in EUR/MWh becomes incorrectly 1000 times smaller than it should be.  A real price of e.g. EUR 50/MWh is presented as EUR 0.05/MWh, i.e. effectively in EUR/kWh.

Thanks

**Comment by Hellowlol** [comment]
Duplicate https://github.com/custom-components/nordpool/issues/219
