### ISSUE TITLE
data_generator makes different price in graph than entity_id

### ISSUE THREAD

**Issue by Thomsen-79** [custom-components/nordpool#227]
the price in top is right but the graph is wrong
https://pastebin.com/rw3EQhgi
![Skærmbillede (143)](https://user-images.githubusercontent.com/61097896/202851059-d17308f0-4b03-4e06-8289-a1efe37a073c.png)

**Comment by Hellowlol** [comment]
… hard to fill out a issue template?

**Comment by Thomsen-79** [comment]
Sorry, but doent know what you mean by that

**Comment by Hellowlol** [comment]
You need to use the issue template. You failed to do so and you are refer to a thirdparty app. There are 0 usefull information to help me debug this issue.

**Comment by Thomsen-79** [comment]
Ok, Im sorry. First time to make a issue. 
Was just wundering why it make the difference in Numbers and graph and believed it to be nordpool integration. It worked fine few days ago. My bad

**Comment by Hellowlol** [comment]
My apologies for biting your head off, that was never my intention. :)

It's just that I sometimes get frustrated when users are opening an issue and provide no useful information so I can actually help them.

If you want assistance I need information that I can use to replicate your problem or to help me debug it:
- What nordpool version your using? 
- what ha version?
- copy and paste the code you used to create the chart? 
- copy paste the sensor from your dev tools?
- debug log

See the read for how to enable to log if you don't know how to :)

**Comment by Thomsen-79** [comment]
No worries mate 😉 for some reason it show the right graph and Numbers again. Maybe its nordpool or maybe just my HA. But thanks for getting back to me.. I will try to do it right next time if I need it👍🏼 use the integration every day. So thanks😊
