### ISSUE TITLE
Using another sensor as value in additional_costs not updating

### ISSUE THREAD

**Issue by cvjensen** [custom-components/nordpool#230]
I've been playing a little with the sum_tariff sensor and additional costs in nordpool.

Instead of manually calculating them I want to use [this](https://github.com/JonasPed/homeassistant-eloverblik) to go and grap the current tariffs so I dont have to manually keep them up to date.

But it just seems like nordpool loads up the float 0 default before the eloverblik_tariff_sum have any value and then nordpool never updates. Any way I can fix that ?

## Version of the custom_component
newest

## Homeassistant version
newest

## Configuration

```
additional_costs: >-
  {{ states('sensor.eloverblik_tariff_sum') | float(0) * 1.25  }}
```

**Comment by Hellowlol** [comment]
Hi

I’m not familiar with that integration. What default value? Please enable debug log and restart the server. Let it run for 10 minutes and paste the log here

**Comment by cvjensen** [comment]
Hi @Hellowlol 

The default value of the float conversion ? 
I'm guessing the "(0)" in "float(0)" means that if no value is received then use the default which in this case is 0.

I've just tried to enable logging as described in the readme of this repo and then....

Then I wrote alot of stuff and just when I would go and grap the logs for you it had updated. Now the additional costs are included .

I then restarted again just to be sure. But I dont seem to be as lucky this time... 

Conf:
```
  additional_costs: >-
    {{ (states('sensor.eloverblik_tariff_sum') | float(0)) * 1.25 }}
```

Test of template:
![image](https://user-images.githubusercontent.com/9024493/203501944-3acc9517-0925-4145-beb0-9619f66443d0.png)

Nordpool not adding any tariffs
![image](https://user-images.githubusercontent.com/9024493/203502093-0a951c4e-a233-43d8-bf70-c883caf3f9e0.png)

Logs:
![image](https://user-images.githubusercontent.com/9024493/203502259-61b337be-4afc-4ad4-bbbc-866051291a07.png)

I will let it run for some time to see if its just slow to update .

**Comment by Hellowlol** [comment]
Ok, perfect. Maybe it gets issues if nordpool is loaded before eloverblik_tariff_sum. 
If nordpool is setup by yaml, can you remove that and  restart the server. Check that eloverblik_tariff_sum has a value, then add nordpool sensor using the gui with the same template that you are using now.

If that dont work, try hitting reload sensor and paste the debug log.

**Comment by cvjensen** [comment]
It seems like the additional costs got added at the next hour change ...

![image](https://user-images.githubusercontent.com/9024493/203552886-324252f3-00c0-4a35-9d61-d9c57f32fec4.png)

Probably because eloverblik_tariff_sum changed its value and nordpool are listening for changes .

I guess I can live with that. The worst it can be is 59minutes without additional costs .
As long as it fixes itself .

**Comment by Hellowlol** [comment]
Im pretty confident that the issue is just related to timing. Ill see if i can install the same package and check for my self

**Comment by cvjensen** [comment]
Sounds good . Thanks for your time , keep me updated if you try it out yourself 😄
