### ISSUE TITLE
additional_costs max doesn't update

### ISSUE THREAD

**Issue by PeterAndreS** [custom-components/nordpool#232]
Nordpool: 009

## Homeassistant version
Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

## Configuration
Nordpool:

sensor:
  # Nordpool sensor electricity prices
  - platform: nordpool

    # Should the prices include vat? Default True
    VAT: True

    # What currency the api fetches the prices in
    # this is only need if you want a sensor in a non local currency
    currency: "DKK"

    # Option to show prices in cents (or the equivalent in local currency)
    price_in_cents: True

    # Helper so you can set your "low" price
    # low_price = hour_price < average * low_price_cutoff
    low_price_cutoff: 0.00

    # What power regions your are interested in.
    # Possible values: "DK1", "DK2", "FI", "LT", "LV", "Oslo", "Kr.sand", "Bergen", "Molde", "Tr.heim", "Tromsø", "SE1", "SE2", "SE3","SE4", "SYS", "EE"
    region: "DK2"

    # How many decimals to use in the display of the price
    precision: 0

    # What the price should be displayed in default
    # Possible values: MWh, kWh and Wh
    # default: kWh
    price_type: kWh

    # This option allows the usage of a template to add a tariff.
    # now() always refers start of the hour of that price.
    # this way we can calculate the correct costs add that to graphs etc.
    # The price result of the additional_costs template expects this additional cost to be in kWh and not cents as a float
    # default {{0.0|float}}
    additional_costs: "
      {% if now().year == 2022 %}
        {% if now().hour >=17 and now().hour <20 %}
          {{0.9856|float}}
        {% else %}
          {{0.3785|float}}
        {% endif %}
      {% else %}
        {% if now().month >=10 or now().month <=3 %}
          {% if now().hour >=18 and now().hour <22 %}
            {{1.8336|float}}
          {% else %}
            {% if now().hour >=0 and now().hour <7 %}
              {{0.2038|float}}
            {% else %}
              {{0.6113|float}}
            {% endif %}
          {% endif %}
        {% else %}
          {% if now().hour >=18 and now().hour <22 %}
            {{0.7945|float}}
          {% else %}
            {% if now().hour >=0 and now().hour <7 %}
              {{0.2038|float}}
            {% else %}
              {{0.3057|float}}
            {% endif %}
          {% endif %}
        {% endif %}
      {% endif %}"
```yaml

```

## Describe the bug
[sensor.nordpool_kwh_dk2_dkk] max value not updated with additional_costs: 
Example: <<
current_price: 469
average: 403
off_peak_1: 326
off_peak_2: 376
peak: 464
min: 287
max: 488
unit: kWh
currency: DKK
country: Denmark
region: DK2
low_price: false
price_percent_to_average: 1.163771712158809
today: 304, 302, 296, 287, 291, 301, 366, 457, 469, 467, 459, 453, 445, 453, 469, 468, 464, 549, 535, 524, 438, 391, 354, 321
tomorrow: 
tomorrow_valid: false
raw_today: 
- start: '2022-12-01T00:00:00+01:00'
  end: '2022-12-01T01:00:00+01:00'
  value: 304
- start: '2022-12-01T01:00:00+01:00'
  end: '2022-12-01T02:00:00+01:00'
  value: 302
- start: '2022-12-01T02:00:00+01:00'
  end: '2022-12-01T03:00:00+01:00'
  value: 296
- start: '2022-12-01T03:00:00+01:00'
  end: '2022-12-01T04:00:00+01:00'
  value: 287
- start: '2022-12-01T04:00:00+01:00'
  end: '2022-12-01T05:00:00+01:00'
  value: 291
- start: '2022-12-01T05:00:00+01:00'
  end: '2022-12-01T06:00:00+01:00'
  value: 301
- start: '2022-12-01T06:00:00+01:00'
  end: '2022-12-01T07:00:00+01:00'
  value: 366
- start: '2022-12-01T07:00:00+01:00'
  end: '2022-12-01T08:00:00+01:00'
  value: 457
- start: '2022-12-01T08:00:00+01:00'
  end: '2022-12-01T09:00:00+01:00'
  value: 469
- start: '2022-12-01T09:00:00+01:00'
  end: '2022-12-01T10:00:00+01:00'
  value: 467
- start: '2022-12-01T10:00:00+01:00'
  end: '2022-12-01T11:00:00+01:00'
  value: 459
- start: '2022-12-01T11:00:00+01:00'
  end: '2022-12-01T12:00:00+01:00'
  value: 453
- start: '2022-12-01T12:00:00+01:00'
  end: '2022-12-01T13:00:00+01:00'
  value: 445
- start: '2022-12-01T13:00:00+01:00'
  end: '2022-12-01T14:00:00+01:00'
  value: 453
- start: '2022-12-01T14:00:00+01:00'
  end: '2022-12-01T15:00:00+01:00'
  value: 469
- start: '2022-12-01T15:00:00+01:00'
  end: '2022-12-01T16:00:00+01:00'
  value: 468
- start: '2022-12-01T16:00:00+01:00'
  end: '2022-12-01T17:00:00+01:00'
  value: 464
- start: '2022-12-01T17:00:00+01:00'
  end: '2022-12-01T18:00:00+01:00'
  value: 549
- start: '2022-12-01T18:00:00+01:00'
  end: '2022-12-01T19:00:00+01:00'
  value: 535
- start: '2022-12-01T19:00:00+01:00'
  end: '2022-12-01T20:00:00+01:00'
  value: 524
- start: '2022-12-01T20:00:00+01:00'
  end: '2022-12-01T21:00:00+01:00'
  value: 438
- start: '2022-12-01T21:00:00+01:00'
  end: '2022-12-01T22:00:00+01:00'
  value: 391
- start: '2022-12-01T22:00:00+01:00'
  end: '2022-12-01T23:00:00+01:00'
  value: 354
- start: '2022-12-01T23:00:00+01:00'
  end: '2022-12-02T00:00:00+01:00'
  value: 321

raw_tomorrow: 
additional_costs_current_hour: 0.3785
unit_of_measurement: Øre/kWh
icon: mdi:flash
friendly_name: sensor.nordpool_kwh_dk2_dkk
>>

**Comment by Hellowlol** [comment]
Thanks for the report. Im not sure what the real problem is. Is the problem that additional cost is not added to the max value? This should be a static value and not change more then once per day.

**Comment by PeterAndreS** [comment]
<h4><strong><span>Additional cost is a</span>dded but value is from wrong period.</strong></h4>
<p>The max value without extra expenses is 450, so it seems that extra expenses for (off-peak period) are used and not (peak period).<br />450 + 37,85 = 487,85.</p>
<p>A more simple approach would simply be to find the peak-value after sensor.today is found <img src="https://htmlg.com/tinymce4911/plugins/emoticons/img/smiley-wink.gif" alt="wink" />.</p>
<h5><strong>From sensor:</strong></h5>
<table border="1" style="border-collapse: collapse; width: 100%; height: 92px;">
<tbody>
<tr style="height: 21px;">
<td style="width: 6.11354%; height: 21px;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">today:</span></td>
<td style="width: 93.8865%; height: 21px;"><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">304, 302, 296, 287, 291, 301, 366, 457, 469, 467, 459, 453, 445, 453, 469, 468, 464,&nbsp;</span><span style="text-decoration: underline;">549</span><span style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">, 535, 524, 438, 391, 354, 321</span></td>
</tr>
<tr style="height: 71px;">
<td style="width: 6.11354%; height: 71px;"><span>raw_today: (Max)</span></td>
<td style="width: 93.8865%; height: 71px;">
<ul dir="auto" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">
<li>start: '2022-12-01T17:00:00+01:00'<br />end: '2022-12-01T18:00:00+01:00'<br />value: 549</li>
</ul>
</td>
</tr>
</tbody>
</table>
<p><span>&nbsp;</span><span><strong>additional costs:</strong>&nbsp;</span></p>
<table class="table table-striped table-bordered" border="0" width="394" height="120" style="width: 458px; height: 127px;">
<tbody>
<tr style="height: 37px;">
<td style="width: 208.375px; height: 37px;">&nbsp;</td>
<td style="width: 130.719px; height: 37px;"><strong>Lavlast</strong></td>
<td style="width: 117.906px; height: 37px;"><strong>Spidslast</strong></td>
</tr>
<tr style="height: 46px;">
<td style="width: 208.375px; height: 46px;">Nettarif ekskl. moms</td>
<td style="width: 130.719px; height: 46px;">30,28</td>
<td style="width: 117.906px; height: 46px;">78,85</td>
</tr>
<tr style="height: 44px;">
<td style="width: 208.375px; height: 44px;">Nettarif inkl. moms</td>
<td style="width: 130.719px; height: 44px;">37,85</td>
<td style="width: 117.906px; height: 44px;">98,56</td>
</tr>
</tbody>
</table>
<h5><span><strong>additional costs (periods):</strong>&nbsp;</span></h5>
<table border="1" style="height: 82px; width: 73.3624%; border-collapse: collapse; background-color: #fbfbfb;">
<tbody>
<tr style="height: 51px;">
<td style="width: 22.6282%; height: 51px;"><span style="font-weight: bold; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">Lav:</span></td>
<td style="width: 50.7342%; height: 51px;">
<ul style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">
<li>alle dage i perioden april &ndash; september</li>
<li>alle dage i perioden oktober &ndash; marts i tidsrummet 20.00 &ndash; 17.00.</li>
</ul>
</td>
</tr>
<tr style="height: 31px;">
<td style="width: 22.6282%; height: 31px;"><span style="font-weight: bold; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">Spids:</span></td>
<td style="width: 50.7342%; height: 31px;">
<ul style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">
<li>alle dage i perioden oktober &ndash; marts i tidsrummet 17.00 &ndash; 20.00.</li>
</ul>
</td>
</tr>
</tbody>
</table>
<p></p>

**Comment by Hellowlol** [comment]
Yeah, just grabbing the Max value for today prices would be the best approach. Max is currently what ever nordpool recons is the highest price without any regard for tariffs.
