### ISSUE TITLE
Low price cutoff based on median

### ISSUE THREAD

**Issue by jhj1974** [custom-components/nordpool#239]
As averaging is vulnerable to extreme values in the collection, an option to base the low price cutoff on the median value would be appreciated.

For example if one specific hour during a day has an extremely low price, the average will be low and the current price might only reach below this treshold for a limited time triggering a "low price" condition. By leveraging the median it will be easier to track the twelve cheapest hours during a day.

Further, maybe one should consider calculating the average and/or median based a contious sliding collection of the upcoming "n" number of hours? This to help decide if the current hour is cheap or not compared to what will be available in the close future. Consumption of energy is a continous process and not an independent event each day, hence a "resetting" the calculation just because the calendar flips to a new day might not be optimal.

Any toughts?

**Comment by Hellowlol** [comment]
Please checkout https://github.com/jpulakka/nordpool_diff

**Comment by Hellowlol** [comment]
median has been added.
