### ISSUE TITLE
When are prices for tomorrow valid?

### ISSUE THREAD

**Issue by matlimatli** [custom-components/nordpool#24]
At least in the morning, it seems like the price data for "tomorrow" is only a copy of the values for today. I suppose Nordpool does not make the data for the next day available until some time around noon or so. Is there any way of knowing if the tomorrow-values are valid? A simple boolean for this would be nice.

**Comment by Hellowlol** [comment]
The prices for tomorrow isnt updated before 1300-1305 Stockholm time.

**Comment by matlimatli** [comment]
Ok. Would it be possible to add a flag to indicat if the array of tomorrow-values are valid?
(I'm doing a graph widget for HADashboard, which would benefit from knowing if it is relevant to plot the values for tomorrow or not. The current workaround is to compare the arrays, and only plot today if they are identical.)

**Comment by Hellowlol** [comment]
I havnt looked into its but a simple solution would be to just check the current time and return true if the clock is more the 1300

**Comment by Hellowlol** [comment]
Make a PR or open a feature request and I’ll get to it sometime :)

**Comment by matlimatli** [comment]
Ok, I might have a look at the code and submit a PR. It seems like it would be possible :)
