### ISSUE TITLE
Negative prices returns "0"

### ISSUE THREAD

**Issue by GKHerping** [custom-components/nordpool#242]
Version of custom_component: latest as of 30/12-2022
Home Assistant version: 2022.12.8

If prices are negative nordpool returns 0,000 and not the negative prices (see example screenshot from [Nordpool website](https://www.nordpoolgroup.com/en/Market-data1/Dayahead/Area-Prices/DK/Hourly/?view=table))

Configuration:
```
- platform: nordpool
  VAT: False
  region: "DK1"
  precision: 3
  price_type: kWh
```
From Home Assistant:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/22987583/210095521-3a036655-24c0-4be8-950d-5c4ae301d20c.png">

Nordpool data:
<img width="149" alt="image" src="https://user-images.githubusercontent.com/22987583/210095075-8c95084d-d217-4e80-b715-383f98a631e0.png">

**Comment by GKHerping** [comment]
Disregard. I just realised that the price is in MWh and calculated to kWh will be i.e.:

03-04: -0,30 DKK/MWh = 0,0003 DKK/kWh

hence, the price will be 0 per the precision of 3

**Comment by Hellowlol** [comment]
I will remove the precision in a future update

**Comment by GKHerping** [comment]
Please don't. I like being able to control it - or at least have 3 decimal available
