### ISSUE TITLE
Statistics not enabled

### ISSUE THREAD

**Issue by babelfishen** [custom-components/nordpool#243]
**Is your feature request related to a problem? Please describe.**
Tried to add a graph for the kwh price over time but the data source are not listed.
Home assistant refers to this url that describes the issue and how to solve it:
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Describe the solution you'd like**
Would like the long term statistics to be enabled by default.
Preferrable, if possible, that not only the past price can be displayed but also the future price in a graph.

**Comment by Hellowlol** [comment]
Its should be available in the lastest pre-release 0.0.10b0. Please test and verify
