### ISSUE TITLE
Invalid version format in manifest.json prevents the integration from loading

### ISSUE THREAD

**Issue by troed** [custom-components/nordpool#246]
See https://github.com/custom-components/nordpool/commit/7743728569c1130219c760d9392cc3eaed5f122f#r94679030 for a comment directly at the affected line.

**Comment by Hellowlol** [comment]
Yeah :( I saw it after wards but I didn't have time to fix it. I'll get out a new version shortly.

**Comment by Hellowlol** [comment]
New version is out, I have installed in thru hacs on my prod HA instance.
