### ISSUE TITLE
Fixed (time-based) Additional Costs

### ISSUE THREAD

**Issue by rj-agara** [custom-components/nordpool#249]
Hello,

First of all, thank you for this great integration.

Feature request - Fixed (time-based) Additional Costs.
In contracts with energy suppliers, there often is a fee that is not connected to the amount of kWh used.
You pay this fee based on time, not kWh used. For example, every month you pay an electrical subscription fee (Swedish: Elnätsabonnemang månadsavgift) and you pay a contract fee (Swedish: Elavtal årsavgift). You have to pay these even if you use 0 (zero) kWh.

Fees connected to kWh usage are already handled with the current Additional Costs function. But for clarity, perhaps rename it to "Additional Costs based on consumption (kWh)" or "Additional Costs, relative".
This new fixed fee request could perhaps be called "Additional Costs based on time-period" or "Additional Costs, fixed"

As the Nordpool data is broken down into hourly "chunks", it would likely be recommended to instruct users to state the fixed fees per hour, not month or year.
For example, a yearly fee of 500 SEK would become 0.05707 SEK/hour (365 days * 24 hours = 8760 hour/year)(ignoring the extra day of leap years) 

Regarding the Nordpool setting of showing "cents". Perhaps easiest to just instruct the user to enter Additional Costs (both relative and fixed) using SEK/DKK/NOK/EUR and not using cent/öre. I don't know how this is handled today. But do the same for both relative and fixed additional costs.

As the Additional Costs is an attribute that can be shown today, this new fixed cost should also be visible as its own attribute. For example, so you can create a graph that stacks spot price, relative additional costs and fixed additional costs. Making it visible how much you pay to what.

**Comment by Hellowlol** [comment]
Hi, 

Thanks for the kind words!

 As for your request I don’t know if it makes sense to add a fixed price template as there is no relation between the fixed price and the energy cost. The user can just as easily create a template sensors to do this job.

I will not change the name of the additional_costs but some additional information in the readme and in the tooltip is a good idea. I’m happy to merged such a PR

**Comment by rj-agara** [comment]
Ok, fair enough. I just thought it would be nice to have all electricity cost in one place. Both dynamic and fixed.

Perhaps you could consider writing a how-to regarding setting up such a template sensor, here on your github?
I'll figure it out. But it is slightly more advances topic. Perhaps not everyone knows how.
But up to you. I can understand if you don't think it makes sense.

Keep up the great work.
