### ISSUE TITLE
Update integration description

### ISSUE THREAD

**Issue by AJediIAm** [custom-components/nordpool#256]
**Is your feature request related to a problem? Please describe.**
When browsing or searching HACS, this integration does not pop up unless you known what your looking for. Even reading the description will tell the user what this integration does. 

**Describe the solution you'd like**
Update the description ("about") of the github project 
from "nordpool sensor for ha."
to "Nordpool integration for hourly energy prices (spot market) for north and west European countries." 

**Describe alternatives you've considered**
Add appropriate tags such as "Energy". According to HACS documentation, the github tags are used for searching. 

**Additional context**
Did you know this integration is the 5th most starred custom-component?

![image](https://user-images.githubusercontent.com/5879533/210184151-00fbb764-aed1-411d-852e-91dd2b2f9fa8.png)
![Capture](https://user-images.githubusercontent.com/5879533/210184129-ffc69be6-8b92-4648-9735-06a54faf6584.PNG)

**Comment by Hellowlol** [comment]
No I didn’t know that. This project gotten way more attention than I imagined. This component was organically created to 1 user, my father-in-law.

I’ll update the description and add additional tags. 

Thanks!

**Comment by Hellowlol** [comment]
Fixed in a upcoming release
