### ISSUE TITLE
additional_costs_current_hour only shows the last value for the day.

### ISSUE THREAD

**Issue by dagstuan** [custom-components/nordpool#258]
Hello, thanks for an awesome plugin! I noticed an issue with how the `additional_costs_current_hour` property works. Currently it seems to only show the last value calculated, and not the value for the current hour. I have a template such as this one just for test purposes:

```
{% if now().hour >= 6 and now().hour < 23 %}
    {{ 3 }}
{% else %}
    {{ 25.0 }}
{% endif %}
```
    
With this template, the `additional_costs_current_hour` shows as `25` no matter what time of day it is.

**Comment by Hellowlol** [comment]
Hi. Thanks for the bug report. The reason this happens is because if _calc_price is called for every hour. Current hour is not whats called last as as a result it will prick the last hour of tomorrow as a value.

Its a easy fix.
