### ISSUE TITLE
No more than one Nord Pool integration can be configured at a time

### ISSUE THREAD

**Issue by Kirbo** [custom-components/nordpool#259]
Since I live in Finland and we have moved to temporary vat 10% for electricity between 2023-01-01 and 2023-04-30, I thought that I could most easily tackle this by adding two Nord Pool integrations: one with VAT 10% (in Additional Cost input) and one with VAT 24% (in Additional Cost input), but once I added the second integration, it isn't working.

The first integration works just as it should, but the second one does not create any device/entity what so ever.

1. First integration added
![image](https://user-images.githubusercontent.com/1077974/210295200-b0916a28-b240-4094-8779-8762f328cf0e.png)

2. Added the second integration 
![image](https://user-images.githubusercontent.com/1077974/210295256-80ef4322-5def-440d-a7b3-0c589dabd682.png)

3. Checking the second integration and it contains _nothing_ 
![image](https://user-images.githubusercontent.com/1077974/210295293-204654fa-62e2-4c80-97a9-79a9036cdd5c.png)

4. Trying to filter entities in "Developer Tools -> States" and it only finds the entity created in the first integration 
![image](https://user-images.githubusercontent.com/1077974/210295335-e6dc98f5-a714-4261-bccd-05cf17328e7a.png)

**Comment by Hellowlol** [comment]
No logs so I have no idea. My assumption is that the same entity_id is created and ha will ignore it. You can attempt to add a new sensor with a different precision for example 6. It that doesn't work please reopen the issue after logs are provided.
