### ISSUE TITLE
Error on newer Hassio

### ISSUE THREAD

**Issue by MissMusic** [custom-components/nordpool#26]
After updating Home Assistant i now get this error when validating config:

Component error: nordpool - Requirements for nordpool not found: ['pendulum>=2.0'].
Platform error sensor.nordpool - Requirements for nordpool not found: ['pendulum>=2.0'].

Anyone else?

**Comment by Hellowlol** [comment]
Dunno. Try reboot

**Comment by MissMusic** [comment]
I’ve tried that, this is the whole error message:

Log Details (ERROR)
Logger: homeassistant.util.package
Source: util/package.py:88 
First occurred: 10:42:19 PM (2 occurrences) 
Last logged: 10:42:46 PM

Unable to install package pendulum>=2.0: ERROR: Command errored out with exit status 1: command: /usr/local/bin/python3 /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpy5x54mvz cwd: /tmp/pip-install-o5ka06rf/pendulum Complete output (24 lines): Traceback (most recent call last): File "setup.py", line 2, in <module> from setuptools import setup ModuleNotFoundError: No module named 'setuptools' Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module> main() File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main json_out['return_val'] = hook(**hook_input['kwargs']) File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 182, in build_wheel metadata_directory) File "/tmp/pip-build-env-6m5foq0j/overlay/lib/python3.7/site-packages/poetry/core/masonry/api.py", line 57, in build_wheel return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory))) File "/tmp/pip-build-env-6m5foq0j/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 56, in make_in wb.build() File "/tmp/pip-build-env-6m5foq0j/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 82, in build self._build(zip_file) File "/tmp/pip-build-env-6m5foq0j/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 102, in _build self._run_build_command(setup) File "/tmp/pip-build-env-6m5foq0j/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 131, in _run_build_command [sys.executable, str(setup), "build", "-b", str(self._path / "build")] File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['/usr/local/bin/python3', 'setup.py', 'build', '-b', 'build']' returned non-zero exit status 1. ---------------------------------------- ERROR: Failed building wheel for pendulum ERROR: Could not build wheels for pendulum which use PEP 517 and cannot be installed directly
Unable to install package pendulum>=2.0: ERROR: Command errored out with exit status 1: command: /usr/local/bin/python3 /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpymd2r3f2 cwd: /tmp/pip-install-6f_sijjo/pendulum Complete output (24 lines): Traceback (most recent call last): File "setup.py", line 2, in <module> from setuptools import setup ModuleNotFoundError: No module named 'setuptools' Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module> main() File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main json_out['return_val'] = hook(**hook_input['kwargs']) File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 182, in build_wheel metadata_directory) File "/tmp/pip-build-env-awx291mw/overlay/lib/python3.7/site-packages/poetry/core/masonry/api.py", line 57, in build_wheel return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory))) File "/tmp/pip-build-env-awx291mw/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 56, in make_in wb.build() File "/tmp/pip-build-env-awx291mw/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 82, in build self._build(zip_file) File "/tmp/pip-build-env-awx291mw/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 102, in _build self._run_build_command(setup) File "/tmp/pip-build-env-awx291mw/overlay/lib/python3.7/site-packages/poetry/core/masonry/builders/wheel.py", line 131, in _run_build_command [sys.executable, str(setup), "build", "-b", str(self._path / "build")] File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['/usr/local/bin/python3', 'setup.py', 'build', '-b', 'build']' returned non-zero exit status 1. ---------------------------------------- ERROR: Failed building wheel for pendulum ERROR: Could not build wheels for pendulum which use PEP 517 and cannot be installed directly

**Comment by MissMusic** [comment]
Is it running fine for you on latest Home Assistant 0.107.7?
If yes, I'll try reinstalling and see if it changes anything.

**Comment by Hellowlol** [comment]
Im running 107.6. Ill look into it later.

**Comment by IZZE2000** [comment]
Also got error checking 107.7. Works fine on 107.6

  General Errors: 
    - Platform error sensor.nordpool - Requirements for nordpool not found: ['pendulum>=2.0'].
    - Component error: default_config - Requirements for cloud not found: ['hass-nabucasa==0.32.2'].

**Comment by Hellowlol** [comment]
I have no idea why this is happening or how to fix it. For now you need to manually install the dep.

docker exec -it homeassistant bin/bash
pip install poetry
pip install --no-build-isolation pendulum==2.1.0

**Comment by MissMusic** [comment]
When i run the first command docker exec i get:

OCI runtime exec failed: exec failed: container_linux.go:346 starting container process caused "exec: \"bin/bash\": stat bin/bash: no such file or directory": unknown

Any idea of what to try? I tried a rollback to 107.6 but still the same pendulum requirement error.

**Comment by Hellowlol** [comment]
Sorry, it was /bin/bash. Anyway, ill drop pendulum. I expect this to be done tomorrow.

**Comment by MissMusic** [comment]
@Hellowlol Thanks, the manual steps above removed all errors in the log and after a full restart (including supervisor) it's up and running again. Bonus is that i downloaded the latest release in my troubleshooting and it seems to have fixed a few other errors i had as well.

**Comment by Hellowlol** [comment]
Should be fixed with the latest commit, please verify.
