### ISSUE TITLE
Calculating wrong?

### ISSUE THREAD

**Issue by BliXem1** [custom-components/nordpool#260]
I’ve got some issues with my Nordpool, and that’s not the extension but the calculating. I don’t understand. I don’t have a dynamic energy contract yet, but I want to know the right prices. So I hope someone can help me.

What I got now is:

```
  - platform: nordpool
    VAT: False
    currency: "EUR"
    price_in_cents: true
    low_price_cutoff: 0.5
    region: "BE"
    precision: 3
    price_type: kWh
    additional_costs: >
      {% set VAT = 0.06 %}
      {% set kwh_tarief = 0.0 %}
      {% set bijz_accijns = 0.0 %}
      {% set energiebijdrage = 0.0 %}
      {% set groenestroom_wkk = 0.0 %}
      {% set marge = 0.0 %}
      {{ ((current_price + marge) * VAT + kwh_tarief + bijz_accijns + energiebijdrage + groenestroom_wkk) |float }}
```

Within my configuration.yaml file. If you can see, the VAT will be calculated (6%) for now. The price is correct. If I calculate the Market data from Nord Pool, you see between 00-01 a price of 130,01. So I calculate 130.01*0.01 * 1.06 which is good now. But when I add the marge of 0.2040 it has to be on 13,9973 but it calculates within HA this value: 15.005 which is incorrect…

130.01*0.1+0.2040 * 1.06 = 13,9973 and not 15.005. Any idea why it goes wrong?
Even when I add a extra 0 at marge (0.02040) it calculates wrong, it’s saying then 13,903…

You can see here the right prices of all add. costs:

```
{% set s = {"VAT": 1.06,"kwh_tarief": 0.0394475,"bijz_accijns": 0.0144160,"energiebijdrage": 0.0020417,"groenestroom_wkk": 0.02714,"marge": 0.002040 } %}
{{((current_price + s.marge) * s.VAT + s.kwh_tarief + s.bijz_accijns + s.energiebijdrage + s.groenestroom_wkk) | float}}
Hope someone can help me to get the right price.
```

Any one got the fix?

**Comment by yozik04** [comment]
I might be wrong but `current_price` is most probably a string that you need to convert first.

**Comment by BliXem1** [comment]
> I might be wrong but `current_price` is most probably a string that you need to convert first.

Do you have an example? :)

**Comment by BliXem1** [comment]
Got it right now:

```
  - platform: nordpool
    VAT: False
    currency: "EUR"
    price_in_cents: false
    low_price_cutoff: 0.5
    region: "BE"
    precision: 5
    price_type: kWh
    additional_costs: >
      {% set VAT = 0.06 %}
      {% set netwerkkosten = 0.0394475 %}
      {% set federale_accijns = 0.014416 %}
      {% set energiebijdrage = 0.0020417 %}
      {% set groenestroom_wkk = 0.02184 %}
      {% set marge = 0.002040 %}
      {{((current_price + marge) * VAT + netwerkkosten + federale_accijns + energiebijdrage + groenestroom_wkk) |float}}
```

But there is a difference of 0.002 euro. Is this an error in the script or?

**Comment by BliXem1** [comment]
fixed

**Comment by Hellowlol** [comment]
I don't know, but i would attempt to set the precision higher, at least as high as other values you use in your calculations.

**Comment by BliXem1** [comment]
Alright tried, this doesn't correct it. I tried precision 5 and 7 but it don't correct the price to the right price, only if I add this:
 {% set correctie = 0.002 %}

Running on the latest beta.

**Comment by BliXem1** [comment]
Do you want me to debug so you can fix it or? :) for me it's already fixed. haha.

**Comment by Hellowlol** [comment]
No I can. I don’t really care if your template is correct or not. If you are happy I’m good 👍
