### ISSUE TITLE
Fixed additional_costs do not add up

### ISSUE THREAD

**Issue by kokesh** [custom-components/nordpool#265]
I've got nordpool working flawlessly for a long time, configured in the UI. I've decided to add additional cost per kWh (fixed energy tax+transfer fee).
I've added additional_costs into configutration.yaml as following:
- platform: nordpool
    : "{{current_price + 0.574|float}}"

Current price is 1SEK + the extra cost, but it still shows 1SEK in the entity. What am I doing wrong?
I've restarted HA.

**Comment by Hellowlol** [comment]
What entity are you referring to? Is it the additional costs attribute? If so there is a 🐜so it don’t update as it should

**Comment by kokesh** [comment]
I've got my current price entity. I thought additiknal costs would be added i to it's value.

**Comment by Hellowlol** [comment]
Closing, please update to the latest version. Reopen if needed
