### ISSUE TITLE
Feature to enable low price for a number of cheapest hours during the day

### ISSUE THREAD

**Issue by JanneMantyharju** [custom-components/nordpool#268]
**Is your feature request related to a problem? Please describe.**
I'm using the low price attribute to trigger electricity usage in my home. Lately here in Finland there has been few days when the electricity cost is nearly the same for every hour and thus never much below average. This causes the low price never to activate.

**Describe the solution you'd like**
In addition the defining an average cutoff to trigger low price, there would be an attribute to define number of needed usage hours per day. The sensor would then enable low price for set number of cheapest hours during the day

**Comment by Hellowlol** [comment]
Hi, thanks for you feature request. This will not be implemented as it just technical debt that needs to be maintained and it’s impossible to account for every use case. The user should create their own template sensor for features like this.
