### ISSUE TITLE
Additional costs

### ISSUE THREAD

**Issue by Repsionu** [custom-components/nordpool#276]
Nordpool version=latest
All works OK but can not make usage of {{current_price}} in additional costs :-(
Tyied this and it passes HA config checks but after reload results in 'Can not convert string to float'?
My part of additional_costs:

`                      {% if current_price <= 0.08 %}
                         {{ current_price + float(0.05) }}
                      {% endif %}
`
Sorry if this is my coding fault, will remove issue then.
Best, JR

Update: as I could not figure out why current_price remained unaltered I modified **additional_costs:** another way:

`                      {% if current_price <= 0.08 %}
                        {% set compensation = 0 %}
                      {%else%}
                        {% set compensation = -5 %}
                      {% endif %}
`
and used varaiable **compensation** in day/night price calculations.
I know it is brute force but sufficent for now :-)

**Comment by Hellowlol** [comment]
Try updating to the latest pre release
