### ISSUE TITLE
Request: More attributes

### ISSUE THREAD

**Issue by Neznix** [custom-components/nordpool#277]
It would be nice to have the other values from tomorrows prices as attributes, for example min, max and average.

**Comment by renslinden** [comment]
I had the same idea, like your proposal.

**Comment by FredrikNas** [comment]
I would also like the min max and average for tomorrow.

**Comment by gnissahr** [comment]
That would be awesome. Currently struggling with template sensors to set it up, but would be far easier if it was an attribute!

**Comment by Anders57S** [comment]
I would also find it useful to have an configurable high_price attribute.

**Comment by utsnik** [comment]
Would love to have the same!

**Comment by Hellowlol** [comment]
Closing, out of scope and duplicate
