### ISSUE TITLE
Gas prices as well?

### ISSUE THREAD

**Issue by DohmenICT** [custom-components/nordpool#278]
**Describe the solution you'd like**
I would like to have a list of the GAS prices which go along with the Electricity prices. (especially in the Netherlands but I can only imagine this also works for a lot of other countries)

**Describe alternatives you've considered**
I now scrape this info from my local energy provider; but that API is instable.

**Additional context**
In the  Netherlands this price is set daily at 6:00. Would be nice to get the price per M3 and per KwH. (If needed, please make the conversion factor from M3 to KwH configurable)

**Comment by Hellowlol** [comment]
The api does not support has prices
