### ISSUE TITLE
Template not working as expected

### ISSUE THREAD

**Issue by bolderbast** [custom-components/nordpool#280]
## Version of the custom_component
0.0.10

## Homeassistant version
2023.1.6

## Configuration

```yaml

No YAML. Adding the integration through the UI Config Flow.

```

## Describe the bug
When adding the sensor without specifying a Template, the resulting value of the sensor is 0.1464. This seems to be correct.
When reading the documentation, I would expect this template `{{ (current_price + 0.126 + 0.002) * 1.21 }}` (entered during the GUI Config Flow) to result in 0.332024. Instead, it results in sensor value 0.478424.

**Comment by bolderbast** [comment]
With the following template, I DO get the correct resulting value: `{{ ((current_price + 0.126 + 0.002) * 1.21) - current_price }}`

**Comment by Hellowlol** [comment]
The template is for additional costs. Meaning the output of the template will be added to this hours current price

Example:
Current hour is 1
The template is 0.5
Current hour is now 1.5

**Comment by bolderbast** [comment]
OK, so then this part in the documentation is incorrect, I suppose?
Can that be adjusted?

**Comment by Hellowlol** [comment]
Documentation is fixed now. Thanks
