### ISSUE TITLE
Addtional cost can't find the mistake

### ISSUE THREAD

**Issue by TheEnergy** [custom-components/nordpool#285]
0.0.10 Version of the custom_component

Home Assistant 2023.1.7

Configuration is

`sensor:
  - platform: nordpool
    # Country/region to get the energy prices for.
    region: "DK2"

    # Override HA local currency used to fetch the prices from the API.
    currency: "DKK"

    # Add Value Added Taxes (VAT)?
    VAT: True

    # Energy price rounding precision.
    precision: 3

    # Display price in cents in stead of (for example) Euros.
    price_in_cents: false

    # Price displayed for MWh, kWh or Wh
    price_type: kWh

    # Template to specify additional cost to be added to the tariff.
    # The template price is in EUR, DKK, NOK or SEK (not in cents).
    # For example: "{{ current_price * 0.19 + 0.023 | float}}"
    additional_costs: >    
    {% if now().hour >= 0 and now().hour < 6 %}
        {{ current_price + 0.210 | float }}
    {% if now().hour >= 6 and now().hour < 17 %}
        {{ current_price + 0.640 | float }}
    {% if now().hour >= 17 and now().hour < 21 %}
        {{ current_price + 1.910 | float }}
    {% if now().hour >= 21 and now().hour < 24 %}
        {{ current_price + 0.640 | float }}
    {% endif %}`

The error is 

"missed comma between flow collection entries (46:6)

 43 |     # The template price is in EUR,  ...
 44 |     # For example: "{{ current_price ...
 45 |     additional_costs: >    
 46 |     {% if now().hour >= 0 and now(). ...
-----------^
 47 |         {{ current_price + 0.210 | f ...
 48 |     {% if now().hour >= 6 and now(). ..."
 
 The same issue is in this post
 https://github.com/custom-components/nordpool/issues/263
 
 But i cant seem to find what the solution was actually.

**Comment by ruteclrp** [comment]
My issue was not sticking to the ninja template requirement to use 2 space indentation rule always. 

Look at your code and make sure the indentations are done with spaces and that there are always pairs of 2 when indentation needed

**Comment by TheEnergy** [comment]
> My issue was not sticking to the ninja template requirement to use 2 space indentation rule always.
> 
> Look at your code and make sure the indentations are done with spaces and that there are always pairs of 2 when indentation needed

Im not hardcare user at this yet. i understand that there is something im missing. i have taken a screenshot of the config. Can you point more direct to the error?

[https://imgur.com/a/W1jsWeL](url)

**Comment by ruteclrp** [comment]
1. Additional cost is what the integration adds to the current price anyway. Therefore the additional cost should not contain also current price. 

2. I used 'if' something, then a
           'Elif' something else, then b

And so on. I note that you use if, if, if, if

3. Play with the indentations 
   As I said.

**Comment by ruteclrp** [comment]
```

sensor:
  - platform: nordpool
    region: "DK2"
    currency: "DKK"
    VAT: True
    precision: 3
    price_in_cents: false
    price_type: kWh
    additional_costs: >
      {% if now().hour >= 0 and now().hour < 6 %}
        {{ 0.210 | float }}
      {% elif now().hour >= 6 and now().hour < 17 %}
        {{ 0.640 | float }}
      {% elif now().hour >= 17 and now().hour < 21 %}
        {{ 1.910 | float }}
      {% elif now().hour >= 21 and now().hour < 24 %}
        {{ 0.640 | float }}
      {% endif %}
```

I think this should work when added to the configuration.y'all

**Comment by TheEnergy** [comment]
> ```
> 
> sensor:
>   - platform: nordpool
>     region: "DK2"
>     currency: "DKK"
>     VAT: True
>     precision: 3
>     price_in_cents: false
>     price_type: kWh
>     additional_costs: >
>       {% if now().hour >= 0 and now().hour < 6 %}
>         {{ 0.210 | float }}
>       {% elif now().hour >= 6 and now().hour < 17 %}
>         {{ 0.640 | float }}
>       {% elif now().hour >= 17 and now().hour < 21 %}
>         {{ 1.910 | float }}
>       {% elif now().hour >= 21 and now().hour < 24 %}
>         {{ 0.640 | float }}
>       {% endif %}
> ```
> 
> I think this should work when added to the configuration.y'all

Yes i can add this but doesnt seem to work. It does not add extra cost on? Or does it only works after next call of new price?

**Comment by ruteclrp** [comment]
I think it executes when updating prices once a day. Another way would be to reload the integration to force the updateVenlig hilsenL. Robert Pedersen+45 2048 4482Sent from my iPhoneOn 29 Jan 2023, at 12.07, TheEnergy ***@***.***> wrote:﻿


sensor:
  - platform: nordpool
    region: "DK2"
    currency: "DKK"
    VAT: True
    precision: 3
    price_in_cents: false
    price_type: kWh
    additional_costs: >
      {% if now().hour >= 0 and now().hour < 6 %}
        {{ 0.210 | float }}
      {% elif now().hour >= 6 and now().hour < 17 %}
        {{ 0.640 | float }}
      {% elif now().hour >= 17 and now().hour < 21 %}
        {{ 1.910 | float }}
      {% elif now().hour >= 21 and now().hour < 24 %}
        {{ 0.640 | float }}
      {% endif %}

I think this should work when added to the configuration.y'all

Yes i can add this but doesnt seem to work. It does not add extra cost on? Or does it only works after next call of new price?
