### ISSUE TITLE
Home Assistant 2023.2 - state class and device class missmatch

### ISSUE THREAD

**Issue by Samppady** [custom-components/nordpool#289]
Log Details (WARNING):

Entity sensor.nordpool_kwh_fi_eur_3_10_01 (<class 'custom_components.nordpool.sensor.NordpoolSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

Entity sensor.nordpool_kwh_fi_eur_3_00_01 (<class 'custom_components.nordpool.sensor.NordpoolSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

Running the latest version of integration and home assistant and HACS.

**Comment by Hellowlol** [comment]
Dulicate
