### ISSUE TITLE
Historical data

### ISSUE THREAD

**Issue by Safs** [custom-components/nordpool#292]
Hello!

Is it possible to get historical data of hourly prices? For example for last month?

Thanks!

**Comment by Hellowlol** [comment]
Use the historie page?

**Comment by Safs** [comment]
I mean, how to get data from NordPool database for older periods.

**Comment by t0xa** [comment]
Nordpool provides historical data for a fee - https://www.nordpoolgroup.com/en/services/power-market-data-services/dataportalregistration/

**Comment by Hellowlol** [comment]
Hi, 

I’m pretty confident that you could use the nordpool Python library to do this. It is also possible to use ensoe api. If you know sole basic scripting in Python that should be a trivial task :)
