### ISSUE TITLE
Additional_costs with seasonal/time overheads reports wrong value of attributes

### ISSUE THREAD

**Issue by MilletGtR** [custom-components/nordpool#293]
**Introduction**
When using additional costs with 'Example 5' under the header 'Additional costs' in the readme.md, the created sensor reports wrong values of most of the attributes. I've noticed most of them to be wrongly calculated seemingly depending on the current additional cost.

**Prerequisites**
A bit of an explanation before the pictures below:

I have peak hours between 06:00 - 22:00 during the winter (except on weekends) where i pay an extra 56 öre (0,56 swedish crowns) per kWh. I've added the nordpool sensor using the template:

```
{% set s = {
    "energiskatt": 0.49,
    "låglast": 0.12,
    "höglast": 0.70,
    "cert": 0.1175
}
%}
{% if (now().month >= 4 and now().month <= 10) or (now().weekday() >= 5) %}
    
{{ s.låglast + s.energiskatt + s.cert | float }}
{% else %}
    {% if now().hour >= 6 and now().hour < 22 %}
        {{ s.höglast + s.energiskatt + s.cert | float }}
    {% else %}
        {{ s.låglast + s.energiskatt + s.cert | float }}
    {% endif %}
{% endif %}
```

**Theory**
What seems to be happening is that it takes the current additional costs and applies it across the board for all attribute calculations. This means that some attributes will be wrong (those that are outside of the time restriction in my template) and some will be right (those that are completely inside the time restriction), for instance peak (08:00 - 20:00) is inside the range defined by me (06:00 - 22:00).

**Pictures**
Example of the 'min' attribute being wrong
<img width="366" alt="Nordpool custom template bug" src="https://user-images.githubusercontent.com/114057317/219660558-e0a2df8f-7481-42ec-bf49-1ad15b4bc8e7.png">

Spreadsheet of current calculation and the correct one plus the theory of why (+56)
<img width="479" alt="Speadsheet - Correct vs current" src="https://user-images.githubusercontent.com/114057317/219666742-f339664e-8cb4-43f4-a19f-e7b64c2b3e64.png">

**Conclusion**
As you can see in the speadsheet, it seems that the integration only considers the current additional_costs when calulating the attributes. Reavaluating them when it changes the additional_cost within the same day.

The theory column is basically what I think is going on (+56 öre on the hours outside of 06:00-22:00) and coupled with a theory calculation (to the right) basically confirming that this theory is correct. The theory is the same as the nordpool sensor here.

**Work-around**
I've currently added my own attributes as sensors based on the today values:

```
nordpool_today_min:
        friendly_name: "Nordpool idag min"
        unit_of_measurement: "öre"
        value_template: >
          {{ ((state_attr('sensor.nordpool_kwh_se3_sek_0_10_025', 'today') | sort(reverse=false))[int(0)] )| round(0) }}
```

**Comment by Hellowlol** [comment]
Are you using the lastest version of this integration? There was a bug causing this to happen but thet is fixed

**Comment by MilletGtR** [comment]
> Are you using the lastest version of this integration? There was a bug causing this to happen but thet is fixed

Maybe I should have lead with that. Yes this resolved the issue.

**Comment by Hellowlol** [comment]
Ok, please close the issue if its working as excepted with the latest version
