### ISSUE TITLE
Nordpool price diff. looking at the site and using the "plugin"

### ISSUE THREAD

**Issue by HenrikDK1971** [custom-components/nordpool#294]
[Hi])
Thank you for a great plugin!

My questions is the following, - when looking at the site:  [https://www.nordpoolgroup.com/en/Market-data1/Dayahead/Area-Prices/DK/Hourly/?dd=DK2&view=table](https://www.nordpoolgroup.com/en/Market-data1/Dayahead/Area-Prices/DK/Hourly/?dd=DK2&view=table)

You can see that the prices from the nordpool site is for the 18-02-2023: 

- 0-1: 204,47
- 1-2: 185,63
- 3-4: 171,11

Using your plugin the output is for the 18-02-2023:
[0 … 9]
- 0-1: 0.256
- 1-2: 0.232
- 2-3: 0.214
- 3-4: 0.234

**It's about 0,50 Dkr in difference, - what is the true and the differens here, and why? Which one should I believe(besides the Mega/Kilo conerting)?**

object
entity_id: "sensor.nordpool_kwh_dk2_dkk_3_10_025"
state: "0.256"
attributes: object
state_class: "measurement"
average: 0.3232916666666667
off_peak_1: 0.238125
off_peak_2: 0.3125
peak: 0.38366666666666666
min: 0.214
max: 0.97
mean: 0.268
unit: "kWh"
currency: "DKK"
country: "Denmark"
region: "DK2"
low_price: true
price_percent_to_average: 0.7918546204407784
today: array[24]
[0 … 9]
0: 0.256
1: 0.232
2: 0.214
3: 0.234
4: 0.228
5: 0.232
6: 0.249
7: 0.26
8: 0.279
9: 0.304

**Comment by Hellowlol** [comment]
Its vat that  makes up the difference

**Comment by HenrikDK1971** [comment]
Can I turn that off, in DK it's quite complex calculation, - and I've done that myself

**Comment by Hellowlol** [comment]
Yeah, just delete the sensor and set it up again using the gui

**Comment by HenrikDK1971** [comment]
Thank you for helping with a 40 cm from the screen errror
