### ISSUE TITLE
Off Peak1 & 2

### ISSUE THREAD

**Issue by eirektg** [custom-components/nordpool#3]
Hi. 

Only a suggestion - add the definition of what off peak 1 and off peak 2 are

**Comment by Hellowlol** [comment]
Good idea. Where would you want this documented? It’s documented inside the extract atters code

**Comment by eirektg** [comment]
You are right :-)

But for non coding people (like myself) maybe in the bottom of the readme.md so that it's quite easy to understand which default time ranges that are in play for each of them. 

Suggestion for next release.
Is it easy for you to add the possibility to change the time periods for both off peak 1 & 2 in the configuration.yaml so it's easy to change?

**Comment by Hellowlol** [comment]
Why would you need to change it? the times are all the same regarding the timezone. Or at least  it should 😂

**Comment by Hellowlol** [comment]
Ah, crap i see what you mean. My helper uses another timezone for fixing missing values from the api. Ill fix  that.

**Comment by eirektg** [comment]
I was about to write an answer, but I see now that you understood what i meant :-)

Basically my suggestion is that it would be nice if its easy to tweak the 3 different peak periods you have defined so it fits to the home for that user/installation.

Anyway, thank you for making this Nordpool intergration 👍

**Comment by Hellowlol** [comment]
Thank you, im glad i could be usefull for somebody else. 

There will not be a option to set offset or something like that. This will set automagically using you local time zone :+1:

**Comment by Hellowlol** [comment]
I think i got it right now. Let me know if you still have issues.
