### ISSUE TITLE
Entity no longer provided by the nordpool integration

### ISSUE THREAD

**Issue by sangvikh** [custom-components/nordpool#302]
Noticed the price did not update at midnight. Tried to reload the integration, but now the sensor is unavailable.
Tried updating to latest home assistant version, still the same.

```
Logger: homeassistant.components.sensor
Source: custom_components/nordpool/sensor.py:344
Integration: Sensor (documentation, issues)
First occurred: 00:44:50 (2 occurrences)
Last logged: 00:44:50

Error adding entities for domain sensor with platform nordpool
Error while setting up nordpool platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 806, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/nordpool/sensor.py", line 521, in async_added_to_hass
    await self.handle_new_hr()
  File "/config/custom_components/nordpool/sensor.py", line 495, in handle_new_hr
    self._update()
  File "/config/custom_components/nordpool/sensor.py", line 344, in _update
    self._average = mean(today)
  File "/usr/local/lib/python3.10/statistics.py", line 329, in mean
    T, total, count = _sum(data)
  File "/usr/local/lib/python3.10/statistics.py", line 187, in _sum
    T = _coerce(T, typ)  # or raise TypeError
  File "/usr/local/lib/python3.10/statistics.py", line 237, in _coerce
    raise TypeError(msg % (T.__name__, S.__name__))
TypeError: don't know how to coerce float and NoneType
```

Log
```
Logger: homeassistant.util.logging
Source: util/logging.py:156
First occurred: 00:44:50 (1 occurrences)
Last logged: 00:44:50

Exception in handle_new_hr when dispatching 'nordpool_update_hour': () Traceback (most recent call last): File "/config/custom_components/nordpool/sensor.py", line 495, in handle_new_hr self._update() File "/config/custom_components/nordpool/sensor.py", line 344, in _update self._average = mean(today) File "/usr/local/lib/python3.10/statistics.py", line 329, in mean T, total, count = _sum(data) File "/usr/local/lib/python3.10/statistics.py", line 187, in _sum T = _coerce(T, typ) # or raise TypeError File "/usr/local/lib/python3.10/statistics.py", line 237, in _coerce raise TypeError(msg % (T.__name__, S.__name__)) TypeError: don't know how to coerce float and NoneType
```

**Comment by MrBamse** [comment]
Same here
Home Assistant 2023.3.6
Frontend 20230309.1
Latest version of the integration

**Comment by ljungqvist** [comment]
You can replace lines 344-350 in sensor.py with
```
        self._average = mean(filter(None, today))
        self._min = min(filter(None, today))
        self._max = max(filter(None, today))
        self._off_peak_1 = mean(filter(None, today[0:8]))
        self._off_peak_2 = mean(filter(None, today[20:]))
        self._peak = mean(filter(None, today[8:20]))
        self._mean = median(filter(None, today))
```
The problem is with daylight saving time (don't we all love it)

**Comment by MrBamse** [comment]
Haha omg xD
You are our hero Petter!
May DST b*** i* h*** ;)

//Ted

**Comment by jpakanen2** [comment]
Same problem here. No warm water this morning. My wife and children will thank me and my hobbies when they will wake up 😁

**Comment by lightheaded** [comment]
Damn, the moment I switch from a simple HTTP API sensor to a "proper" addon, this happens 🤣

No, just kidding. Bugs happen. Keep up the good work! Hope this gets resolved soon.

**Comment by uphillbattle** [comment]
> You can replace lines 344-350 in sensor.py with
> 
> ```
>         self._average = mean(filter(None, today))
>         self._min = min(filter(None, today))
>         self._max = max(filter(None, today))
>         self._off_peak_1 = mean(filter(None, today[0:8]))
>         self._off_peak_2 = mean(filter(None, today[20:]))
>         self._peak = mean(filter(None, today[8:20]))
>         self._mean = median(filter(None, today))
> ```
> 
> The problem is with daylight saving time (don't we all love it)

Excellent, @ljungqvist, well done, works like a charm. You should make a PR with this fix.

**Comment by boomchackalack** [comment]
Thanks a lot @ljungqvist !

**Comment by angainor** [comment]
it's funny how many of us wake up to the same problem :)

**Comment by anandlar** [comment]
Thanks a lot @ljungqvist !
Will this fix work when we get to "wintertime" again?

**Comment by jarube** [comment]
Wow, thank you. Had the same problem here.

**Comment by brackman1** [comment]
> You can replace lines 344-350 in sensor.py with
> 
> ```
>         self._average = mean(filter(None, today))
>         self._min = min(filter(None, today))
>         self._max = max(filter(None, today))
>         self._off_peak_1 = mean(filter(None, today[0:8]))
>         self._off_peak_2 = mean(filter(None, today[20:]))
>         self._peak = mean(filter(None, today[8:20]))
>         self._mean = median(filter(None, today))
> ```
> 
> The problem is with daylight saving time (don't we all love it)

Thanks a lot for the solution. After setting it up yesterday for the first time and next day it was broken :( by the summertime.

**Comment by Svanto1963** [comment]
Do not work here :(

**Comment by elden1337** [comment]
> Thanks a lot @ljungqvist !
> Will this fix work when we get to "wintertime" again?

I dont think it will unfortunately. That list probably does not contain a None-item but 25 hours of numbers.

**Comment by hvhol** [comment]
Wow you are great Thnx !

**Comment by tux2000** [comment]
> You can replace lines 344-350 in sensor.py with
> 
> ```
>         self._average = mean(filter(None, today))
>         self._min = min(filter(None, today))
>         self._max = max(filter(None, today))
>         self._off_peak_1 = mean(filter(None, today[0:8]))
>         self._off_peak_2 = mean(filter(None, today[20:]))
>         self._peak = mean(filter(None, today[8:20]))
>         self._mean = median(filter(None, today))
> ```
> 
> The problem is with daylight saving time (don't we all love it)

Thanks for the suggested quick-fix. I added a PR for it to maybe make it less work for @Hellowlol to push this change to a new release.

**Comment by systeemi** [comment]
Thank you very much!!!

**Comment by kurtdefeyter** [comment]
many thanks , works like a charm
Best Regards

**Comment by chheiss** [comment]
Replaced these lines but not getting new values for today and tomorrow...

**Comment by joem65** [comment]
Perfekt! Tackar @ljungqvist

**Comment by dront242** [comment]
Thanks @ljungqvist!

**Comment by torsteinelv** [comment]
Same problem here. But cant this be fixed and rolled out instead?

**Comment by tux2000** [comment]
The new release fixed the error for me, thanks for the quick solution @Hellowlol!

**Comment by MIBSkyrup** [comment]
Very quick fix available to download via HACS.

Fixes some of my problems:
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'
AND
TypeError: '<' not supported between instances of 'NoneType' and 'float'

but now get following error:

UndefinedError: list object has no element 23

**Comment by mumse** [comment]
> 

Just did the update a minute ago, seems to work ok for me atleast.

**Comment by Hellowlol** [comment]
@MIBSkyrup that seems like a weird Python error. Is this a template error? I assume so as today only has 23 hours (22 in Python as it’s zero indexed) please open a new issue provide logs and template

**Comment by MIBSkyrup** [comment]
> @MIBSkyrup that seems like a weird Python error. Is this a template error? I assume so as today only has 23 hours (22 in Python as it’s zero indexed) please open a new issue provide logs and template

Agree, it looked strange. Makes perfect sence that is due to today only is 23 hours. Pretty sure it will be sorted out tomorrow, otherwise I will send requested information. Thanks for super support!
