### ISSUE TITLE
Add holidays (sensor?) option to additional_costs

### ISSUE THREAD

**Issue by Repsionu** [custom-components/nordpool#311]
As we can only use **current_price and now()** in this template there is no viable way to add state based check like that: 
**{% if states('calendar.holidays') ==0 %}** 
to signal the integration that the day is a holiday and requires another tariff not dependant on weekday...
Or maybe I have misunderstood something?
Best, JR

**Comment by Hellowlol** [comment]
Hi, 

Yes you have. Please read the readme
