### ISSUE TITLE
No data from Nordpool with Fin VAT 24%

### ISSUE THREAD

**Issue by twosh** [custom-components/nordpool#319]
Hi!

If the VAT is 0.24 I get no data. If I manually change it on line 37 in sensor.py to 0.1 it starts to pull data again.

This error originated from a custom integration.

Logger: custom_components.nordpool_planner.binary_sensor
Source: custom_components/nordpool_planner/binary_sensor.py:294
Integration: nordpool_planner (documentation, issues) 
First occurred: 4:32:51 PM (90 occurrences) 
Last logged: 4:54:51 PM

Got empty data from Norpool entity sensor.nordpool_kwh_fi_eur_3_095_01
No values for today in Norpool entity sensor.nordpool_kwh_fi_eur_3_095_01

**Comment by Hellowlol** [comment]
Please provide logs. Your change should really do anything, its more likely that something Else is messed up.

**Comment by twosh** [comment]
Hi, sorry, not to have, but all I get on Settings -> System -> Logs is this:

```
This error originated from a custom integration.

Logger: custom_components.nordpool_planner.binary_sensor
Source: custom_components/nordpool_planner/binary_sensor.py:294
Integration: nordpool_planner (documentation, issues)
First occurred: 6:48:58 PM (2 occurrences)
Last logged: 6:48:58 PM

Got empty data from Norpool entity sensor.nordpool_kwh_fi_eur_3_095_01
```

Can I get more detailed logs somewhere else?

**Comment by helmha** [comment]
Same problem here. I changed the VAT value in sensor.py in line 37 from 0.1 to 0.24 and now I can't receive any data from Nordpool. When I revert the change it will work again.

**Comment by Hellowlol** [comment]
Dunno, without logs but yes I think so. Don’t edit the code directly, there is an example in the readme to know to calcite vat your self

**Comment by twosh** [comment]
Sorry, false alarm. I setup the integration on a second HA instance to try different things, and found the reason for no data. When changing the VAT from 10% to 24% the integration creates a new sensor, e.g. sensor.nordpool_kwh_fi_eur_3_095_01 gets a sibling called sensor.nordpool_kwh_fi_eur_3_095_024 and the old one doesn't have any data any longer. So, what I and @helmha need to do is update all the places where we use the old sensor ID and add the new one.

Could perhaps be added as a NB in the readme just to help other confused people out. :) 

Cheers!
