### ISSUE TITLE
4 digit accuracy

### ISSUE THREAD

**Issue by Ayuus** [custom-components/nordpool#324]
Day ahead prices are set with 4-digit accuracy, e.g. price for may 27 13-14 hrs CET (set on may 26)  is set to -0.2534. In the Netherlands, that is -0.3066 including 21% VAT. However, the HA integration shows only - 0.031, even though in apexcharts-card, float_precision is set to 4.

**Comment by Hellowlol** [comment]
Close for not ising issue template. Check the sensors values in the states page if they have 4 digits that its all good and the problem is in apexcards. If it incorrect in states page reopen the issue and provide the required information

**Comment by Ayuus** [comment]
Hi Steffen,

 

I did that, in states, values are only 3 digits.

 

Regards, Ronald

 

Van: Steffen Fredriksen ***@***.***> 
Verzonden: Friday, 26 May 2023 17:20
Aan: custom-components/nordpool ***@***.***>
CC: Ayuus ***@***.***>; Author ***@***.***>
Onderwerp: Re: [custom-components/nordpool] 4 digit accuracy (Issue #324)

 

Close for not using issue template. Check the sensors values in the states page if they have 4 digits that its all good and the problem is in apexcards. If it incorrect in states page reopen the issue and provide the required information
