### ISSUE TITLE
Add fixed supplier costs

### ISSUE THREAD

**Issue by Ayuus** [custom-components/nordpool#325]
The integration supplies day ahead prices. Most of us have to pay additional costs, depending on supplier and contract. A way to add those costs automatically would be desirable.

**Comment by Hellowlol** [comment]
Closing. This is out of scope . There is no way to handle this automatically. I have no way of knowing the what the costs will be in the different regions/providers.

There is an example how you can add this manually yourself

**Comment by Ayuus** [comment]
Hi Steffen,

 

Thanks for your reply. I assume I did not express the request clearly. Of course, you have no way of knowing what the additional costs are.

I meant that we, users, can enter somewhere the extra cost we pay, and that the integration will take them into account.

 

Regards,

 

Ronald

 

Van: Steffen Fredriksen ***@***.***> 
Verzonden: Friday, 26 May 2023 17:24
Aan: custom-components/nordpool ***@***.***>
CC: Ayuus ***@***.***>; Author ***@***.***>
Onderwerp: Re: [custom-components/nordpool] Add fixed supplier costs (Issue #325)

 

Closing. This is out of scope . There is no way to handle this automatically. I have no way of knowing the what the costs will be in the different regions/providers.

There is an example how you can add this manually yourself

**Comment by Hellowlol** [comment]
That already possible. Please read the documentation in the readme
