### ISSUE TITLE
Configuring Command Line sensor using YAML has moved.

### ISSUE THREAD

**Issue by aurimassiaulys** [custom-components/nordpool#329]
you should fix new YAML  formating after HA update.

**Comment by Hellowlol** [comment]
I have no idea what you are talking about. Please send a pr to fix anything that is wrong in the documentation

**Comment by rdperkins** [comment]
I agree with Hellowlol. How do I know if I have the problem in my configuration.yaml? I have the following in that file:
sensor: !include sensor.yaml and binary_sensor.*_occupancy in the influxdb: section. Thanks for your help.

**Comment by Dstoofdijk** [comment]
I 'm facing same issue: Configuring Command Line sensor using YAML has moved.
Solution would be to change "YAML configuration to integration key"
Unclear how to act in this
