### ISSUE TITLE
translations directory should be renamed

### ISSUE THREAD

**Issue by priiduonu** [custom-components/nordpool#33]
running home-assistant v 0.109.2, the following warnings appear in the log:

```
nordpool: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this
```

**Comment by knas4ever** [comment]
Ya I have the same problem. Renaming the folder doesn't help. The sensor is dead!

**Comment by knas4ever** [comment]
> Ya I have the same problem. Renaming the folder doesn't help. The sensor is dead!

Is there a way to make it work again under home-assistant v 0.109.2?

**Comment by Hellowlol** [comment]
Unless your running 0.111 this isn’t the reason why the sensor don’t work. Open a new issue, post a image of your sensor and debug logs

**Comment by knas4ever** [comment]
> Unless your running 0.111 this isn’t the reason why the sensor don’t work. Open a new issue, post a image of your sensor and debug logs

Happened after upgrading to Home Assistant 0.109.6 (but of course that's not 0.111) :)

**Comment by Hellowlol** [comment]
This is fixed.
