### ISSUE TITLE
Additional cost division

### ISSUE THREAD

**Issue by Birdman86** [custom-components/nordpool#332]
## Version of the custom_component

0.0.14

## Homeassistant version
2023.6.4

## Configuration

```yaml

{{ (current_price / 2)| float}}

```

## Describe the bug
Tried to use division to calculate a rebate on the price but it doesn't seem to work as intended.
Tried "current_price / 2", but the math is incorrect, as the value returned is greater than x1. Not really sure how it calculates division.

**Comment by Hellowlol** [comment]
Try using the template editor in the gui.

**Comment by Birdman86** [comment]
I presume that you mean the template editor in the developer tools.
I've tried that to confirm the code but it doesn't help for two reasons.

1. This integration interprets the code/math logic differently, as if you want to add 20% VAT, you have to calculate it as current_price * 0.20, instead of the standard math of current_price * 1.20.
2. Division works just fine in the template editor by using the default division sign of "/", so I've confirmed that the code is correct (not that it should be that difficult considering it is just a simple "current_price / 2") but this integration is interpreting it completely different.

**Comment by Hellowlol** [comment]
Please remember that the template adds additional costs!

example current_price = 2 with you code the price is now 3

**Comment by Birdman86** [comment]
So if I want to deduct 50% off of the current_price, how would I achieve that?

**Comment by Hellowlol** [comment]
Try. {{current_price * (-0.5)}}

**Comment by Birdman86** [comment]
Yeah, I solved it last night by doing a subtraction of the current_price to negate the original value and then build it up from there.

Got the desired results with this:

{{ - current_price + ( (current_price + 0.0789) / 2 ) * 1.25 + 0.628 | float}}
