### ISSUE TITLE
 integration submits energy tariff with one hour delay

### ISSUE THREAD

**Issue by andiukas** [custom-components/nordpool#334]
Hello, integration submits energy tariff with one hour delay. Should have submitted the rate between 14 and 15
but submitted between 13 and 14 

![Screenshot 2023-07-04 145840](https://github.com/custom-components/nordpool/assets/44068098/184abb2b-b9e5-43b5-a4a9-1879b66ac83c)
![Screenshot 2023-07-04 145922](https://github.com/custom-components/nordpool/assets/44068098/5fe42650-cf60-4545-8adc-779f9dc9b3a7)
![Screenshot 2023-07-04 145908](https://github.com/custom-components/nordpool/assets/44068098/4d51d68a-6d5e-4486-ae72-d93cc3da0e2c)

![Screenshot 2023-07-04 150739](https://github.com/custom-components/nordpool/assets/44068098/39db60d9-8035-422b-b60d-9eceb63a2e2d)
![Screenshot 2023-07-04 150704](https://github.com/custom-components/nordpool/assets/44068098/5da970be-858b-4d68-a15c-9e0ef00265b9)

**Comment by Hellowlol** [comment]
Hi,

Thanks for using the integration. The prices should be correct. If you want to compare the prices in between the integration and the nordpool website, please account for the different timezones. Their api and their website displays the price in CET time.
