### ISSUE TITLE
VAT calculation is wrong in documentation

### ISSUE THREAD

**Issue by liviooo** [custom-components/nordpool#340]
Documentation says: 
Add 19 % VAT of the current hour's price
{{ (current_price * 0.19) | float }}

19% VAT should be calculated as follows:
{{ (current_price * 1.19) | float }}

**Comment by Newspaperman57** [comment]
The referenced part of the [documentation](https://github.com/custom-components/nordpool#additional-costs) also explains how the `additional_costs`-field works, and that the value calculated is added to `current_price`.
Hypothetically, if `current_price` is 1 and you want it to report prices including VAT, `additional_costs` should return 0.19 cents to make the reported total cost equal to 1.19

**Comment by Hellowlol** [comment]
Documentation is correct, closing
