### ISSUE TITLE
Combine raw_today and raw_tomorrow

### ISSUE THREAD

**Issue by RenfoJu1** [custom-components/nordpool#342]
In order to display prices of today and tomorrow in one graph, you typically have to combine the 2. This is possible, but tedious. 

Nicer implementation would be to always have the last known 48 hours with their start & end times. This would be updated once a day (when tomorrow_valid becomes true).

**Comment by Hellowlol** [comment]
This is out of scope, im sure you are able to create template sensor that solves this issue for you.
