### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by oveeliegmailcom** [custom-components/nordpool#343]
I realized i had no data medio June 2023, but had no time searching for the reason at the time.

Now I used some time searching and.
  - removed the in integration
  - rebooted, and make shore no keys inn the logs.... 
  - reinstaled the integration and connected a single sensor, and got no data.
  

  
Today I set upp a new Linux, docker and run Ha 2023.9.1 clean docker installation whit clean docker disk.
  - added the custom integration, an added NOK and "tromsø" (and norhing else)
 
LOGS:

Log details (ERROR)
Logger: homeassistant.components.sensor
Source: custom_components/nordpool/aio_price.py:145
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 4:04:03 PM (2 occurrences)
Last logged: 4:04:03 PM

Error adding entities for domain sensor with platform nordpool
Error while setting up nordpool platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1001, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/nordpool/sensor.py", line 518, in async_added_to_hass
    await self.handle_new_hr()
  File "/config/custom_components/nordpool/sensor.py", line 480, in handle_new_hr
    today = await self._api.today(self._area, self._currency)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/__init__.py", line 113, in today
    return await self._someday(area, currency, "today")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/__init__.py", line 99, in _someday
    await self.update_today()
  File "/config/custom_components/nordpool/__init__.py", line 80, in update_today
    await self._update("today")
  File "/config/custom_components/nordpool/__init__.py", line 73, in _update
    data = await spot.hourly(end_date=dt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/aio_price.py", line 239, in hourly
    return await self.fetch(self.HOURLY, end_date, areas)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/aio_price.py", line 233, in fetch
    return join_result_for_correct_time(raw, end_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/aio_price.py", line 145, in join_result_for_correct_time
    raise InvalidValueException()
custom_components.nordpool.aio_price.InvalidValueException 
 
 
except an Mill integration, no values changed from then std. config from first startup!

<html>
<body>
<div class="mdc-dialog__container" style="display: flex; flex-direction: row; align-items: var(--vertical-align-dialog,center); justify-content: space-around; box-sizing: border-box; height: 894px; transform: none; opacity: 1; pointer-events: none; color: rgb(33, 33, 33); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="mdc-dialog__surface" style="box-shadow: var(--mdc-dialog-box-shadow,0px 11px 15px -7px rgba(0,0,0,.2),0px 24px 38px 3px rgba(0,0,0,.14),0px 9px 46px 8px rgba(0,0,0,.12)); position: var(--dialog-surface-position,relative); display: flex; flex-direction: column; flex-grow: 0; flex-shrink: 0; box-sizing: border-box; max-width: var(--mdc-dialog-max-width,560px); max-height: var(--mdc-dialog-max-height,calc(100% - 32px)); pointer-events: auto; overflow-y: auto; background-color: var(--mdc-theme-surface,#fff); border-radius: var(--ha-dialog-border-radius,28px); min-width: var(--mdc-dialog-min-width,280px); top: var(--dialog-surface-top); margin-top: var(--dialog-surface-margin-top); min-height: var(--mdc-dialog-min-height,auto);"><h2 id="title" class="mdc-dialog__title" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-headline6-font-family,var(--mdc-typography-font-family,Roboto,sans-serif)); font-size: var(--mdc-typography-headline6-font-size,1.25rem); line-height: var(--mdc-typography-headline6-line-height,2rem); font-weight: var(--mdc-typography-headline6-font-weight,500); letter-spacing: var(--mdc-typography-headline6-letter-spacing,.0125em); text-decoration: var(--mdc-typography-headline6-text-decoration,inherit); text-transform: var(--mdc-typography-headline6-text-transform,inherit); display: block; position: relative; flex-shrink: 0; box-sizing: border-box; margin: 0px; padding: 24px 24px 15px; color: var(--mdc-dialog-heading-ink-color,rgba(0,0,0,.87)); border-color: var(--mdc-dialog-scroll-divider-color,rgba(0,0,0,.12)); border-bottom-width: 1px; border-bottom-style: solid;"><div class="header_title" style="margin-right: 32px; margin-inline-end: 32px; margin-inline-start: initial; direction: var(--direction);">System information</div><ha-icon-button dialogaction="close" class="header_button" style="display: inline-block; outline: 0px; position: absolute; right: 16px; top: 14px; text-decoration: none; color: inherit; inset-inline-start: initial; inset-inline-end: 16px; direction: var(--direction);"><mwc-icon-button title="Close" style="display: inline-block; outline: 0px; --mdc-ripple-color: currentcolor; -webkit-tap-highlight-color: transparent; vertical-align: top; --mdc-theme-on-primary: currentColor; --mdc-theme-text-disabled-on-light: var(--disabled-text-color);"><button class="mdc-icon-button mdc-icon-button--display-flex" aria-label="Close" style="font-size: 24px; width: var(--mdc-icon-button-size,48px); height: var(--mdc-icon-button-size,48px); padding: calc((var(--mdc-icon-button-size,48px) - var(--mdc-icon-size,24px))/ 2); display: inline-flex; position: relative; box-sizing: border-box; border: none; outline: 0px; background-color: transparent; fill: currentcolor; color: inherit; text-decoration: none; cursor: pointer; user-select: none; z-index: 0; overflow: visible; align-items: center; justify-content: center; vertical-align: top;"><span><slot><ha-svg-icon style="display: block; align-items: center; justify-content: center; position: relative; vertical-align: middle; fill: currentcolor; width: var(--mdc-icon-size,24px); height: var(--mdc-icon-size,24px);"><svg preserveAspectRatio="xMidYMid meet" focusable="false" role="img" aria-hidden="true" viewBox="0 0 24 24"><g><path d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></g></svg></ha-svg-icon></slot></span></button></mwc-icon-button></ha-icon-button></h2><div id="content" class="mdc-dialog__content" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-body1-font-family,var(--mdc-typography-font-family,Roboto,sans-serif)); font-size: var(--mdc-typography-body1-font-size,1rem); line-height: var(--mdc-typography-body1-line-height,1.5rem); font-weight: var(--mdc-typography-body1-font-weight,400); letter-spacing: var(--mdc-typography-body1-letter-spacing,.03125em); text-decoration: var(--mdc-typography-body1-text-decoration,inherit); text-transform: var(--mdc-typography-body1-text-transform,inherit); flex-grow: 1; box-sizing: border-box; margin: 0px; overflow: auto; color: var(--mdc-dialog-content-ink-color,rgba(0,0,0,.6)); padding: var(--dialog-content-padding,24px); position: var(--dialog-content-position,relative);"><slot id="contentSlot" style="margin-top: 0px; margin-bottom: 0px;"><div><div>

Version | core-2023.9.1
-- | --
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
User | root
Virtual Environment | false
Python Version | 3.11.5
Operating System Family | Linux
Operating System Version | 6.6.0-0.rc0.20230908gita48fa7efaf11.10.fc40.x86_64
CPU Architecture | x86_64
Timezone | Europe/Oslo
Configuration Directory | /config

</div></div></slot></div><footer id="actions" class=" mdc-dialog__actions " style="display: flex; position: relative; flex-shrink: 0; flex-wrap: wrap; align-items: center; justify-content: var(--justify-action-buttons,flex-end); box-sizing: border-box; min-height: 52px; margin: 0px; padding: 12px 24px; border-top-width: 1px; border-top-style: solid; border-color: var(--mdc-dialog-scroll-divider-color,rgba(0,0,0,.12));"><span style="flex: var(--secondary-action-button-flex,unset);"><slot name="secondaryAction"></slot></span><span style="flex: var(--primary-action-button-flex,unset);"><slot name="primaryAction"><mwc-button slot="primaryAction" style="display: inline-flex; outline: 0px; -webkit-tap-highlight-color: transparent; vertical-align: top; margin-left: 8px; margin-right: 0px; max-width: 100%; text-align: right;"><button id="button" class="mdc-button   " aria-label="Copy" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-button-font-family,var(--mdc-typography-font-family,Roboto,sans-serif)); font-size: var(--mdc-typography-button-font-size,.875rem); line-height: inherit; font-weight: var(--mdc-typography-button-font-weight,500); letter-spacing: var(--mdc-typography-button-letter-spacing,.0892857143em); text-decoration: var(--mdc-typography-button-text-decoration,none); text-transform: var(--mdc-typography-button-text-transform,uppercase); position: relative; display: inline-flex; align-items: center; justify-content: center; box-sizing: border-box; min-width: 64px; border: none; outline: 0px; user-select: none; appearance: none; overflow: hidden; vertical-align: middle; background: 0px 0px; padding-top: 0px; padding-right: var(--mdc-button-horizontal-padding,8px); padding-bottom: 0px; padding-left: var(--mdc-button-horizontal-padding,8px); height: 36px; border-radius: var(--mdc-shape-small,4px); flex: 1 1 auto; color: var(--mdc-theme-primary,#6200ee);"><span class="leading-icon"><slot name="icon"></slot></span><span class="mdc-button__label" style="position: relative;">COPY</span><span class="slot-container   " style="display: inline-flex; align-items: center; justify-content: center;"><slot></slot></span><span class="trailing-icon"><slot name="trailingIcon"></slot></span></button></mwc-button></slot></span></footer></div></div><br class="Apple-interchange-newline">
</body>
</html>

Som neded info, pleas let me now!

Ove Lie

**Comment by Hellowlol** [comment]
Hi Ove,

Thanks for using the issue template. This error is mostly due to junk in the API response from Nordpool. The integration tries to evaluate all the errors and not just the code you are interested in. I have recently merged a PR that should fix this issue

**Comment by oveeliegmailcom** [comment]
Tested whit success!

Excellent "support" :-)

mvh Ove
