### ISSUE TITLE
Tibber charges

### ISSUE THREAD

**Issue by vlumikero** [custom-components/nordpool#348]
Sharing this little insight related to Tibber. I had to do a bit of research to get the right calculation for Tibber's extra charges incl VAT. The calculation for the total price is (current_price + 9.82)*1,25.

You can either close this issue or if suitable, update the docs.

**Comment by Hellowlol** [comment]
Im not really sure what you are referring to. The readme has five code examples for how to use the additional costs. If you want to add a additional one, please send a PR.
