### ISSUE TITLE
Requesting system price as one of the "countries"

### ISSUE THREAD

**Issue by jddonovan** [custom-components/nordpool#363]
In my contract I'm paying for the difference between the Nordpool country specific price and the so called system price. So the base cost is fixed to, let's say 10 cents per kwh, and I pay extra or I get a discount if the country specific price is above or below the system price.

Getting the final price I pay would be easy if the add-on would provide the system price by default. Now my workaround would be to get values for multiple countries and calculate the average for those to get the "system price", which is inaccurate and inefficient.

All Nordpool services seem to offer system price "SYS" just like any other countries' data, so I would expect the API to provide the information too.

Thanks!

**Comment by catshapednoodles** [comment]
Isn't this already supported? 'SYS' seems to be one of the regions in the code, so you should be able to use it: https://github.com/custom-components/nordpool/blob/master/custom_components/nordpool/sensor.py#L52C41-L52C41

**Comment by jddonovan** [comment]
You're right! And I did test it before making this request, added it to the configuration, re-loaded configuration and rebooted. I think I even waited for an hour that it would appear (for next update), and didn't.

But lo and behold, I have it in my sensors now with the configuration I did days ago.

Thank you @catshapednoodles for going through the code!
