### ISSUE TITLE
Nordpool Lovelace card?

### ISSUE THREAD

**Issue by Tom-ahawk** [custom-components/nordpool#37]
The Nordpool sensor has attributes for today and tomorrow el- price. Displaying these prices over the 48 hours period, in a graph would be a beneficial card.

Any chance someone have the knowledge to make a card like this?

![image](https://user-images.githubusercontent.com/35527507/83942475-e63efa80-a7f3-11ea-9e80-a34650fc7b00.png)

**Comment by Hellowlol** [comment]
I would love to have that. I dont know enough js to make this :(
