### ISSUE TITLE
Strange negative character

### ISSUE THREAD

**Issue by Anders57S** [custom-components/nordpool#370]
If I cut the price data from the attribute and pastes into Excel I get a odd character for negative values.
It is a long minus character ( − ) instead of the correct one ( - ). 
Is it possible to change to a traditional minus?

VERSION_STORAGE = "6"
STORENAME = "hacs"

Home Assistant Core 2023.12.4

**Comment by Hellowlol** [comment]
I don’t control how it looks. It’s just negative numbers. The rest is defined by ha ui

**Comment by Anders57S** [comment]
Oki, then I know

thanks for replying.
