### ISSUE TITLE
VAT configuration seems to not working

### ISSUE THREAD

**Issue by karilabermo** [custom-components/nordpool#378]
Include VAT | no | Default: true Add Value Added Taxes (VAT) or not.
I assume the the following settings will show a price without VAT
Include VAT : false
And 
Include VAT : true
Will show prices with VAT, if so this seems not to work for the SE3 are in sweden what i can see.
Best regard 
Kari

**Comment by zanoii** [comment]
Agreed. The VAT setting does not make a difference. Tested configuration both through UI and YAML, for SE2. Prices are always without VAT. 

I tried hardcoding VAT in sensor.py to find the issue, but to no avail.

**Comment by Hellowlol** [comment]
The code for this is really simple. Please create two new sensors one with and one without. Leave additional costs blank

**Comment by zanoii** [comment]
> The code for this is really simple. Please create two new sensors one with and one without. Leave additional costs blank

That is not a solution. I already have two sensors, one "base price" and one including all additional costs (All-in-one). Neither show VAT even though the additional sensor have the VAT checkbox checked.

I can use the base price sensor to calculate the VAT for the AIO sensor, but that is a hacky workaround at best, and not a solution to what seems like a bug.

**Comment by Hellowlol** [comment]
Closing as the issue template has not been used. The code here is really simple, and has worked out of the box for a really long time.
