### ISSUE TITLE
A reliable way of triggering automations when Nordpool price period changes

### ISSUE THREAD

**Issue by koopee** [custom-components/nordpool#379]
**Use case**
I have an automation where I select cheapest prices to a list. When price period changes, I check if the current price is in the cheap price list then turn on a switch and remove the "used" price from the list. Else the switch is turned off.

**Problem**
I use nordpool change as trigger, which does not work, because nordpool changes are not predictable. I have noticed Nordpool triggers a change when new data is retrieved from the data provider and an additional trigger is generated when the day changes. I have failed to find a reliable way of filtering these changes away and only trigger when price period changes. Trigger for current price is unreliable too, because there would be no trigger if the price is same for several hours in a row.

**Solution**
I suggest adding a timestamp attribute to Nordpool, that is updated when price period changes from one to another. It would then be nice and predictable to trigger other automations according to this variable. And it would work right away when quarterly rates are introduced.

**Alternative solution**
I could make a trigger that would fire my automation every hour change. But it would need readjusting when the price period changes to 15 minutes. And also I'm fearing some random edge cases, where my automation would actually fire before Nordpool sensor updates its price and I would get outdated data.

**Comment by Hellowlol** [comment]
Just use the state change. 

The integration uses self._attr_force_update = True

meaning if will force a state change regardless if the value is identical

**Comment by yozik04** [comment]
I use pyscript custom component. I have a numeric sensor which controls amount of hours I want to heat the house. The triggered function runs every 10 minutes. It calculates lowest x prices and checks if current hour is included in this lowest x prices array. Depending on that it turns on/off climate sensor that controls if heating should be turned on or off.

**Comment by koopee** [comment]
> I use pyscript custom component. I have a numeric sensor which controls amount of hours I want to heat the house. The triggered function runs every 10 minutes. It calculates lowest x prices and checks if current hour is included in this lowest x prices array. Depending on that it turns on/off climate sensor that controls if heating should be turned on or off.

This works almost all times. There are edge cases, though. If heating is wanted for 2 cheapest hours and the price array is like [10, 10,10,0], then the heater is on for all four hours with this simple approach... I intend to use this to charge EV, so practically in this scenario batttery would become full almost certainly from the first three most expensive allowed hours and the cheapest one in the end would have little use.

Not the most common scenario, sure, but it would be nice to take this situation into account as well.

**Comment by yozik04** [comment]
No, it works correctly all the time =). Otherwise, that would be a bug in algorithm.

Here is the code:
```python3
import datetime
import zoneinfo

def n_lowest(n, candidates: dict):
    candidates_clean = filter(lambda x: x["value"] is not None, candidates)
    return sorted(candidates_clean, key=lambda x: x["value"])[:n]

def find_price(dt, candidates):
    for x in candidates:
        if x["start"] <= dt < x["end"]:
            return x

def filter_today(candidates):
    return filter(lambda x: x["start"].day == datetime.date.today().day, candidates)


@service
def update_heating(entity_id):
    current_hour = datetime.datetime.now(tz=zoneinfo.ZoneInfo(key='Europe/Tallinn'))

    candidates = sensor.nordpool_kwh_ee_eur_3_095_02.raw_today + sensor.nordpool_kwh_ee_eur_3_095_02.raw_tomorrow
    hours_to_heat = int(float(input_number.hours_to_heat))
    today_candidates = filter_today(candidates)

    cheap_hours = n_lowest(hours_to_heat, today_candidates)
    should_heat = find_price(current_hour, cheap_hours) is not None
    if should_heat:
        climate.turn_on(entity_id=entity_id)
    else:
        climate.turn_off(entity_id=entity_id)
```

**Comment by yozik04** [comment]
I have reread your message, and you are correct. The last hour of charging consumes much less power as well.

**Comment by yozik04** [comment]
Split hours into more slots. Per 5/10 minutes. If you know exactly how long you need to charge, then you can calculate how many slots you need.

**Comment by koopee** [comment]
> Split hours into more slots. Per 5/10 minutes. If you know exactly how long you need to charge, then you can calculate how many slots you need.

I'm afraid I don't quite get what are you aiming at by "splitting hours". For me, it is quite enough to tell something "charge 2 cheapest hours"

My original problem is, that when the cheap price is marked as "used", an extra trigger from Nordpool integration in this period will stop charge as the price is marked as "used" when starting the period. This kind of situation will happen if the price is cheap at midnight or the moment when new day data is fetched.

Prices need to be marked as used. Another scenario when this would be needed is, if the prices are all the same. Like 0,0,0,0,0,0. Now the two cheapest hours are both 0. All zero prices are charged, which I propably do not wan't. This too is not quite common situation, I agree, but robust system should take this kind of situations also into account.

**Comment by koopee** [comment]
Please reopen this. I made a test case, where I made a test template sensor which is set to trigger when nordpool changes and then log the trigger time. Last night there were two consecutive identical prices and the second one did not create trigger for my automation, so no indication that the price period had changed.

I use this as my trigger. If I remove "from: null", it also fires on housekeeping updates like when new data becomes available.
  - trigger:
      - platform: state
        id: "interval_change"
        entity_id:
          - sensor.nordpool_kwh_fi_eur_3_10_024
        from: null
