### ISSUE TITLE
High prices not supported?

### ISSUE THREAD

**Issue by matlimatli** [custom-components/nordpool#38]
In south Sweden the prices are currently very high. Tomorrow the price will be almost 200 öre/kWh. This seems to not be handled properly by the component. 
My prices for tomorrow (SE3) look like this:
```
tomorrow: 39.879, 35.354, 34.025, 33.052, 32.645, 35.644, 65.696, 89.779, , , , , , , , 81.164, 78.191, 84.767, 95.948, 88.174, 59.568, 52.926, 49.98, 42.916
unit_of_measurement: Öre/kWh
```

All prices above 100 appear to be discarded.

**Comment by Hellowlol** [comment]
Hi! Thanks for reporting the bug. Its a upstream issue. I have pushed a fix in https://github.com/custom-components/nordpool/commit/6740bcb86b4eff687c78528bd6e9e90ce4b104c4 and opened a PR with https://github.com/kipe/nordpool/pull/11 upstream. Update the integration! :)
