### ISSUE TITLE
VAT for Finland will increase from 0.24 to 0.255 starting  from 1.9.2024

### ISSUE THREAD

**Issue by lindsand** [custom-components/nordpool#389]
VAT for Finland will increase from 0.24 to 0.255 starting from 1.9.2024

https://www.vero.fi/en/businesses-and-corporations/taxes-and-charges/vat/rates-of-vat/new-vat-rate-from-1-september-2024--instructions-for-vat-reporting/

Hardcoded here:

https://github.com/custom-components/nordpool/blob/master/custom_components/nordpool/sensor.py

_REGIONS = {
    "DK1": ["DKK", "Denmark", 0.25],
    "DK2": ["DKK", "Denmark", 0.25],
    **"FI": ["EUR", "Finland", 0.24],**
    "EE": ["EUR", "Estonia", 0.22],
    "LT": ["EUR", "Lithuania", 0.21],
    "LV": ["EUR", "Latvia", 0.21],
    "Oslo": ["NOK", "Norway", 0.25],

**Comment by Hellowlol** [comment]
Hi,

Can you please send a PR for this change? If you can get it done today I can include it in the next release.

**Comment by vla89** [comment]
I created a PR for this #394.

**Comment by pistegif** [comment]
Note: this will cause new device/entity to be created (since the default naming contains the VAT).
When using the sensor in automations, remember to rename the new sensor to match.
