### ISSUE TITLE
Prices not loading

### ISSUE THREAD

**Issue by developerfromjokela** [custom-components/nordpool#412]
Hi.

Prices seem not to load, tried to access API manually, it seems to be down. 503 error. 
There was an article on nordpool site that they're deprecating some APIs, can this be the cause?

**Comment by corove** [comment]
I have the same issue. 
Not loading any API from Nordpool at all. Tried to set up new API connection, but still no response.

**Comment by ykii** [comment]
Same here, died this morning at 6am.

**Comment by developerfromjokela** [comment]
It's also causing major slowdowns in Home Assistant because of it. Restarts take >5 min.

**Comment by jarube** [comment]
yup, same here!

**Comment by Hellowlol** [comment]
Maybe they finally has pulled the plug for the old API  that we have been using. The new API seems to be a lot simpler to use, unfortunately, i dont have time update this integration for a couple of weeks. If you need another good alternative i can recommend: https://github.com/JaccoR/hass-entso-e

**Comment by developerfromjokela** [comment]
What's the new API? Can you link it here? @Hellowlol

**Comment by Hellowlol** [comment]
Here is an example: https://dataportal-api.nordpoolgroup.com/api/DayAheadPrices?date=2024-10-08&market=DayAhead&deliveryArea=AT,BE,FR,GER,NL,PL,NO1,SYS&currency=NOK

https://data.nordpoolgroup.com/auction/day-ahead/prices?deliveryDate=latest&currency=NOK&aggregation=Hourly&deliveryAreas=AT,BE,FR,GER,NL,PL,NO1,SYS

**Comment by developerfromjokela** [comment]
I'll try to implement it, thanks!

**Comment by pistegif** [comment]
The prices seem to load again. At some point after 14:00 when the tomorrow download triggered, the tomorrow prices appeared, and then HA restart loaded today's prices too.
But since it is still in the dark how long the old API will hold, I'd be happy to throw few sponsor bucks to @developerfromjokela if you have the time/will to migrate to new API :)

**Comment by developerfromjokela** [comment]
> The prices seem to load again. At some point after 14:00 when the tomorrow download triggered, the tomorrow prices appeared, and then HA restart loaded today's prices too.
> 
> But since it is still in the dark how long the old API will hold, I'd be happy to throw few sponsor bucks to @developerfromjokela if you have the time/will to migrate to new API :)

Just checked, no prices on my instance. Probably better to migrate

**Comment by lightheaded** [comment]
My prices are back as well after a restart. They were down from around 7am UTC, and came back just now after I restarted after installing the ENTSO-E integration 😅 there's some irony for you

**Comment by jannesaarinen** [comment]
For me the prices reapperead after I reloaded the integration (didn't have to restart homeassistant).

I'm also happy to offer you coffee @developerfromjokela , if you have the time to migrate to new API. I can bring the coffee to you in person, if you live really in Jokela / Tuusula, as I'm based also in Tuusula. :)

**Comment by developerfromjokela** [comment]
If some people want to test the new API, copy over files modified in the commit and restart HA 😉

**Comment by developerfromjokela** [comment]
Significant performance improvement was a positive side-effect of this migration 😄

**Comment by karlis99** [comment]
> If some people want to test the new API, copy over files modified in the commit and restart HA 😉

Thanks, works for me to!

**Comment by dana-se** [comment]
> If some people want to test the new API, copy over files modified in the commit and restart HA 😉

Works for me with SE4, and the Integration startup time went from five to under one second 😄
Is there something special you want us to test?

Thanks

**Comment by jvuotila** [comment]
> If some people want to test the new API, copy over files modified in the commit and restart HA 😉

I also replaced the changed files and omg how fast integrations starts after HA restart. Seems that old version have been hanging the whole startup quite a much!

**Comment by developerfromjokela** [comment]
> > If some people want to test the new API, copy over files modified in the commit and restart HA 😉
> 
> 
> 
> Works for me with SE4, and the Integration startup time went from five to under one second 😄
> 
> Is there something special you want us to test?
> 
> 
> 
> Thanks

Just to make sure everything works as it should and no new issues come up. Nothing specific :)

**Comment by developerfromjokela** [comment]
Now that tomorrow's prices are available, check your raw_today attribute. Is it veery long? Or is it only on my home assistant?

**Comment by dana-se** [comment]
Everything is right here, but didn't merge the latest changes https://github.com/custom-components/nordpool/pull/413/commits/a1332b333ee89b5eef2c0c727a3e327024a40bd4

**Comment by developerfromjokela** [comment]
> Everything is right here, but didn't merge the latest changes https://github.com/custom-components/nordpool/pull/413/commits/a1332b333ee89b5eef2c0c727a3e327024a40bd4

Ok. I had that issue yesterday on first commit, curious if anybody else has this also.

**Comment by jvuotila** [comment]
> Now that tomorrow's prices are available, check your raw_today attribute. Is it veery long? Or is it only on my home assistant?

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.42, 0.61, 1.24, 1.4, 1.43, 1.41, 1.18, 1.0, 0.91, 0.95, 1.02, 1.12, 1.19, 1.09, 0.82, 0.19, 0.0, 0.0]

**Comment by developerfromjokela** [comment]
> > Now that tomorrow's prices are available, check your raw_today attribute. Is it veery long? Or is it only on my home assistant?
> 
> 
> 
> [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.42, 0.61, 1.24, 1.4, 1.43, 1.41, 1.18, 1.0, 0.91, 0.95, 1.02, 1.12, 1.19, 1.09, 0.82, 0.19, 0.0, 0.0]

I meant this: ![image](https://github.com/user-attachments/assets/5f417e31-222c-4dfa-955c-0baebdc41a08)

**Comment by jvuotila** [comment]
> I meant this, is it very very long:

Yes, I edit my reply. See above.

**Comment by developerfromjokela** [comment]
> > I meant this, is it very very long:
> 
> Yes, I edit my reply. See above.

On my HA it contained today's prices + 10x duplicate of tomorrow prices. Yours is normal.

**Comment by Teme-V** [comment]
Nordpool have sent following info:
"dear customer... "Please be aware that on Monday 14th October 2024 we will be closing our old market data pages, which until now have been hosted on nordpoolgroup.com. 

 

These legacy pages were replaced some time ago - Market Data is now available on our new Data Portal, which you can find here."

**Comment by developerfromjokela** [comment]
Ok, thanks for info.

I've implemented new data page API on my repository and working on getting
it merged

**Comment by oakmountainsweden** [comment]
Hi, I have this issue. What can I do to make it work again?

**Comment by jvuotila** [comment]
> Hi, I have this issue. What can I do to make it work again?

Just upgrade the integration.

**Comment by bilalhp** [comment]
What's the way to upgrade this integration without upgrading the HA?
