### ISSUE TITLE
Custom component version not matching to release 0.0.15

### ISSUE THREAD

**Issue by jannesaarinen** [custom-components/nordpool#418]
I think the custom component version was forgot to update to `0.0.15` as it's still `0.0.14` in the manifest and there fore also shown incorrectly in the HA integrations UI:
![image](https://github.com/user-attachments/assets/0ed9e412-98b3-4111-aba0-ced63f08e81f)

https://github.com/custom-components/nordpool/blob/d81756f4a4fa2a60d4c05d2d81be6350825f8731/custom_components/nordpool/manifest.json#L19

**Comment by lindsand** [comment]
True, I just downloaded 0.0.15 to fix #417 but version is still shown as 0.0.14

**Comment by DariusVaitkus** [comment]
I just installed. Restarted. And version 0.0.15 shown. Renamed to my old entity name and everything is working fine.

**Comment by prilly-dev** [comment]
manifest.json is indeed showing 0.0.14, should be updated to 0.0.15

**Comment by oleg-d** [comment]
Fixed by https://github.com/custom-components/nordpool/pull/424

**Comment by Hellowlol** [comment]
Yeah, sorry, by bad. It fixed
