### ISSUE TITLE
German prices do no longer match tibber prices as they had before 0.0.15 

### ISSUE THREAD

**Issue by typxxi** [custom-components/nordpool#422]
## Version of the custom_component
0.0.15 
I have downloaded that several times and rebooted HA afterwards, but if I open the integration "nordpool" I get this picture with a 0.0.14, no matter what. ctrl + f5 should update the browser but it stays at 0.0.14 
![image](https://github.com/user-attachments/assets/263bb227-671b-4e66-89a1-52f7125e1b99)

If I check Hacs it says latest release 3 days ago, if I click download again it asks if I wanna download 0.0.15 which I agree and then will be asked for labels and so on

But I am pretty sure that the new regions from Norway and for Germany have been released with 0.0.15 and that is what I get if I start adding a new configuration: a new choice via UI where I can only choose GER cause 'DE-LU' is no longer available
Hence 0.0.15 

## Homeassistant version
![image](https://github.com/user-attachments/assets/684394f9-6ac8-411b-afd8-0fec068f74a9)

## Configuration
sensors.yaml

```
- platform: nordpool
  region: "GER" # Country/region to get the energy prices for - "DE-LU" outdated since API changes around 14th of oct. 2024 

  currency: "EUR"
  VAT: false
  precision: 3
  price_in_cents: true 
  price_type: kWh # price displayed for kWh

  # Percentage of average price to set the low price attribute
  low_price_cutoff: 0.95

  additional_costs: "{{ (0.2027 + (current_price * 0.19)) | float }}"
```

## Describe the bug
prices are way off from tibber app prices and tiber HA integration prices which match each other.
Tibber prices are these
![image](https://github.com/user-attachments/assets/ce95493f-f0bb-4d39-950d-ce5e37e314e4)

Nordpool prices based on the new region "GER" instead of "DE-LU" which was no longer working (this screenshot has been taken in the following hour)
![image](https://github.com/user-attachments/assets/3f44dacf-1805-4df9-95be-0fc83487d5cc)

For tomorrow evening we have a 
40,7 Cent by tibber integration
46,7 cent by nordpool integraion and modifyer line 
6 cent difference compared to 0,01 Cent we have had before with the nordpool for "DE-LU" and with the same calculation
`  additional_costs: "{{ (0.2027 + (current_price * 0.19)) | float }}"`
And 6 cent is a weird figure. 

I have only one assumption that might cause trouble and that is the fact that the UI is now asking "incl. vat" or had this option activated and that this can cause a "doubled VAT" even though 19% on top of 40,7 cent would not match to 46,7 cause that would be 48,43 or 2 cents too much. 

Finally I changed the additional cost to 0% Vat in this formula
`  additional_costs: "{{ (0.2027 + (current_price * 0)) | float }}"`

leading to lower costs but still off by 40,7 (tibber max tomorrow) versus 42,5 cent nordpool with 0% Vat in the formula
![image](https://github.com/user-attachments/assets/6e6a0940-edb8-41a5-9e06-1adc99c0d990)

And after 3 days of tinkering and trying to get my previous matching results back (I mean nordpool figures met the tibber figures 5 out of 6 times and only 1 time a deviation of 0,01 cent) cause my energy management is relying on nordpool right now this was my final try.

## Debug log
```
all the screenshots above 
```

### UPDATE 18:10 
If I remove all the entities and sensors and then add it again then nothing of the changes made will appear in my sensors.yaml file. I have not found a single change.

```
- platform: nordpool
  region: "GER" # Country/region to get the energy prices for - "DE-LU" outdated since API changes around 14th of oct. 2024 

  currency: "EUR"
  VAT: true
  precision: 3
  price_in_cents: true 
  price_type: kWh # price displayed for kWh

  # Percentage of average price to set the low price attribute
  low_price_cutoff: 0.95

  additional_costs: "{{ (0.2027 + (current_price * 0.19)) | float }}"
```

**Comment by Hellowlol** [comment]
Hi,

Thanks for opening the bug report and providing details. How you are making a lot of assumptions including that the prices in tibber app is correct and that you have a template that gets it close to the tibber prices. 

We need to compare apples to apples. So you need to do the following.

1 add a new sensor using the ui, select mwh, no vat, zone ger, precision should be 4 and additional costs should be empty.

check the prices you get towards the prices on the nordpool website. It they are identical there is nothing we can do it fix this, if they are not plots the data from the sensor here.

**Comment by typxxi** [comment]
well,

I had checked the nordpool prices in summer several times and the differences were close to 0.

Meanwhile (in the past 2 hours) I found out more .
For example a part of documentation or history how this had all started in summer 2024 after the tibber integration had broken in spring 2024.

It all started with a website who had described how to do the integration and I guess I did it manually and added it in the sensors.yaml file 
And as usual I tend to note the source in such files on the top in a history like this 
###################################################################
#                                                                 #
#   NORDPOOL INTEGRATION                                          #
#   https://www.creatingsmarthome.com/index.php/2022/09/17/home-assistant-nord-pool-spot-prices-and-how-to-automate-devices-for-cheapest-hours/
#                                                                 #
###################################################################

So my explanation is that I started back then with that manual integration, I checked the tibber app prices versus those I got in the price chart based on the nordpool sensor.  

And after I had been working on the AIO Energy Management integration from the same website which relies on nordpool over the weekend I recogniced that the data were missing on monday noon. 

Not sure what happened next cause I spend some time for writing that issue and I guess did also install the HACs integration again. 

Therefore I am not sure which values were used, those I had put in using the dialog during configuration or those from my sensors.yaml file. 

Anyhow, meanwhile I have removed nordpool from hacs completely, rebooted, made another backup and reinstalled the nordpool integration again. 

Not sure , but I recogniced that the nordpool entity names changed when I had changed parameter cause my apex charts could no longer find the sensors. 

Right now using the dialog box incl. VAT and adding the tibber fees of 20,02 cent the prices are still way too high.
![image](https://github.com/user-attachments/assets/f5245f50-4a21-4210-bfb4-00530af2d936)

And now I will follow your recipe and create a new configuration without anything. 
Will be back soon

THANKS a LOT for your quick reply.

**Comment by typxxi** [comment]
Here is the result for the naked sensor 
![image](https://github.com/user-attachments/assets/460149d1-128a-494b-b706-896f8daa20d5)

my scale starts at 15 cent so way too small but the preview show the current price 11,8 Cent

But here is a screenshot of that sensor too
![image](https://github.com/user-attachments/assets/560d20e1-0923-4e35-8fda-9b14d9f5bb5e)

That matches the price I get from the entso-e platt form here even though not nordpool, but the fastest way for me to check.
![image](https://github.com/user-attachments/assets/ca264cd1-22a3-4ae3-897c-ea557cf7b32d)

And it matches the price tibber app shows me as the net price -  at least rounded 11,75 versus 11,8 cent

Next step ?

**Comment by typxxi** [comment]
Ok, I am doing the reverse calculation and will create more sensors to compare those results and write a guide for german users how to use nordpool to get the proper tibber price. 

Will take a bit more time.

**Comment by dana-se** [comment]
Look in sensor.py at line 56-57
    # Unsure about tax rate, correct if wrong
    "GER": ["EUR", "Germany", 0.23],

**Comment by typxxi** [comment]
### UPDATE 2: Tibber & Nordpool integration calculation for 17.10.2024 - 21:00

```
  30,800 cent Tibber App all incl. 
  / 1,19   
= 25,882 cent net
-  9,781 cent day ahead net price Nordpool & Entso-E / 9,8 cent tibber app
= 16,101 cent net fees for this price 
  + 19%
in the hour before it was 16,065 Cent, therefore I am using 16,8 cent from now on

additional costs (estimation) for german tibber with 16,08 cent should be
{{ ( (0.1608 * 1.19) + (current_price * 0.19) ) | float }} 

   9,781 cent net Nordpool & Entso-E / 9,8 Cent Tibber net
+ 16,08 cent net additional fees 
= 25,882 cent net
   x 1,19
= 30,800 cent gros
```

But my sensor is way off again with 33,4766
![image](https://github.com/user-attachments/assets/c4e15ba1-cbed-48ed-a823-d81ffe37bf88)

So far I have not changed the line that @dana-se had provided. 

I will now first try to build a new sensor without the vat option enabled and do all the stuff with this additional cost line

{{ ( (0.1608 * 1.19) + (current_price * 0.19) ) | float }}

```
1.19 is the factor for the additional costs incl. 19% vat 
+ vat for the day ahead kWh price 
+ day ahead price
= 30,8 cent tibber price (hopefully)

```
After that trial I will try to follow @dana-se advice but I am not the coding and python guy. I guess that sensor.py file is stored in the hacs folder under an integration nordpool integration folder.

**Comment by typxxi** [comment]
UPDATE 3: Tibber & Nordpool matching figures for 17.10.2024 - 21:00

For all those not familiar and maybe reading along afterwards: 
delete the latest device (incl. its entity/ies) first from inside the nordpoll integration page and then add a new one.

If you create the new one then choose
germany
euro
4 for rounding precision
1% or what you want to be considered cheap 
VAT MUST BE DEACTIVATED at least for 0.0.15 users due to the wrong 23% VAT in the code (might have already changed)
energy scale kWh

AND THEN BE VERY AWARE THAT (even if you had chosen cents above) 
you **have to use € for additional costs** in the following line
      =======================

`{{ ( (0.1608 * 1.19) + (current_price * 0.19) ) | float }}`
Do not use 16.08 there for the tibber net fees 

![image](https://github.com/user-attachments/assets/314adfaf-f0e4-405c-9374-83048621d7cb)

**Comment by typxxi** [comment]
### And after all the GUIDE for at least all german tibber users to find out your local tibber fees


1. Open the tibber app, 
2. click on the current price button
3. then select today
4. now move the cursor to a certain time and watch the exact price.

Do not use 31 cent which tibber is showing you in big fontsize.
Use the smaller with the 1/10 precision in my case here 
```
 30,800 cent Tibber App all incl. 
```

From now on you have to do a few, but very important steps with a huge risk to create bugs by not being fully aware of all the steps or simply by too much copy and paste actions. 


5. Check the Entso E net dayahead price but make sure to take the green graph which is showing the hourly prices not the quarter hourly prices from [here](https://newtransparency.entsoe.eu/market/energyPrices?appState=%7B%22sa%22%3A%5B%22BZN%7C10Y1001A1001A82H%22%5D%2C%22st%22%3A%22BZN%22%2C%22mm%22%3Atrue%2C%22ma%22%3Afalse%2C%22sp%22%3A%22HALF%22%2C%22dt%22%3A%22CHART%22%2C%22df%22%3A%222024-10-17%22%2C%22tz%22%3A%22CET%22%7D) 

![image](https://github.com/user-attachments/assets/63c2a9ea-c8f2-414c-8503-4bdbeda0f4bd)

Or you first have to add another nordpool plus sensor but without VAT and without additional costs to get the pure and net day ahead price

6. And here the calculation sheme as a shortcut for calculating the tibber fees (gross not net to make it easier)

```
  tibber app price 
- day ahead price (which is net)
- 19% x day ahead price = vat on day ahead price
------------------------------------------------------- 
= tibber fees incl. VAT
```

```
  30,800 cent Tibber App all incl. 
-  9,781 cent day ahead net price Nordpool & Entso-E / 9,8 cent tibber app
-  1.858 cent 19% VAT for the day ahead price 
------------------------------------------------------- 
= 19,161 cent tibber fees incl. VAT
```

7. Here you can use this "kind" of line for the calculation of the additional costs 

`{{ ( 0.19161 + current_price * 0.19 ) | float }}`

### `Final reminder: use your brain and check what you are doing`

If you copy the **19,161** figure from above and paste that into this additional cost line

**`{{ ( 0.19161 + current_price * 0.19 ) | float }}`** 

then you will not be able to create the sensor cause you will get an error message you will not understand instantly.

#1 if you paste the figure from a german calculator then you insert a **19,161** into the forumula which HA and the integration can and will not accept cause they can not deal with "," and "." when a "." is mandatory

#2 as I had warned you before you will get a wrong result cause you have copied a cent figure were the integration is expecting to get a € figure, which means that 19.161 will be 100 times too big where 0.19161 is right.

So do not paste 19,161 from the german calculator and use "0.19161" in that formular. 

And then the prices of the sensor should match those in the tibber app and HA tibber integration price sensor

`{{ ( 0.19161 + current_price * 0.19 ) | float }}` 

Took me 3 or 4 days to get behind all the bits and pieces but if you follow these steps it is pretty easy and foremost reliable cause now you should understand what even tibber employees are not explaining. 

Good luck & savings.

**Comment by typxxi** [comment]
And finally here is the fix @dana-se had mentioned for german users running 0.0.15 

![image](https://github.com/user-attachments/assets/0b1637de-81c2-4a82-9981-0e98357d905f)

I guess it will be fixed in 0.0.16 or the upcoming beta versions.

**Comment by typxxi** [comment]
FINAL REMARK FOR ALL GERMAN TIBBER USERS AND REGARDLESS IF THEY USE 0.0.15 or beyond: 

if you edit and change the VAT in the file sensor.py (in homeassistant/custom/nordpool folder)
( line 57: "GER": ["EUR", "Germany", 0.23], by replacing 23 with 19)
and then configure again you will create a new sensor. Each VAT figure will create a new VAT sensor so be aware to check other scripts and what not if you are using any "_23" sensor. Your proper sensors should end with _19 afaik.

**Comment by Hellowlol** [comment]
So nice to see that you found a solution. The readme clearly states that you can’t use cents in additional cost, we even have example how it could be used. Any update to the readme is much appreciated :)

To update the German vat just edit the mentioned line to the correct vat and send a pr. Thanks for creating a detailed write up for how to find the correct additional costs for tibber users
