### ISSUE TITLE
Integrations broken after v0.15

### ISSUE THREAD

**Issue by rinowit** [custom-components/nordpool#423]
I have had this integration for many years. Now sadly my integrations that depends of the past model of the sensor date is broken. 

My question is: Why is the structure changed? This is ofcourse not a security issue that is the reason. It's ok with tha name change from Oslo to NO1. But why the structure? It takes down all the integrations I had that was dependent of the maked prices?

I have been using HA for at least 10 years and more. And some times I have been wondering if I have to change a system to a more robust system that don't give surprises like this.

The Nordpool integration has been a wonderfull add-on.

Thank you:)

**Comment by dana-se** [comment]
Take a look here
https://github.com/custom-components/nordpool/issues/420#issuecomment-2421497326

**Comment by dana-se** [comment]
I think that the easiest way for you, is to rename both the Name and Entity ID to the old ones that worked.
![image](https://github.com/user-attachments/assets/7f5944c8-d19b-4516-90c5-8660f0d79b19)

**Comment by dana-se** [comment]
This is because 0.15 make a new sensor with  new name and Identity ID, that you must rename to the old names.
Your plugins are looking for the old Identity ID.

**Comment by rinowit** [comment]
I have already tried renaming it to the previous configuration, but the other plugin uses the old region names hardcoded. I attempted to modify that plugin, but it can't read the new sensor data.

I’ve been trying to understand how the low price percentage works. If I can stop using the other plugin and solely rely on this one, it might prevent future issues. If I want to use the top 30% of the lowest prices of the day, what value should I set to achieve that?

Thanks for helping:)

**Comment by dana-se** [comment]
@rinowit  If you look at the entities of your new nordpool sensor, has the Identity ID the same name as the hardcoded plugin use?

**Comment by rinowit** [comment]
No, it has the name sensor.nordpool. Not the strang numeric ending. I use this name everywhere in the integration:)

**Comment by dana-se** [comment]
But you sad  "the other plugin uses the old region names hardcoded" 
Then you must rename your sensor.nordpool to that hardcoded name.

**Comment by rinowit** [comment]
I used Oslo and not the new NO1. There are probably other differences to. As I have tryed to change the system files for the other plugin to match NO1

**Comment by thr0t** [comment]
After several days of trying different solutions I was not able to get it working in my container HASS. Seems like all the HASS updates have not gone smoothly as there are a lot of system logic changes and some settings just started conflicting. So the solution that worked for me was fresh HASS install. It is a pain (the esphome needs additional effort, not related to this topic) but at least it started working.

**Comment by rinowit** [comment]
Closing case

**Comment by dana-se** [comment]
> Closing case

Did you solve the problem?

**Comment by rinowit** [comment]
No, i will have to fix it oher ways. 

Nordpool as a plugin works. It’s the plugins that is dependent of nordpool that don’t work. 

In the mean time I will try to figure out how I can use the nordpool integration to fint the lowest prices of the day. I would like to use the cheapes hours to controll the most power intense devices. 

Thanks for helping:)

**Comment by dana-se** [comment]
Herhaps this: https://www.creatingsmarthome.com/?p=1620

**Comment by thr0t** [comment]
Maybe this will help you with the cheapest hours:
https://github.com/kotope/ha_nordpool_cheapest_hours
