### ISSUE TITLE
VAT rate 

### ISSUE THREAD

**Issue by vulgarsonic** [custom-components/nordpool#43]
Hello!
Running this via HACS and if you select "Include VAT" code always assumes 25% VAT.
In Finland we have 24% for example.

**Comment by vulgarsonic** [comment]
Thank´s for the answer!
But i'm i  FInland and i get values with 25% VAT.
How does it determine location?

**Comment by Hellowlol** [comment]
https://github.com/custom-components/nordpool/blob/master/custom_components/nordpool/sensor.py#L134 It uses the area to set the vat

**Comment by vulgarsonic** [comment]
Sorry, that i don´t follow...
What area, how is it determined?

I'm om Åland islands, pretty much right in between Sweden And Finland. 
We do belong to Finland though so 24% VAT is the correct value for us.
What can i do to correct it?

**Comment by Hellowlol** [comment]
Can you take a picture of your nordpool settings and the name of the enitity_id? You cant. It should already be correct.

**Comment by vulgarsonic** [comment]
Aha!
Then i think i understand, my area is SE3 since we import our electricity from swedish suppliers. 
But as we belog to finland our vat is 24%,
Is there any possible workaround?

**Comment by Hellowlol** [comment]
Just create a template sensor that corrects it.
