### ISSUE TITLE
Error during setup of component nordpool

### ISSUE THREAD

**Issue by Freezydk** [custom-components/nordpool#435]
I'm a bit of a Rookie here, so bare with me. Somehow the Noordpool component can't be started after the version has been updated to 0.0.15. I tried to downgrade to 0.0.14 but no data was "loaded". Anyone know how to fix this. I'm running HACS on a HA installed on Docker (running on a NAS).

Add your logs here.

Logger: homeassistant.setup
Kilde: setup.py:398
Første forekomst: 17.54.28 (1 forekomster)
Senest logget: 17.54.28

Error during setup of component nordpool
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 398, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/nordpool/__init__.py", line 197, in async_setup
    return await _dry_setup(hass, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/__init__.py", line 179, in _dry_setup
    tz=await dt_utils.async_get_time_zone("Europe/Stockholm"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.util.dt' has no attribute 'async_get_time_zone'

**Comment by Hellowlol** [comment]
You are using a to old Home Assistant version. Please upgrade.
