### ISSUE TITLE
Issue with await lookup timezone

### ISSUE THREAD

**Issue by wittich** [custom-components/nordpool#437]
## Version of the custom_component
Nordpool version 0.0.15

## Homeassistant version
2024.2.4

## Configuration

```yaml
sensor:
  - platform: nordpool
    region: "GER"
    currency: "EUR"
    VAT: true
    precision: 3
    low_price_cutoff: 0.95
    price_in_cents: true
    price_type: "kWh"
    additional_costs: "{{0.0|float}}"
```

## Describe the bug
The Nordpool integration fails to set up due to an error with the `async_get_time_zone` function. The error message indicates that `async_get_time_zone` is not a valid attribute in `homeassistant.util.dt`. Home Assistant version 2024.2.4 may have removed or replaced this function, leading to incompatibility with Nordpool version 0.0.15.

Error Message:
```
AttributeError: module 'homeassistant.util.dt' has no attribute 'async_get_time_zone'
```

Replacing `async_get_time_zone` with `get_time_zone` resolves the issue, suggesting that `async_get_time_zone` is no longer supported in the latest Home Assistant release. 

## Debug log

```text
2024-11-02 00:00:37.438 DEBUG (MainThread) [custom_components.nordpool] Added nordpool to hass.data
2024-11-02 00:00:37.438 ERROR (MainThread) [homeassistant.setup] Error during setup of component nordpool
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 333, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/nordpool/__init__.py", line 197, in async_setup
    return await _dry_setup(hass, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/__init__.py", line 179, in _dry_setup
    tz=await dt_utils.async_get_time_zone("Europe/Stockholm"),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.util.dt' has no attribute 'async_get_time_zone'
```

**Comment by wittich** [comment]
See https://github.com/custom-components/nordpool/commit/390f0ada

**Comment by Hellowlol** [comment]
Upgrade your ha
