### ISSUE TITLE
problem adding integration using GUI in "Devices & Services"

### ISSUE THREAD

**Issue by bp-ouhaha** [custom-components/nordpool#441]
I installed today Nordpool 0.0.15 (latest) on Home-Assitant version:
Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2
Frontend 20241002.4

After restart, I try to add the Integration in "Devices & Services" using the GUI, then I get this message:
Config flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by tomgnilsen** [comment]
I face the same issue. Added the HACS today and installed NordPool. Looks like a problem with the change of the different price zones in Norway that was renamed. 

Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2
Frontend 20241002.4

**Comment by makuke** [comment]
Sorry for dumb question but is this hack can be performed via Wifi to SD card..I cannot find correct menu to access to subfolder.

**Comment by bp-ouhaha** [comment]
it seems to be working now. I guess due to updates (0.16 or newer HA version).

I'm now on these HA versions:
 Core 2024.11.0
Supervisor 2024.11.2
Operating System 13.2
Frontend 20241106.0

**Comment by bp-ouhaha** [comment]
Thanks anyway!
