### ISSUE TITLE
Future prices incorrectly calculated when using template

### ISSUE THREAD

**Issue by zanoii** [custom-components/nordpool#442]
## Version of the custom_component
Downloaded and updated to release 0.0.15 but manifest.json says it's 0.0.14.

## Homeassistant version
2024.10.4

## Configuration
UI config:
SE2
no VAT
Precision 4
Template: {{states('sensor.endast_tillaggskostnader_variabel_tariff_sek_kwh_inkl_moms')|float+(current_price*0.25)}}

The 'sensor.endast_tillaggskostnader_variabel_tariff_sek_kwh_inkl_moms' helper looks like this:
```
{% set s = {
    "hourly_fixed_cost": 0.081,
    "winter_night": 0.096,
    "winter_day": 0.56,
    "summer_day": 0.096,
    "summer_night": 0.096,
    "energy_tax": 0.428,
    "vat": 1.25
}
%}
{% if now().month >= 4 and now().month < 11 %}
    {% if now().hour >= 6 and now().hour < 22 %}
        {{ (s.summer_day + s.hourly_fixed_cost + s.energy_tax | float)*s.vat }}
    {% else %}
        {{ (s.summer_night + s.hourly_fixed_cost + s.energy_tax|float)*s.vat }}
    {% endif %}
{% else %}
    {% if now().hour >= 6 and now().hour < 22 %}
        {{ (s.winter_day + s.hourly_fixed_cost + s.energy_tax | float)*s.vat }}
    {% else %}
        {{ (s.winter_night + s.hourly_fixed_cost + s.energy_tax | float)*s.vat }}
    {% endif %}
{% endif %}
```

## Describe the bug
When calculating future prices using the helper, future prices are incorrect if calculated during a different tariff. Additional costs are low from 22 to 06, but if calculated between 06 and 22, they are **calculated using the tariff valid at the time of calculation instead of the actual (future) timestamp**.

This leads to incorrect future prices (in the attributes), which in turn makes this integration unusable when it comes to schedule consumtion based on future electricity prices - e.g. EV charging when the price is low.

Here are some screenshots to illustrate. Note that the same hours (21, 22, 23) are marked in both screenshots. 

### Screenshots
This is how prices look before 22:00:
![image](https://github.com/user-attachments/assets/40a30d7b-dfc4-4415-8014-ee273da9d19a)

This is how prices look after 22:00. The same hours are marked in this screenshot.
![image](https://github.com/user-attachments/assets/12b034a6-567a-48c5-b986-ac8d6a2e6992)

I'm guessing this is since now() uses the current time - which is logical and probably correct. There needs to be a different way of calculating future prices.

## Debug log
Not relevant imo.

**Comment by Hellowlol** [comment]
This isnt a bug. It’s working as indented. There is a special logic in the template rendering in the sensor that ensures that now() is always related to the current price. Note: this documented in the wikis If you try to render the template outside the context of the sensor it will return the incorrect future price. 

My suggestion is to use the template option in the sensor.

**Comment by zanoii** [comment]
> This isnt a bug. It’s working as indented. There is a special logic in the template rendering in the sensor that ensures that now() is always related to the current price. Note: this documented in the wikis If you try to render the template outside the context of the sensor it will return the incorrect future price.
> 
> My suggestion is to use the template option in the sensor.

Thank you for pointing this out. I was unable to find any content at all under the "Wiki" menu item, but the readme.md had the info below, which I guess I should have read with greater care: 
> now(): this always refer to the _**current**_ hour of the price

I can't really see the point with the helper script "Example 5: Seasonal peek and off-peek overhead" if it always calculates values based on the current hour, but I assume there must be use cases where you'd want this.

Again, thanks for pointing my mistake out. I appreciate it a lot since everything now works as intended and I can stop creating workarounds. 🙂
