### ISSUE TITLE
Reload the integration once integration fails to update raw data?

### ISSUE THREAD

**Issue by anandlar** [custom-components/nordpool#447]
I would like to trigger reload of the integration once integration fails to update raw data?

BR
Anders

**Comment by stefancn** [comment]
Me to .... 

Regards ...

Stefan

**Comment by developerfromjokela** [comment]
Can you clarify what you mean exactly? any info or screenshot would be helpful :)

**Comment by anandlar** [comment]
Hi, I would like to be able to do it like the screenshot shows
![image](https://github.com/user-attachments/assets/f544879b-f54e-4098-a1c4-fb2e67d0fb57)

**Comment by roccolord** [comment]
Reload is available? 

![image](https://github.com/user-attachments/assets/eec9bb1b-0355-4be5-acb4-b54e55410f92)

**Comment by anandlar** [comment]
True, it was not their in an earlier version. Sorry about my mistake
