### ISSUE TITLE
Nordpool stopped working 

### ISSUE THREAD

**Issue by SebastianTheCat** [custom-components/nordpool#453]
It stopped working and when you delete it and try to re install it, then it would not be downloaded from hacs, this version can not work with hacs 

Someone updated something that wasn't broken before, and now it seems like it can not be fixed, at least not easy.

**Comment by SebastianTheCat** [comment]
It works again

**Comment by Safs** [comment]
Same here! Does not work.

**Comment by SebastianTheCat** [comment]
It works again
