### ISSUE TITLE
Q: Additional Cost based on date... again

### ISSUE THREAD

**Issue by boelle** [custom-components/nordpool#457]
i use this template to add fee's on top of what nordpool reports

{% set s = {
    "cost": 88.6,
    "summer": {"night": 5.5125, "day": 8.2725, "eve": 21.5025, "eve2": 8.2725, "fail": 0.0},
    "winter": {"night": 5.5125, "day": 16.545, "eve": 49.6275, "eve2": 16.545, "fail": 0.00}
}
%}
{% set season = 'summer' if 4 <= now().month < 10 else 'winter' %}
{% if 0 <= now().hour < 6 %}
  {% set tod = 'night' %}
{% elif 6 <= now().hour < 17 %}
  {% set tod = 'day' %}
{% elif 17 <= now().hour < 21 %}
  {% set tod = 'eve' %}
{% elif 21 <= now().hour < 24 %}
  {% set tod = 'eve2' %}
{% else %}
  {% set tod = 'fail' %}
{% endif %}
{{ s[season][tod] + s.cost}}

it should work with the tariff model 3 in denmark

![image](https://github.com/user-attachments/assets/4fe61c38-b275-4ef7-b44d-3a5ccbbb1bd4)

fee's for each kwh depends on summer/winter and what time of day it is

the prices today are:

![image](https://github.com/user-attachments/assets/02aeae5e-fa25-4664-a2d1-849a6d93b595)

but i get much lower prices

![{FBCC8989-C282-4C72-BFAE-FEF9A767E778}](https://github.com/user-attachments/assets/39b283ba-c507-459f-a581-1fb1de93c008)

![{1F7C527E-C0D9-4C98-B632-6CB09DBFFF15}](https://github.com/user-attachments/assets/e4db378d-b563-46eb-917f-18f840fef490)

have i f'ed up or is the data pulled from nordpool wrong?

one thing i have never figured is to add VAT which is 25% for denmark... how do i do that?

**Comment by boelle** [comment]
as for the prices... they are listed in MWh

if during config i select that i get close

![{57CB131C-2A53-4F45-A627-BC3A8B7CE310}](https://github.com/user-attachments/assets/fca8f68a-f44b-4b98-aeab-bbf464882f2a)

but my template is based on KWh... so do i just select KWh instead during config?

**Comment by boelle** [comment]
so, with this config i'm close....

![{6953FC9D-29C1-4458-BDA4-3B34A4438AAA}](https://github.com/user-attachments/assets/26b5b249-7cad-4fef-b193-03dc0173a53a)


![{C293E6CA-E336-4CAE-815A-969E5C750AFC}](https://github.com/user-attachments/assets/4236c317-3b92-4e9b-ad5d-9a3ab58807e4)


its just 100x to big... the number should be 547,6402 Øre/kWh which would turn in to 5,476402 kr

**Comment by boelle** [comment]
so to sum it up, i need to add 25% and divide by 100

**Comment by boelle** [comment]
so what % is used when i tick include VAT ?

**Comment by Hellowlol** [comment]
I can’t remember, I think it 24% but please check the sensor.py code file.

**Comment by boelle** [comment]
Must be line 35 and 36? 25%

lør. 28. dec. 2024 12.41 skrev Steffen Fredriksen ***@***.***

**Comment by Hellowlol** [comment]
Yes, closing this is is off topic and not really a issue with the integration. Feel free to open a discussion if you need assistance.

**Comment by boelle** [comment]
nope, but it was the only place i could find asking for help and guidiance... hence the Q: in the title
