### ISSUE TITLE
Nordpool pulled all currencies exept EUR?

### ISSUE THREAD

**Issue by MissMusic** [custom-components/nordpool#47]
The addon presented some really low prices for tomorrow so i got suspicious and checked the website.

https://www.nordpoolgroup.com/Market-data1/Dayahead/Area-Prices/ALL1/Hourly/?view=table

I had the nordpool component configured for prices in SEK, but that option is no longer available at nordpool it seems.

**Comment by MissMusic** [comment]
It turns out you can still get the currency options by selecting a specific country:
https://www.nordpoolgroup.com/Market-data1/Dayahead/Area-Prices/SE/Hourly/?view=chart

**Comment by jonasbkarlsson** [comment]
Seems like you get the price in EUR, even if you have configured `currency: "SEK"`

**Comment by MissMusic** [comment]
Yes, i thought that was obvious but i now realize i missed to add that that was my suspicion as well. 😊

**Comment by Hellowlol** [comment]
There was a bug in the api yesterday so today's price might not be correct. Reboot home assistant (was a bug in the sensor reload) and check again. Open a new issue using the issue template if the problem persists
