### ISSUE TITLE
Is todays sportprice correct

### ISSUE THREAD

**Issue by baunan** [custom-components/nordpool#55]
No direct error, but it looks like today's prise is off with a factor of 10.
Attached a picture from today's values reported by this add-on, which is great by the way. And a snapshot from Nordpol website.

![image](https://user-images.githubusercontent.com/59838425/107766797-4fd4b880-6d34-11eb-8273-19ca98b6dbcb.png)
![image](https://user-images.githubusercontent.com/59838425/107766823-5b27e400-6d34-11eb-8fc5-4ec2c01d5489.png)

Tomorrows figures do looks to be correct.

**Comment by Hellowlol** [comment]
Make sure you use the latest update, if you do reload the integration. If the error persist open a new issue using the issue template
