### ISSUE TITLE
Reload buggy if multiple np sensors 

### ISSUE THREAD

**Issue by Hellowlol** [custom-components/nordpool#56]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
Reload does not work correctly if multiple nordpool sensors is active

## Debug log

```text

Add your logs here.

```

**Comment by kalaws** [comment]
Any progress on this bug? I have two sensors, which only differ by their additional costs setting (one set of additional 'costs' for import, one set for export). One of them (always the same one) sometimes reverts to 'Unknown' state. Any idea if this affects calculations within Energy dashboard, if it reverts back to a valid state within the hour?

Also, is it accepted to reproduce the two sensors in their entirety in configuration.yaml, or is there a way that one could only restate the changed variables for the second sensor? Would be more elegant, I suppose (and that would perhaps also be the only benefit).

**Comment by Hellowlol** [comment]
I’m dont understand your problem. This issue is related to how a reload of the platform is handled.
(Error in the log)

If you have any other issues you should open a new issue using the issue template.

**Comment by kalaws** [comment]
Ok, so to stick with the issue, I’m completely new to HA (two days in), so I honestly don’t have a clue. 

Here’s what the two sensor histories look like:

![7B761B82-A897-46B5-8DAB-BC2886F899B0](https://user-images.githubusercontent.com/90693616/133491432-617ecef7-64f8-4178-b6fa-0f7ab7f82869.png)
![58802326-49E6-4207-B4EA-FA06DDBB0D7A](https://user-images.githubusercontent.com/90693616/133491435-65c2b777-b759-49c9-a54d-f63c480cb43c.png)

Import sensor has some interruptions, export sensor does not. I haven’t been able to find a relevant log. Where would that be? Sorry for being such a noob - I appreciate the work done!

**Comment by kalaws** [comment]
Ok, managed to use templates instead. Will see if the interruptions stop.

**Comment by PalleRaa** [comment]
> Ok, managed to use templates instead. Will see if the interruptions stop.

Did this work? Can you show me how you set it up using template sensor? I need to have two almost identical sensors. One which has pretty advanced additional cost settings. The other sensor should just be a copy of the first, but substract a fixed amount for each kWh.

**Comment by marparts** [comment]
I whant to add two sensord. Buy and sell.
I can add only one Nordpool sensor. Second one is "unknown"

```
  - platform: nordpool
    region: "EE" 
    friendly_name: "Nordpool"
    price_in_cents: True
    precision: 3 
    additional_costs: '{% set s = {
    "day": 0.0329,
    "night": 0.019,
    "GreenMarginaalAktsiis": 0.0156
}
%}
{% if now().month >= 3 and now().month <11 %}
    {% if now().hour >=8 and now().hour <=23 and now().weekday() in (1,2,3,4,5) %}
        {{s.day+s.GreenMarginaalAktsiis}}
    {% else %}
        {{s.night+s.GreenMarginaalAktsiis}}
    {% endif %}
{% else %}
    {% if now().hour >=7 and now().hour <=22 and now().weekday() in (1,2,3,4,5) %}
        {{s.day+s.GreenMarginaalAktsiis}}
    {% else %}
        {{s.night+s.GreenMarginaalAktsiis}}
    {% endif %}
{% endif %}'

  - platform: nordpool
    region: "EE" 
    friendly_name: "Nordpool Sell"
    price_in_cents: True
    precision: 2
    additional_costs: -0.0049
```

**Comment by and117** [comment]
I have the same issue. Of my three sensors only one is updated after a HA reboot. So I have now created a Node Red flow that restart each sensor with 5sec delay after the HA restart. If I restart all at the same time only one is updated.

**Comment by Hellowlol** [comment]
@and117 thats a different issue then this one. Please open a new issue and provide logs

**Comment by Hellowlol** [comment]
Should be ok in 0.0.8
