### ISSUE TITLE
Additional cost: yearly/monthly fixed cost + kwh variable cost

### ISSUE THREAD

**Issue by jkaberg** [custom-components/nordpool#69]
So this just me thinking out loud; but it would be nice if we somehow could add these addiational costs in a sane and correct way:

- Yearly cost (for example grid rent)
- Monthly cost (for example monthly cost regarding the power subscription)
- Additonal kwh cost (for example additional kwh cost due to the power subscription)

The above in addition to the current kwh spot would be ideal which would boild down to an nice total kwh price

I did notice the tariff example in the README.md, however I can't wrap my head around the yearly/monthly costs if at all possible? 

As an example I have:

```
Yearly grid rent: 2345 NOK
Monthly power subscription: 9 NOK
kwh charge grid rent: 0,452 NOK
kwh charge power subscription: 0,035 NOK
+ spot price
```

**Comment by jkaberg** [comment]
Awnsering my own question;

```
'{% set s = {
	"grid_yearly_cost": 2345,
	"grid_kwh_cost": 0,452,
	"psub_monthly_cost": 9,
	"psub_kwh_cost": 0,35
}
	set fixed_cost = (((s.grid_yearly_cost+(12*s.psub_monthly_cost))/365)/24)|float
%}
{{ (s.grid_kwh_cost+s.psub_kwh_cost)+fixed_cost|float }}'
```

**Comment by Hellowlol** [comment]
The example in the readme is to show how a complex tariff can be added. Most peoples tariff simpler, i can add a simpler example and add some comments

**Comment by bjQrnen** [comment]
Would it not be more correct to divide the yearly grid costs with the estimated yearly consumption?

 - platform: nordpool
    VAT: True
    currency: "NOK"
    region: "Tr.heim"
    precision: 3 
    price_type: kWh
    additional_costs: '{% set s = {"grid_yearly_cost": 2345,
           "Estimated_yearly_consumption_kwh": 5000,
            "grid_kwh_cost": 0.452,
            "psub_monthly_cost": 0.0,
            "psub_kwh_cost": 0.0
            }%}{% set fixed_cost = (((s.grid_yearly_cost+(12*s.psub_monthly_cost))/Estimated_yearly_consumption_kwh)|float %}{{(s.grid_kwh_cost+s.psub_kwh_cost)+fixed_cost|float }}'
