### ISSUE TITLE
Need manifiest version for Home Assistant 2021.6

### ISSUE THREAD

**Issue by mariwing** [custom-components/nordpool#71]
## Version of the custom_component

0.0.3

## Describe the bug
A manifest.json file with a version is mandatory with Home Assistant version 2021.6 and this component no more loads without it. Greatly appreciated if this can be fixed, thanks!

```

**Comment by oscfor** [comment]
https://community.home-assistant.io/t/2021-6-a-little-bit-of-everything/312796/241?fbclid=IwAR3M5a4qkOSPPKu3UF6tZyPLgARAFPKDwonrYBED2jWhxohoGFCPukGxgvA
