### ISSUE TITLE
additional cost help

### ISSUE THREAD

**Issue by kuradi** [custom-components/nordpool#75]
guys,

need some help cause im not really strong in javascript.
in estonia we have price day summertime monday-friday 8-24 and price day wintertime monday-friday 7-23; price night summertime monday-friday 24-8 and price night wintertime monday-friday 23-7 + also on weekends we have nightprice
as i understand code below its not using summertime checking, its just checks which month we have, right? how to modify code below to use dst?

{% set s = {
  "hourly_fixed_cost": 0.5352,
  "winter_night": 0.265,
  "winter_day": 0.465,
  "summer_day": 0.284,
  "summer_night": 0.246,
  "cert": 0.01
  }
%}
{% if now().month >= 5 and now().month <11 %}
    {% if now().hour >=6 and now().hour <23 %}
        {{s.summer_day+s.hourly_fixed_cost+s.cert}}
    {% else %}
        {{s.night+s.hourly_fixed_cost+s.cert}}
    {% endif %}
{% else %}
    {% if now().hour >=6 and now().hour <23 %}
      {{s.winter_day+s.hourly_fixed_cost+s.cert}}
  {%else%}
      {{s.winter_night+s.hourly_fixed_cost+s.cert}}
   {% endif %}
  
{% endif %}

**Comment by Hellowlol** [comment]
now() is in local time.

**Comment by nelgi** [comment]
> guys,
> 
> need some help cause im not really strong in javascript.
> in estonia we have price day summertime monday-friday 8-24 and price day wintertime monday-friday 7-23; price night summertime monday-friday 24-8 and price night wintertime monday-friday 23-7 + also on weekends we have nightprice
> as i understand code below its not using summertime checking, its just checks which month we have, right? how to modify code below to use dst?
> 
> {% set s = {
> "hourly_fixed_cost": 0.5352,
> "winter_night": 0.265,
> "winter_day": 0.465,
> "summer_day": 0.284,
> "summer_night": 0.246,
> "cert": 0.01
> }
> %}
> {% if now().month >= 5 and now().month <11 %}
> {% if now().hour >=6 and now().hour <23 %}
> {{s.summer_day+s.hourly_fixed_cost+s.cert}}
> {% else %}
> {{s.night+s.hourly_fixed_cost+s.cert}}
> {% endif %}
> {% else %}
> {% if now().hour >=6 and now().hour <23 %}
> {{s.winter_day+s.hourly_fixed_cost+s.cert}}
> {%else%}
> {{s.winter_night+s.hourly_fixed_cost+s.cert}}
> {% endif %}
> 
> {% endif %}

try this:

`    {% macro calc(v) -%}
    {%set d = {"operator_margin": 0.0015,
    "electricity_tariff": 0.00447,
    "renewable_tariff": 0.0104,
    "nw_fee_night": 0.0246,
    "nw_fee_day": 0.0423
    } %}
    {%set day_price = v + ((d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_day) * 1.2 | float ) | round(4)%}
    {%set night_price = v + ((d.operator_margin + d.renewable_tariff + d.electricity_tariff + d.nw_fee_night) * 1.2 | float ) | round(4)%}
    {% if now().timetuple().tm_isdst == 1%}
    {% if now().hour >= 8 and now().weekday() >= 0 and now().weekday() < 5%}
    {{day_price}}
    {% else %}
    {{night_price}}
    {% endif %}
    {% else %}
    {% if now().hour >= 7 and now().hour < 23 and now().weekday() >= 0 and now().weekday() < 5%}
    {{day_price}}
    {% else %}
    {{night_price}}
    {% endif %}
    {% endif %}
    {%- endmacro %}
    {{calc(0)}}`
