### ISSUE TITLE
nordpool_kwh_dk1_dkk_3_10_025 no values for tomorrow

### ISSUE THREAD

**Issue by wormiedk** [custom-components/nordpool#85]
When configuring this sensor I get no values for tomorrow either in raw or in the tomorrow attribute. Today seems to work as expected

**Comment by havardthom** [comment]
My nordpool sensor (nordpool_kwh_oslo_nok_3_095_025) also stopped working at 00:00 yesterday. I restarted HASS today  and it is working again.

**Comment by Hellowlol** [comment]
Turn on debug logging. I dont have enough info to fix this. Open a new issue with the log and ill get this sorted. You also need to add your template as the traceback telles me that you use a custom template
