### ISSUE TITLE
Feature request: Support Elvia GridTariffAPI in 2022

### ISSUE THREAD

**Issue by havardthom** [custom-components/nordpool#86]
In 2022 Norway is changing its Grid Tariff model (https://www.elvia.no/nettleie/alt-du-ma-vite-om-ny-nettleie-for-2022/). This means dynamic grid tariff prices based on network use. Elvia has released a GridTariffAPI to offer all private grid tariffs and its prices per hour. Would love a way to integrate this API with the nordpool sensor, e.g. provide some url and basic auth in config to allow the sensor to fetch grid tariff prices per hour. 

Docs for GridTariffAPI: https://assets.ctfassets.net/jbub5thfds15/1mF3J3xVf9400SDuwkChUC/a069a61a0257ba8c950432000bdefef3/Elvia_GridTariffAPI_for_smart_house_purposes_v1_1_20210212.doc.pdf

**Comment by Hellowlol** [comment]
Lol, they really did it. More death inc ☹️. I will not implement something thats just for Norwegian users. The template was added so people could add there own tariffs. Has the prices been listed public anywhere?

**Comment by havardthom** [comment]
No, don't think the prices has been released yet. Come to think of it, I agree that this grid tariff API would probably be best in a separate sensor, would give more flexibility for tracking and integrating prices to existing solutions.

**Comment by Hellowlol** [comment]
This seems to only be for Elvias consumers so pretty useless for other people. I would I use a rest sensors to get the info you need in combination with highest hourly use from the Han port and add that to your template. Current hour +price and the energy is safe you give you what you need.

If I provider has national coverage for all grid company’s I’ll add that as a separate component
