### ISSUE TITLE
Suggestion to add additional sensor to show price with and without additional cost

### ISSUE THREAD

**Issue by ThoStaKa** [custom-components/nordpool#88]
I am displaying the power price with apex charts card. It would make things a lot simpler if the integration could optionally create 2 sensors. 1 with and 1 without additional costs. 

**Describe the solution you'd like**
2 alternatives that I can think of:
1: One "duplicate" nordpool sensor similar to the existing, but without additional costs
2: Additional attribute list (unsure of the correct name) without additional costs. Se suggestion below:

############
`raw_today:
  - start: '2021-11-30T00:00:00+01:00'
    end: '2021-11-30T01:00:00+01:00'
    value: 76.277`
    value_without_additional: xx.xxx`
############

**Describe alternatives you've considered**
I tried stacking in apex chart, but doing the work inside og Norpool integration might be simpler.

**Additional context**

**Comment by Hellowlol** [comment]
Make two sensors? Just add another level of rounding then the first sensor

**Comment by ErikH2** [comment]
I also have problems with duplicating the sensor, 
I added 2 pices in the sensor.yaml file starting with - platform: nordpool and so on,
But it only collects data from the upper of the 2 different settings.
Can anyone share how they solved the dual sensor integration.
