### ISSUE TITLE
device_state_attributes

### ISSUE THREAD

**Issue by prilly-dev** [custom-components/nordpool#91]
Entity sensor.nordpool_kwh_oslo_nok_2_095_025 (<class 'custom_components.nordpool.sensor.NordpoolSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by gulli1986** [comment]
Getting the following warning after update to 2021.12:

`2021-12-11 21:53:27 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.nordpool_kwh_oslo_nok_3_10_025 (<class 'custom_components.nordpool.sensor.NordpoolSensor'>) implements device_state_attributes. Please report it to the custom component author.`

It looks like it is just a name change from "device_state_attributes" to "extra_state_attributes" name change.
Anyone knows how to fix this? Is it just to replace all "device_state_attributes" by "extra_state_attributes" in all files?

**Comment by prilly-dev** [comment]
property device_state_attributes

    Return entity specific state attributes.

    This method is deprecated, platform classes should implement extra_state_attributes instead

http://dev-docs.home-assistant.io/en/master/api/helpers.html

**Comment by prilly-dev** [comment]
Seems this is already taken care of: https://github.com/custom-components/nordpool/pull/90

**Comment by Hellowlol** [comment]
This is fixed.
