### ISSUE TITLE
Create wiki with Tariff configurations for providers or regions

### ISSUE THREAD

**Issue by LordMike** [custom-components/nordpool#92]
**Is your feature request related to a problem? Please describe.**
I would like to create a correct tarriffs calculation that matches what I see in Denmark (provider: Modstrøm). This could be tricky, although I think most of the additional costs are fixed, and not varying by time of day or year.. 

**Describe the solution you'd like**
It could be awesome to have a pre-built list of tarriff configurations available, perhaps on a wiki or such. It could be contributed by users as they make the configurations to match.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Hellowlol** [comment]
Feel free to get started.

**Comment by LordMike** [comment]
I've added a PR, I'm still working on it. I found out that while I thought the danish taxes were straightforward, they weren't.. So I'm working on that.

This makes me wonder - is there a way we can programmatically get these tax values - likely not, but would it then be possible to store a file on this github repo, with all applicable tax values - which the integration could then fetch every N days? (or store in the file a "valid_until" value to cache it as much as possible).

**Comment by runemoennike** [comment]
You can get them from Eloverblik.dk, through an API. In fact, I've created a PR to the Eloverblik integration that fetches the tariffs and expose them as a sensor. I've also added an example template sensor for combining that with the Nordpool data.

It's here for now: https://github.com/JonasPed/homeassistant-eloverblik/pull/57
