### ISSUE TITLE
Discussion: Should additional_costs include vat or not?

### ISSUE THREAD

**Issue by cnrd** [custom-components/nordpool#95]
I was the person who created this pull request: https://github.com/custom-components/nordpool/pull/80

After looking into the code I can determine that I was unfortunately wrong. VAT is not added on top of the additional_cost: https://github.com/custom-components/nordpool/blob/629de21dfe3cd9f42bc17ed56935ddd1ea45a34d/custom_components/nordpool/sensor.py#L273-L278

I think it should be added on top ie.:
````python
        if self._price_type in ("MWh", "mWh"):
            price = (template_value / 1000 + value) * float(1 + self._vat)
        else:
            price = (template_value + value / _PRICE_IN[self._price_type]) * (
                float(1 + self._vat)
            )
````

As that is how I would calculate the total: Add up everything and then add the VAT on top.

This may however not be desirable, as there may be countries where VAT is not paid on top of those costs?

Let me know what you think.

**Comment by Hellowlol** [comment]
It should not be included.
