### ISSUE TITLE
Currency returns EUR when NOK is selected

### ISSUE THREAD

**Issue by bjornidar** [custom-components/nordpool#97]
## Version of the custom_component
v0.0.3

## Configuration
platform: nordpool
currency: "NOK"
low_price_cutoff: 0.95
region: "Oslo"
precision: 2
price_type: kWh
additional_costs: "{{0.0|float}}"

## Describe the bug
currency set to NOK returns EUR.

**Comment by Hellowlol** [comment]
I suspect nordpool is having issues with the api. My prices for today is correct. Have you tried reloading the sensor?

**Comment by bjornidar** [comment]
It has been like this since I installed it in the end of November... The price seems to be OK, it's just the currency/ symbol not being correct.

**Comment by Hellowlol** [comment]
Are you referring to the icon?

**Comment by bjornidar** [comment]
Both the icon and the sensor tex
![1](https://user-images.githubusercontent.com/53019262/147089548-69489027-0125-425a-ae32-fb3c77aeb568.png)
![2](https://user-images.githubusercontent.com/53019262/147089552-62cd197e-2b76-450d-bfbf-8773e9e80189.png)
t

**Comment by Hellowlol** [comment]
I dont understand how this is possible the unit of measurement is currency/price_type eg NOK/kWh.

Try setting up the sensor using the webui

**Comment by Hellowlol** [comment]
What sensor is this? I can't recognize the name. Do you mind showing me all the sensor attributes?
